### ISSUE TITLE
Slightly move call to getTransition()

### ISSUE THREAD

**Issue by Djules** [luruke/barba.js#10]
Could be handy to move call to `getTransition` right after the new url has been added to the history, so we can use `currentStatus` method in our own method `getTransition`.

Line 238 of Pjax.js

```javascript
this.History.add(newUrl);

var transition = Object.create(this.getTransition());
```

instead of 

```javascript
var transition = Object.create(this.getTransition());

this.History.add(newUrl);
```

**Comment by luruke** [comment]
Hi @djules.
Thanks for the issue.

It totally makes sense!

Before implementing it I will just do some tests.

Cheers!

**Comment by luruke** [comment]
Hi @Djules!
Just implemented this little change.
Build and npm package updated.

Thank you again, have a nice weekend :+1:

**Comment by Djules** [comment]
Brilliant! Cheers!
