### ISSUE TITLE
re: reinitialze js functions

### ISSUE THREAD

**Issue by anartfulscience** [luruke/barba.js#101]
Hello,

Firstly thanks for creating this, it works really well!

I've an issue reloading some js functions though. What's the best way to reinitialze them?

I'm using the smooth scroll polyfill and placing the below script within the fadeIn: function(), but it's not firing when you revisit the page. Can you help please.

Thanks, Stephen 

window.addEventListener('load', function() {

	    // scroll into view
      document.querySelector('.js-scroll-into-hello').addEventListener('click', function(e) {
        e.preventDefault();
        document.querySelector('section:first-of-type').scrollIntoView({ behavior: 'smooth' });
      });

});

**Comment by luruke** [comment]
Hello @anartfulscience , 
You can use barba.js events and 'reinitialise' your code:
http://barbajs.org/events.html

**Comment by anartfulscience** [comment]
Thanks Luruke,

One the thing. I'm integrating barba within wordpress and it's creating an issue when your logged into the CMS. Is there away to blacklist the Wordpress admin links like with smooth state? The notes are here regards SmoothState link blacklisting https://webdesign.tutsplus.com/tutorials/how-to-integrate-smoothstatejs-into-a-wordpress-theme--cms-26610

Thanks, Stephen

**Comment by luruke** [comment]
Hello @anartfulscience ,
you can check this old issue: https://github.com/luruke/barba.js/issues/47#issuecomment-237813998
