### ISSUE TITLE
Server Caching?

### ISSUE THREAD

**Issue by hartey11** [luruke/barba.js#102]
Hi,

Does Barba retrieve cached versions of pages from the server? We are using WP Engine which heavily caches on the server. But when we AJAX to a page it's a lot slower than if we navigate directly to it. The page uses a lot of PHP and it looks like the AJAX request is forcing the server to reprocess the page rather than use the cached version.

**Comment by luruke** [comment]
Hello @hartey11,
Barba.js sends a normal xhr request (as you can see here https://github.com/luruke/barba.js/blob/master/src/Utils/Utils.js#L51).

The only "difference" is that adds a `x-barba` header, but I'm not sure how this can affect it.

I don't know how WP Engine works under the hood, so I can't help on that way.

I'd suggest to debug the HTTP requests, and response headers

**Comment by luruke** [comment]
Hello @hartey11 ?
Did you solve at the end?

**Comment by hartey11** [comment]
Hi @luruke,

WP Engine confirmed that AJAX requests bypass their caching system. As a solution I had to setup wordpress to generate a html file everytime the page saves, then insert that into the theme file. Worked a treat and now its the fasted loading page on the site!

**Comment by luruke** [comment]
@hartey11 , strange.

Barba.js uses a simple `XMLHttpRequest` request (https://github.com/luruke/barba.js/blob/master/src/Utils/Utils.js#L51), without any special parameters to force the cache.

I don't know how WP Engine works, so I guess I can't help you further.
