### ISSUE TITLE
Pass click-event to BaseTransition.start

### ISSUE THREAD

**Issue by chrisbergr** [luruke/barba.js#103]
Hi @luruke,

thanks for sharing this awesome lib with us :)

In one of my projects I try to combine it with an additional function showing an overlay that starts on the click (/tap) position with 0px width and height, transforming to fullscreen in a defined time.

```javascript
    $( '.internal' ).bind( 'click', function (e) {
        ShowOverlay(e.clientX, e.clientY);
    });
```

That works like a charm, but after combining it with barba, because of the `preventDefault` call, it doesn't work anymore.

I'd like to call this `ShowOverlay` function in the `BaseTransition.start` function, but I don't see a possibility to pass the click event to it.

```javascript
    var FadeTransition = barba.BaseTransition.extend({
        start: function() {
            Promise
                .all([this.newContainerLoading, this.fadeOut()])
                .then(this.fadeIn.bind(this));
        }
    });
```

Is there a possibility to get the x/y position of the event? -If not, this would be my request for the next version of this great script.

Best, Chris

**Comment by luruke** [comment]
Hi there, I'm on mobile so my reponse will be quite direct.

You can save the item clicked via the event 'onlinkclicked' in a global variable and then use it in your transition. If you go through the demos you should find a similar usage.

Let me know if this helps otherwise I'll try to reply with more detail when I'll come back from holidays.

Cheers

**Comment by chrisbergr** [comment]
Thank you for your fast response.
It took me some time to figure out that I have to use the dispatcher to catch your referred event. After realizing that it's pretty clear now. In my current sequence I don't need to share the event in a global variable, I can call my function directly.

Just using the following:

```javascript
    Barba.Dispatcher.on('linkClicked', function(el, e) {
        ShowOverlay(e.clientX, e.clientY);
    });
```

Yes, it's documented on the [events](http://barbajs.org/events.html) page of the documentation and I didn't get it before.

So thank you for your help.

**Comment by ZachSaucier** [comment]
Is there a way to do this in v2? I don't see any link event listener in the docs but I could be missing something.
