### ISSUE TITLE
Add version 1.0.0 to the jsdelivr CDN

### ISSUE THREAD

**Issue by grenouille220** [luruke/barba.js#105]
Would it be possible to add the latest stable version to [jsdelivr](https://www.jsdelivr.com) please ?

You can fork the project and submit a pull request with an info.ini + update.json from github's web interfaces as described here:
- https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

If you can't, I could submit it on your behalf.

Best

**Comment by luruke** [comment]
Hello @grenouille220 ,
please do it 👍 


Thank you

**Comment by grenouille220** [comment]
Here it is: [https://www.jsdelivr.com/projects/barba.js](https://www.jsdelivr.com/projects/barba.js) !

Regards

**Comment by luruke** [comment]
Thank you @grenouille220 !
