### ISSUE TITLE
Get custom transitions to work with ES6?

### ISSUE THREAD

**Issue by intelligence** [luruke/barba.js#107]
Hey!

Thanks for Barba, it's great!

I'm pretty new to Barba and got limited javascript skills, I'm working with a stack that relies on ES6 so I need to get it to run there, but I'm having a hard time. Afaik "this" is not available in the same sense with the scopes in ES6 or something like that, am I right?

So how can I get it to work? 

What I've got so far is this
```
    const BasicTransition = Barba.BaseTransition.extend({
      start: () => {
        this.newContainerLoading.then(this.finish.bind(this));
      },

      finish: () => {
        document.body.scrollTop = 0;
        this.done();
      },
    });

    Barba.Pjax.getTransition = function () {
      return BasicTransition;
    };
```

Which throws `Uncaught TypeError: Cannot read property 'then' of undefined` as "this" doesn't have newContainerLoading I guess.. Sorry for my limited skills with this, would appreciate your input!

**Comment by luruke** [comment]
Hi @intelligence ,
ES6 has introduced arrow function, which automatically bounds this to the parent scope.

This being said you can always use the classic `function() {}`, arrow function is a "new feature", not a replacement of the function declaration.

Cheers.

**Comment by intelligence** [comment]
Thank you so much!
