### ISSUE TITLE
Nested containers

### ISSUE THREAD

**Issue by derbenner** [luruke/barba.js#109]
nice tool! but now we need barba in barba.
in the 1st .barba-container we need a new .barba-container and in next to this are links which should be loaded inside the 2nd barba-container, is there any way?
i must specify the inner links to call the inner barba, all other links should be replace the complete content in the 1st container.

thank you very much! best greetings from germany :]

**Comment by luruke** [comment]
Hi @derbenner ,
If I remember correctly this topic was already discussed but I can't find the issue right now.

Actually what you are describing is not supported by barba.js.

The main philosophy behind the library is that it works as progressive enhancement, each page needs to be accessible directly.
Without javascript enabled, your website needs to work normally.

Being said that, having nested containers will results in dynamically create "pages" that don't exists in reality. You won't be able to share an URL that replicates that page.

So, doing what you are asking it's technically possible, but it's not currently supported.

Hope it makes sense.
Cheers
