### ISSUE TITLE
Option to prefetch on mousedown and touchstart

### ISSUE THREAD

**Issue by shrpne** [luruke/barba.js#110]
So I prefer prefetch on mousedown and touchstart, it is a bit slower than mouseover, but make no unnecessary request ans still save some time

**Comment by luruke** [comment]
Hi @shrpne,
Yep, that makes sense.

I will think if adding an option for this.

Meanwhile If someone needs it, you can replace the Prefatch init function before using it
(it just changes the event from `mouseenter` to `mousedown`)

```javascript
Barba.Prefetch.init = function() {
  if (!window.history.pushState) {
    return false;
  }

  document.body.addEventListener('mousedown', this.onLinkEnter.bind(this));
  document.body.addEventListener('touchstart', this.onLinkEnter.bind(this));
}
```
