### ISSUE TITLE
How to prevent memory leaks?

### ISSUE THREAD

**Issue by samburgers** [luruke/barba.js#111]
Hi there, 

Is there any documentation anywhere about how to best prevent memory leaks?

Here is a snapshot of Nodes and Listeners buildup over about 10 simple page navigations with barba. Nothing else fancy going on at all.

Thanks!

<img width="1093" alt="screen shot 2017-01-21 at 1 41 03 pm" src="https://cloud.githubusercontent.com/assets/1476939/22171347/a8f3d982-dfdf-11e6-96f5-ac6ff6dbd43a.png">

**Comment by luruke** [comment]
Hello @samburgers !
Thanks for pointing this.

So, just to better understand, the graph is coming from a simple website with just pjax navigation enabled?

Do you also use Barba.js Views?
Have you tried disabling cache? (`Barba.Pjax.cacheEnabled = false;` before starting)

Thank you!

**Comment by derbenner** [comment]
Hi,

i have the same problem, Barba uses so much memory and cpu that the site's stucks.
i added cache=false befor starting but no dirrent example site:
http://s603881526.online.de/clickandbuilds/TYPO3/Akkurat_Inkasso/
use the image or topnavigation, after 4-5 sites you will see that the animation stucks

**Comment by derbenner** [comment]
I found my Issue, i have a html5 Video tag inside, and every barba request it load the video again and again
any solution to remove the video tag from response?

**Comment by luruke** [comment]
Hello @derbenner,

not sure what your problem is, but if you are using any server side language, you can check for the `x-barba` header, and if exists, not display the `video`.

In fact each xhr request made by barba.js include this special HTTP header (https://github.com/luruke/barba.js/blob/master/src/Utils/Utils.js#L69).

Hope it makes sense,
Cheers.

**Comment by samburgers** [comment]
Apologies it looks like the eventListeners weren't being removed properly in the case above, which was causing the listener buildup, duh. for anyone else that stumbles across this, double check any listeners you add `onEnter` are similarly removed `onLeave`:

```
var Homepage = Barba.BaseView.extend({
  namespace: 'homepage',
  onEnter: function() {},
  onEnterCompleted: function() {
      document.addEventListener("click", someFunc);
  },
  onLeave: function() {},
  onLeaveCompleted: function() {
      document.removeEventListener("click", someFunc);
  }
});

// Don't forget to init the view!
Homepage.init();
```
