### ISSUE TITLE
Links with hashes result in full page reload

### ISSUE THREAD

**Issue by malydok** [luruke/barba.js#113]
I have a working Barba implementation on a client website and one of the pages loads data depending on its hash location, e.g. `/work#websites`. I want to be able to link to these from elsewhere on the website but Barba fails to recognize this link (while `/work` works just fine) and a full reload proceeds.

Apparently in `/src/Pjax/Pjax.js` the `preventCheck` function checks whether there's a hash in the url and prevents the lazy loading on this line `if (href.indexOf('#') > -1)`. This was intended for same page hash changes, which is logical, but fails even hashlinks for other pages.

In `preventCheck` we have these two checks:
```
//Ignore case when a hash is being tacked on the current URL
if (href.indexOf('#') > -1)
    return false;

//In case you're trying to load the same page
if (Utils.cleanLink(href) == Utils.cleanLink(location.href))
    return false;
```
which ultimately check for the same thing? If only the hash changes then the same page check is enough to establish that, no need for the first one. Which solves my case.

Thanks for your work on the plugin by the way, it's pretty sweet :-)

**Comment by luruke** [comment]
Hello @malydok,
I close this issue since there is already https://github.com/luruke/barba.js/issues/53

This will be hopefully fixed in the v2.
