### ISSUE TITLE
Browser loads new page if a link contains an img tag on ie11 & edge

### ISSUE THREAD

**Issue by mlizotteblanko** [luruke/barba.js#114]
Browser loads new page if a link contains an img tag on ie11 & edge.
The img element is use prior the link and the preventCheck test always fail at the "same domain check".

I use this work around in onLinkClick function:
...
while (el && !(this.getHref(el) && el.tagName!='IMG')) {
   el = el.parentNode;
}
...

**Comment by luruke** [comment]
Thank you @mlizotteblanko , I will have a look to this!

**Comment by blimpmason** [comment]
@luruke I'm having a similar issue with IE11 at the moment — links that contain an img tag force a full page load. Was Melros's fix incorporated or is this to be addressed in v2?
