### ISSUE TITLE
Missing declared property to BaseView

### ISSUE THREAD

**Issue by Djules** [luruke/barba.js#115]
Well, this is not an issue. I just found out there is a ```container``` property to [BaseView](https://github.com/luruke/barba.js/blob/master/src/View/BaseView.js) object, but it's not declared or documented.

**Comment by luruke** [comment]
Hey @Djules ,
yes, I added it but actually I forgot to document it (shame on me!)

I found that it's super useful to have access to the associated container.

It's even more useful when you have to create transitions between pages that share the same template / same View.

Thanks for the issue, I will try to update the doc as soon as possible (along with the v2..)

**Comment by Djules** [comment]
Yeah, just saw that, when did you add it? I was using some internal code to retrieve the associated container until I found that.
It was necessary in my own opinion. 👍
