### ISSUE TITLE
Where to place jquery functions

### ISSUE THREAD

**Issue by Mulegoat** [luruke/barba.js#118]
Hi there,

I'm just getting started with this library and am trying to get it working with a site that is in early development at [http://staging.villadeste-marlow.com](url). It's a Wordpress site and I'm using the Sage starter theme from roots.io. I've setup a basic page transition using the example in the docs, the issue is that other javascript or jquery functions are not being fired.

For example, at [http://staging.villadeste-marlow.com/our-menus](url) (accessed via the top nav menu - only 'Home' and 'Menus' links are active at the moment) contains a simple content slider (function menuSlider) which requires the adding of class 'is_active' to the first panel on doccument load but doesn't seem to work where I've placed it:

```javascript
(function($) { 

  /**
  * Use this variable to set up the common and page specific functions. If you
  * rename this variable, you will also need to rename the namespace below.
  */


  var Sage = {
    // All pages
    'common': {
      init: function() {
        // JavaScript to be fired on all pages

        (function menuSlider() { 

          $('.c-menu_outer').each(function() {
            var $slider = $(this);

            $slider.find('.panel:eq(0)').addClass('_active');
            $slider.find('.slide-link:eq(0)').addClass('active');

            var $activeSlide = $slider.find('.panel._active');
          
            var tl = new TimelineMax();
            $('.slide-link').on('click', function() {
              var $copy = $('.c-menu_container'); 
              var $img = $('.c-menu_bg-container'); 
              var $this = $(this);
              var offset_left = $this.offset();
              var initTabNum = $this.data('slide');
              var $article= $('.panel');
              var $show = $('._active'); 

              function step_1() {
                $article.removeClass('_active');
              }
              
              function step_2() {
                $('.num_' + initTabNum).addClass('_active');
              } 
                
              if(!tl.isActive()){
                tl.to($copy, 0.4, {
                  opacity:0, 
                  ease: Power2.easeInOut, 
                  onComplete: step_1
                }).to($img, 0.4, {
                  opacity:0, 
                  ease: Power2.easeInOut, 
                  onComplete: step_1
                }).fromTo($('.num_' + initTabNum), 0.1, 
                { 
                  onStart: step_2, 
                  opacity:0
                }, {
                  opacity:1,
                  ease: Power2.easeInOut, 
                  immediateRender:false
                }).to($copy, 0.4, {
                  opacity:1, 
                  ease: Power2.easeInOut
                }).to($img, 0.4, {
                  opacity:1, 
                  ease: Power2.easeInOut
                });  
              console.log('slide changed !');
              $('.slide-link').removeClass('active');
              var $activeLink = $('.slide-link[data-slide="' + $('.panel._active').data('slide') + '"]');
              $this.addClass('active');


              } 
            });


          });

        })();          


        Barba.Pjax.start();

        var FadeTransition = Barba.BaseTransition.extend({
          start: function() {
            /**
             * This function is automatically called as soon the Transition starts
             * this.newContainerLoading is a Promise for the loading of the new container
             * (Barba.js also comes with an handy Promise polyfill!)
             */

            // As soon the loading is finished and the old page is faded out, let's fade the new page
            Promise
              .all([this.newContainerLoading, this.fadeOut()])
              .then(this.fadeIn.bind(this));
          },

          fadeOut: function() {
            /**
             * this.oldContainer is the HTMLElement of the old Container
             */

            return $(this.oldContainer).animate({ opacity: 0 }).promise();
          },

          fadeIn: function() {
            // *
            //  * this.newContainer is the HTMLElement of the new Container
            //  * At this stage newContainer is on the DOM (inside our #barba-container and with visibility: hidden)
            //  * Please note, newContainer is available just after newContainerLoading is resolved!
             

            var _this = this;
            var $el = $(this.newContainer);

            $(this.oldContainer).hide();

            $el.css({
              visibility : 'visible',
              opacity : 0
            });

            $el.animate({ opacity: 1 }, 400, function() {
              /**
               * Do not forget to call .done() as soon your transition is finished!
               * .done() will automatically remove from the DOM the old Container
               */
              _this.done();
            });
          }
        });

        /**
        * Next step, you have to tell Barba to use the new Transition
        */

        Barba.Pjax.getTransition = function() {
        /**
        * Here you can use your own logic!
        * For example you can use different Transition based on the current page or link...
        */

          return FadeTransition;
        };

        (function initSelect() { 

          $('.gfield_select').select2({

            minimumResultsForSearch: Infinity

          });      

        })();  


      },
      finalize: function() { 
        // JavaScript to be fired on all pages, after page specific JS is fired

      }
    },
    // Home page
    'home': {
      init: function() {
        // JavaScript to be fired on the home page

      },
      finalize: function() {
        // JavaScript to be fired on the home page, after the init JS


  
      }
    },
    // About us page, note the change from about-us to about_us.
    'about_us': {
      init: function() {
        // JavaScript to be fired on the about us page
      }
    }
  };

  /**
  * The routing fires all common scripts, followed by the page specific scripts.
  * Add additional events for more control over timing e.g. a finalize event
  */

  var UTIL = {
    fire: function(func, funcname, args) {
      var fire;
      var namespace = Sage;
      funcname = (funcname === undefined) ? 'init' : funcname;
      fire = func !== '';
      fire = fire && namespace[func];
      fire = fire && typeof namespace[func][funcname] === 'function';

      if (fire) {
        namespace[func][funcname](args);
      }
    },
    loadEvents: function() {
      // Fire common init JS
      UTIL.fire('common');

      // Fire page-specific init JS, and then finalize JS
      $.each(document.body.className.replace(/-/g, '_').split(/\s+/), function(i, classnm) {
        UTIL.fire(classnm);
        UTIL.fire(classnm, 'finalize');
      });

      // Fire common finalize JS
      UTIL.fire('common', 'finalize');
    }
  };

  // Load Events
  $(document).ready(UTIL.loadEvents);

})(jQuery); // Fully reference jQuery after this point.
```

Unfortunately it doesn't seem to work. Where should I be placing this and any additional scripts?

Many thanks in advance! And apologies, I can't seem to get github to display my code properly, hopefully you get the gist :)

**Comment by luruke** [comment]
Hello.

I don't know Sage, but from the code I can see has a system to split the code based on the page.

Barba.js has this kind of functionality built-in with the [Views](http://barbajs.org/views.html).

So, I'd say to use barba.js view or [Events](http://barbajs.org/events.html).

**Comment by Mulegoat** [comment]
Ciao Luigi! 

Yes, Sage does have JS DOM routing but I'm setting all js to fire on all pages but I will give Views a try. Does the data namespace need to be attached to the barba-container element or can it be nested inside it?

Many thanks

Marco

**Comment by mverissimo** [comment]
Hi,
I have the same problem, elements with events outside **barba-wrapper** are fired but don't change element state on a page, even calling the function in the view.

`const APP = window.APP || {};
/**
	* menu
	*
	* @description Toggle navigation
	*/
APP.navigation = () => {
	// header
	const header = document.querySelector('header');

	// hamburguer
	const buttonMenu = document.getElementById('menu');

	// List items menu
	const navigation = document.getElementById('navigation');

	buttonMenu.addEventListener('click', function animate() {
		this.classList.toggle('is-active');
		navigation.classList.toggle('is-active');
	});
};

// Pages
APP.homePage = () => {
	APP.navigation();
};

APP.aboutPage = () => {
	APP.navigation();
};

APP.barba = () => {
	Barba.Dispatcher.on('newPageReady', () => {});

	// Transition animate
	const FadeTransition = Barba.BaseTransition.extend({});

	// Views
	const homePage = Barba.BaseView.extend({
		namespace: 'home'
		,	onEnterCompleted: function onEnterCompleted() {
			APP.homePage();
		}
		,
	});
	const aboutPage = Barba.BaseView.extend({
		namespace: 'about'
		,	onEnterCompleted: function onEnterCompleted() {
			APP.aboutPage();
		}
		,
	});

	Barba.Pjax.getTransition = function getTransition() {
		return FadeTransition;
	};

	// Init Views
	homePage.init();
	aboutPage.init();

	Barba.Pjax.start();
	Barba.Prefetch.init();
};

document.addEventListener('DOMContentLoaded', () => {
	APP.barba();
});
`

Many thanks

**Comment by luruke** [comment]
Hi @Mulegoat, the `namesapace` needs to be attached to the `barba-container`.
You can look at the [demos](http://barbajs.org/demos.html) for more info.

Hello @mverissimo, what is your problem exactly?

**Comment by mverissimo** [comment]
Hi @luruke, I create a simple example: https://github.com/mverissimo/Barba-example

My doubt is when creating an element outside barba-wrapper and try call event on click after transition for other pages, the same not working. But when create inside barba-wrapper, works correctly.

Many thanks.

**Comment by luruke** [comment]
Thank you @mverissimo , i'll have a look this evening.

**Comment by luruke** [comment]
Hello @mverissimo , I've tried your demo and everything works expected on my side.

1. /insidewrapper/ the menu is outside the barba-container, so the navigation menu DOM is never swapped/touched by barba. So it's up to you to close the menu at page change (you can listen barba.js events). Pay attention, you are calling `APP.navigation` multiple times here, so you have multiple event listener on the menu button.


2. /outsidewrapper/ the navigation is inside the barba-container, so, the whole navigation menu is swapped from the transition.

**Comment by mverissimo** [comment]
Hi @luruke , I solved my problem.
I was calling `APP.navigation` on the wrong scope.

 Many thanks for your help!
