### ISSUE TITLE
Page is reloading when "clicking/changing" page faster.

### ISSUE THREAD

**Issue by ngteric** [luruke/barba.js#119]
Hello,

I'am using barba.js on a project, but i have problem with my navigation. When i change page normally when animation is finished it works perfectly, but when i change a page faster than usually (happens when i missed click) the page reloading. Is there a way to fix that ?

Thank you !

**Comment by luruke** [comment]
It's a desidered "feature".
https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L303

Basically if a transition is in progress, it force the redirect.
