### ISSUE TITLE
Execute Three.js onEnterCompleted

### ISSUE THREAD

**Issue by mineraux** [luruke/barba.js#120]
Hello, I'm learning barba and i would like to also use Three.js.
The problem is that I use `document.getElementById('background').appendChild(renderer.domElement);` to add my three.js code to the DOM. In this case, 'background' is not define when the user is on the home (my three.js scene is on an other page).

I tried this, but doesn't work (i have my js code in the console but doesn't execute in the dom) : 
```
var Audio = Barba.BaseView.extend({
        namespace: 'audio',
        onEnter: function() {
            $("#container").addClass("onEnter");
        },
        onEnterCompleted: function() {
            $("#container").addClass("onEnterCompleted");
            $.getScript( "assets/javascript/sounds_rings.js", function( data, textStatus, jqxhr ) {
                console.log( data ); // Data returned
                console.log( textStatus ); // Success
                console.log( jqxhr.status ); // 200
                console.log( "Load was performed." );
            });
            document.getElementById('background').appendChild(renderer.domElement);
        },
        onLeave: function() {
            $("#container").addClass("onLeave");
        },
        onLeaveCompleted: function() {
            $("#container").addClass("onLeaveCompleted");
        }
    });
Audio.init();
```

Hope you can help me. Thanks

**Comment by mineraux** [comment]
I forgot to say it works when i refresh the page with the three.js code but doesn't just with the click on the link to this page.

**Comment by luruke** [comment]
Hello @mineraux,
So, I assume your `#background` is in the "page" with the namespace `audio`, right?

The code should actually works, since at `onEnterCompleted` the new page is already on the DOM.

You might improve your code using `this.container` instead of document, which is the `HTMLElement` of the `.barba-container` with the namespace `audio`.

**Comment by mineraux** [comment]
It's look like barba doesn't trigger the new page.
I wrote it on home.html and audio.html but nothing happen : 
```
var Audio = Barba.BaseView.extend({
        namespace: 'audio',
        onEnter: function() {
            $("#background").addClass("onEnter");
        },
        onEnterCompleted: function() {
          $("#background").addClass("onEnter");
        },
        onLeave: function() {
            $("#background").addClass("onEnter");
        },
        onLeaveCompleted: function() {
            $("#background").addClass("onEnter");
        }
    });
Audio.init();
Barba.Pjax.start();
```

My audio.html looks like that : 
```
<div id="barba-wrapper">
    <div class="barba-container" >
        <div id="container" class="audio experimentation" data-namespace="audio">
          <div class="about">
            <h2>Audio</h2>
            <p class="tags">three.js, canvas, audio, particules</p>
          </div>
            <div id="background">
            </div>
        </div>
    </div>
</div>
```
My home.html : 
```
<div id="barba-wrapper">
    <div class="barba-container">
        <div id="container" class="home" data-namespace="audio">
        <article>
            <div class="description">
                <a href="audio.html">Audio</a>
                <p>Expérimentation audio et particules</p>
            </div>
            <a href="audio.html" class="link-work">
                <img src="assets/images/audio.jpg" alt="" class="logo-work">
                <span class="goToProject white">Voir le projet</span>
            </a>
        </article>
        </div>
    </div>
</div>
```

Do you have any idea why it doesn't work ? Thanks

**Comment by mineraux** [comment]
I found an half of solution : load the three.js file (sounds_rings.js) on the home. The problem is, in the following code, the music loaded with onLeave is still played when I leave audio.html (should be stopped)
Home.html : 
```
<script>
        var Homepage = Barba.BaseView.extend({

                namespace: 'homepage',
                onEnter: function() {
                    console.log("onEnterHome");
                },
                onEnterCompleted: function() {
                  console.log("onEnterCompletedHome");
                  $.getScript( "assets/javascript/sounds_rings.js", function( data, textStatus, jqxhr ) {
                    });
                },
                onLeave: function() {
                  console.log("onLeaveHome");
                  // Chargement du son
                  loadSound("assets/audio/History_of_Empire_cut.ogg");
                  function loadSound(url) {
                      var request = new XMLHttpRequest();
                      request.open('GET', url, true);
                      request.responseType = 'arraybuffer';

                      request.onload = function() {
                          // Décodage des data
                          context.decodeAudioData(request.response, function(buffer) {
                              // Une fois décodé, le son est lancé
                              playSound(buffer);
                          }, onError);
                      };
                      request.send();
                  }

                },
                onLeaveCompleted: function() {
                }
            });
            var Audio = Barba.BaseView.extend({
                    namespace: 'audio',
                    onEnter: function() {
                        console.log("onEnterAudio");
                    },
                    onEnterCompleted: function() {
                      console.log("onEnterCompletedAudio");
                      fireWhenReady();
                      function fireWhenReady() {
                        if (typeof renderer != 'undefined') {
                          console.log("renderer defined");
                          $("#background").append(renderer.domElement);
                        }
                        else {
                          console.log("renderer undefined");
                          setTimeout(fireWhenReady, 100);
                        }
                      }
                    },
                    onLeave: function() {
                      console.log("onLeaveAudio");
                    },
                    onLeaveCompleted: function() {
                    }
                });
        Audio.init();
        Homepage.init();
        Barba.Pjax.start();
        </script>
```

Do you know how to do it ?

**Comment by mineraux** [comment]
Well, I'm close to success but it only work with mistake in my code ...
```
        var Homepage = Barba.BaseView.extend({

                namespace: 'homepage',
                onEnter: function() {
                    console.log("onEnterHome");
                },
                onEnterCompleted: function() {
                  console.log("onEnterCompletedHome");
                  //   $.getScript( "assets/javascript/sounds_rings.js", function( data, textStatus, jqxhr ) {
                  //     });
                },
                onLeave: function() {
                },
                onLeaveCompleted: function() {
                }
            });
            var Audio = Barba.BaseView.extend({
                    namespace: 'audio',
                    onEnter: function() {
                        console.log("onEnterAudio");
                    },
                    onEnterCompleted: function() {
                      console.log("onEnterCompletedAudio");
                        setTimeout(function(){
                          $.getScript("assets/javascript/sounds_rings.js");
                          }, 3000);
                      }) //unexpected )
                });
        Audio.init();
        Homepage.init();
        Barba.Pjax.start();
```

As you can see, before last ")" is unexpected but it doesn't work if I remove it ... 
Do you have any explanations ?

Furthermore, I would like to stop the sounds_rings.js when i leave audio.html, because it plays a music, only necessary in audio.html.

**Comment by mineraux** [comment]
Well, after 6 hours searching, I'm still stuck. 
Data-namespace is on barba-container. `<div class="barba-container" data-namespace="audio">`
I didn't understand what do you mean with this.container. 
`this.$(".barba-container").getElementById('background').appendChild(renderer.domElement); `?

It's very strange because I have the data of sounds_rings.js in my console (onEnterCompleted in index.html) but it doesn't execute. The same code in audio.html works when i refresh audio.html.

I also tried to wait 1sec before launch sounds_rings but same problem.

Script in home.html and audio.html : 
```
<script>
var Homepage = Barba.BaseView.extend({

        namespace: 'homepage',
        onEnter: function() {
            console.log("onEnterHome");
        },
        onEnterCompleted: function() {
          console.log("onEnterCompletedHome");
        }
    })

var Audio = Barba.BaseView.extend({
        namespace: 'audio',
          onEnter: function() {
              console.log("onEnterAudio");
          },
          onEnterCompleted: function() {
            console.log("onEnterCompletedAudio");
            setTimeout(function(){
              console.log("test");
              $.getScript("assets/javascript/sounds_rings.js", function(data){
                console.log( data ); // Data returned
                console.log("sounds_rings Loaded");
              })
            }, 1000);
          }
        })
Homepage.init();
Audio.init();
Barba.Pjax.start();
</script>
```

**Comment by luruke** [comment]
@mineraux If the `console.log` are called, what is your problem?
The sound that is not played?

**Comment by mineraux** [comment]
It doesn't. As I said before, I have data in the console bug it's not executed when I go from home.html to audio.html but it works when I refresh audio.html (same code in the namespace 'audio' in home.html and audio.html). 
For exemple, when I resize the page (supported by the script), i have an error. 

> Uncaught TypeError: Cannot set property 'aspect' of undefined
>     at handleResize (<anonymous>:335:19)

**Comment by luruke** [comment]
@mineraux Can you provide a full demo link / code? That would be helpful.

**Comment by mineraux** [comment]
[mineraux_github.zip](https://github.com/luruke/barba.js/files/772624/mineraux_github.zip)

Here is my code (I didn't link all my files, just one for the exemple is enough), but looks like you need a local server (or the links won't work).
So, as you will see, in index.html when you click on the title "Audio" or the picture related with, the page will change but the three.js script doesn't work. If you stay on audio.html and refresh, it will works (an other problem after is how to stop the music when the page is leaved but we'll se that later).

I hope you will find what is the problem. 
Thanks for your help.

**Comment by luruke** [comment]
Hi @mineraux .
The problem is in your code.

You're loading this `sounds_rings.js` via jQuery.

In this file, everything is initialised with `window.onload = init;`, which of course will never been called if the DOM ha already loaded.

Apart from this, your approach is quite wrong, how you will "destroy" the three.js instance (audio, request animation frame, window resize...) when leaving the page?

My solution is to create a more structured "modules" that have independent init and destroy functions that can be invoked independently, and not using `window.onload` "events".
