### ISSUE TITLE
Instance of the class still kept in memory

### ISSUE THREAD

**Issue by johnfordman** [luruke/barba.js#121]
Hey luruke, thank you for you handsome library ! I’m definitely new with ES2015 and 
I have one question , i used the view to handle the transition between the page.
when i’m doing a new instance of one class « onEnterCompleted », the instance of the class still kept in memory, what is the best way to handle this problem ? 

Best regards,
thank you in advance

**Comment by luruke** [comment]
Hello @johnfordman ,
You have four hooks inside the view:

```
  onEnter: function() {
      // The new Container is ready and attached to the DOM.
  },
  onEnterCompleted: function() {
      // The Transition has just finished.
  },
  onLeave: function() {
      // A new Transition toward a new page has just started.
  },
  onLeaveCompleted: function() {
      // The Container has just been removed from the DOM.
  }
```

The idea is that you init your code inside `onEnter/onEnterCompleted`, then 'clean' your view inside `onLeave/onLeaveCompleted`.

So when leaving you should destroy your classes, free memory, remove events listeners and etc.
