### ISSUE TITLE
CF7 Wordpess reload

### ISSUE THREAD

**Issue by biazo** [luruke/barba.js#122]
Hi there, and thank you for developing this framework!
I have an issue with Wordpress CF7 forms...if i load the page for the first time form works correctly, but if i change page and try to send a form it doesn't work in AJAX and it reloads page changing url to urlpath/#form_id.
Can you help me solving this?
Thanks a lot!

**Comment by luruke** [comment]
Hello @biazo ,
I had the same problem time ago,
you have to dynamically init the CF7 form.

I used this code in my view:
```javascript
    const loader = $(this.container).find('.ajax-loader');
    if (!loader.length) {
      $('div.wpcf7 > form').each(function() {
        $(this).wpcf7InitForm();
      });
    }
```

It basically check if there is acf7 in the page(via .ajax-loader), then init the private function `wpcf7InitForm` on each form.

Hope it helps

**Comment by Mulegoat** [comment]
Hi Luigi,

Any chance you've come across a similar solution for Gravity Forms?

**Comment by biazo** [comment]
@luruke thanks a lot, you're great!

**Comment by luruke** [comment]
@Mulegoat never used,
But reading this https://www.stevenhenty.com/load-gravity-forms-via-ajax/ it seems that it should be enough calling `gformInitDatepicker()`

**Comment by hartey11** [comment]
Hi, I've tried gformInitDatepicker() but it doesn't seem to work. Has anyone managed to get Gravity forms working? If so, could you provide a bit more detail on how?

**Comment by Mulegoat** [comment]
Yes. I used it with views and called it on each one with a form within onEnterCompleted e.g.

`
        var Homepage = Barba.BaseView.extend({
          namespace: 'page-front-page.php',
          onEnter: function() {
            // The new Container is ready and attached to the DOM.
            loadSite();
            scrollReveal();
            openCloseMenu();
            openCloseForm();
          },
          onEnterCompleted: function() {
            // The Transition has just finished.
            gformInitDatepicker();  
            initSelect();
            initRoyalSlider();
          },
          onLeave: function() {
            // A new Transition toward a new page has just started.
          },
          onLeaveCompleted: function() {
            // The Container has just been removed from the DOM.
         
          }
        });
`

Hope that helps

**Comment by hartey11** [comment]
Thanks! But no i dont think this will work. I'm not using the datePicker so that function isn't present on the window object. If i load the form in using an admin-ajax.php request it works (but makes the page very slow to load) but for some reason the javascript inside of the barba container doesn't trigger when its insert.

Heres a link to the site http://preto.staging.wpengine.com/

If you scroll down to the Request a table on load it works (click next without selecting anything and the borders should turn red). If you click The Experience at the top and navigate to that page bia barba you'll see the same Request a table form near the bottom, you see the default selects are now present and if you click next nothing happens...

**Comment by hartey11** [comment]
Think i found a fix! if I add the below to the end of the barba page transition the gravity forms work.

`eval($('.site-main').find('script').text());`

**Comment by bramchi** [comment]
@hartey11 What a genius hack :-D. And proof Gravity Forms' API is a mess :-(

**Comment by mikemedoro** [comment]
@luruke For the latest version of CF7(5.0.1), I had to adjust the function:

`
$( 'div.wpcf7 > form' ).each( function() {
	var $form = $( this );
	wpcf7.initForm( $form );
	if ( wpcf7.cached ) {
		wpcf7.refill( $form );
	}
});
`

This solves the issue of the form not working, but now if I do a hard refresh on the page, the form submits twice. Have you run into this issue at all or know of a way to solve? Thanks

**Comment by krishna-wac** [comment]
Hi,

I also have this same issue but I had some changes from the above code like this.
I have create a function Cf7Init()

function Cf7Init(){
    var loader = $(this.container).find('.ajax-loader');
    if (!loader.length) {      
		$( 'div.wpcf7 > form' ).each( function() {
			var $form = $( this );
			wpcf7.initForm( $form );
			if ( wpcf7.cached ) {
				wpcf7.refill( $form );
			}
		} );
    } 
}

And call this function inside this:

if ($('.barba-container').attr('data-namespace') == 'contact') {
  Cf7Init();
}

It works great...! 🙂

**Comment by imstanleyyeo** [comment]
Thanks for the awesome library! 

I am also encountering this issue but am not using views. Just initing Cf7Init() on newPageReady if there's a specific class on page. However, I got this error in the console:

`Uncaught (in promise) TypeError: Cannot read property 'container' of undefined`

Seems that it couldn't understand "container"  var loader = $(this.container).find('.ajax-loader');

Any help appreciated! Sorry for my bad english.

**Comment by imstanleyyeo** [comment]
I've read from this [thread](https://github.com/barbajs/barba/issues/25) that possible reasons from @luruke that a loaded page might not contain .barba-container with wordpress. I'm using barba on every page with the 2 closing div tag included in footer.php. So not sure what could be wrong. 

Hope someone can point me in the right direction.

**Comment by imstanleyyeo** [comment]
@krishna-wac I've used your Cf7Init() function but I got this error in the console. 

`Uncaught (in promise) TypeError: Cannot read property 'container' of undefined`

Did you encounter this too? How do you resolve this?

Thanks

**Comment by samuelgoddard** [comment]
Has anyone managed to get this working with V2? All of the threads i've found on the topic all have answers for V1 but nothing for V2 :( any help appreciated

**Comment by rgldev** [comment]
@samuelgoddard I have used the code from @krishna-wac and adapted it, using it inside beforeEnter function.

I did it with the following versions and it worked for me:
barba.js v2.9.7
contact form 7 v5.3

The code is the following:

```javascript
beforeEnter({ next }) {
  var cf_selector = 'div.wpcf7 > form';
  var cf_forms = $(next.container).find(cf_selector);
  if (cf_forms.length>0) {
      $(cf_selector).each(function() {
          var $form = $(this);
          wpcf7.initForm( $form );
          if ( wpcf7.cached ) {
              wpcf7.refill( $form );
          }
      });
  }
},
```

**Comment by francescocortese** [comment]
I tried the code, but doesn't load the page when I go on the contact form page.
I tried also:
`$( 'div.wpcf7 > form' ).each( function() { var $form = $( this ); wpcf7.initForm( $form ); if ( wpcf7.cached ) { wpcf7.refill( $form ); } });
`
But I get this from console:
`wpcf7.initForm is not a function`
My CF work only one time when I load the page for the first time.
Any help?

Thanks.

**Comment by fintinc** [comment]
Hi
The newest version of wpcf7 needs some code changes:

`    beforeEnter: function({ next }) {

      var cf_selector = 'div.wpcf7 > form';
      var cf_forms = $(next.container).find(cf_selector);
      if (cf_forms.length>0) {
         $(cf_selector).each(function() {
          var $form = $(this);
          wpcf7.init( $form[0] ); 
        });
      } 
     
    },`

**Comment by francescocortese** [comment]
Thanks @fintinc this solved my problem.

**Comment by martinkariuki7** [comment]
Thanks fintic, works for me as well :)

**Comment by gerasart** [comment]
where modal is $(".yourModal").find('form);   

 fixModalJs(modal) {
        setTimeout(() => {
            if (modal.length > 0) {
                wpcf7.init(modal[0]);
            }
        }, 0);
    },

**Comment by cburrows85** [comment]
> Hi The newest version of wpcf7 needs some code changes:
> 
> ```
> beforeEnter: function({ next }) {
>       var cf_selector = 'div.wpcf7 > form';
>       var cf_forms = $(next.container).find(cf_selector);
>       if (cf_forms.length>0) {
>          $(cf_selector).each(function() {
>           var $form = $(this);
>           wpcf7.init( $form[0] ); 
>         });
>       }   
>     },
> ```

This works beautifully for my project. Thanks so much! 👍🏻
