### ISSUE TITLE
New site using barba.js

### ISSUE THREAD

**Issue by cedric-dagherir** [luruke/barba.js#124]
Hi luruke,

Thanks for your work ! I'll recommand it to my partners.

Can you add this new website using barba.js with ajax + pace.js to your examples page ? https://www.plastiques.eu/

BR.

**Comment by luruke** [comment]
Hello @cedric-dagherir ,
thank you for this.

I'd like to add new websites with some transition a bit different of the classic fadein/fadeout, hope you understand.

Cheers
