### ISSUE TITLE
Barba Views and Promise - delay Transition till page content loaded?

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [luruke/barba.js#125]
I have a custom Barba View for certain pages, which loads a google map in the `onEnter` function. This works great, but Im also using a Fade Transition and the Transition is starting before the google map has loaded, though I would prefer it to wait till the map is loaded.

I assume this would be achieved in the FadeTransitions `start` function using the promises, but Im not sure how to go about inserting a new promise. Im guessing I would add it here 
```
start: function() {
        Promise
        .all([this.newContainerLoading, this.fadeOut()])
        .then(this.fadeIn.bind(this));
    },
```
Most likely as an entry in the `.all([...])` promise array. 

Another thing Im unsure of is, for most pages that dont use the custom Barba View, I dont need to wait for a google map to load, the default behaviour is fine, so if I add a new promise to the array, how will I ensure that normal pages dont get stuck waiting forever since that new promise wont get fulfilled?

**Comment by luruke** [comment]
Hi there @matthewjumpsoffbuildings ,
there are different solution here.

The most simple and logic to me is to leave the `Transition` as it is now, without taking care of the google map.

Then in the `View` with the google maps you can fadein when that is ready.

Would this suits to you?

I'm also planning in the v2 to be able to get the instance context of the new and old View during the Transition, so it will be easier to make into account the loading of gmap during the transition

**Comment by matthewjumpsoffbuildings** [comment]
That is one solution, but its not ideal, since the page transition is not going to be a simple fade when its completed - page transitions will be slides... so Id prefer the transition to wait till the google map is loaded before sliding in the new page.

Having access to the instance of the new and old View would be helpful for sure. Would you expose some kind of Promise from the View that could be accessed in the Transition?

**Comment by spindiesel** [comment]
Hi matthewjumpsoffbuildings,

Is there any chance you could post your google maps code as an example so I could see how you've got it working so far? I'm a bit of a novice with the js side of things...

Before trying to port my code over to barba, I was loading my maps code using window.onload(), however it's now not working obviously as it's being ajaxed in. If you could point out anything I could try instead of window.onload() it would be appreciated. My code so far is below:

```

`var Services = Barba.BaseView.extend({
  namespace: 'services',
  onEnter: function() {
      // The new Container is ready and attached to the DOM.
```

      console.log('services loaded');

            window.onload = function () {

                var latlng = new google.maps.LatLng(-37.81764265020812, 144.9916296);

                var styles = [
                    {
                        featureType: "landscape",
                        stylers: [
                            { color: '#eeddee' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "natural",
                        stylers: [
                            { hue: '#ff0000' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "road",
                        stylers: [
                            { hue: '#5500aa' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "building",
                        elementType: "labels",
                        stylers: [
                            { hue: '#000066' },
                            { saturation: -100 }
                        ]
                    },{
                        featureType: "poi", //points of interest
                        stylers: [
                            { hue: '#0044ff' },
                            { saturation: -100 }
                        ]
                    }
                ];

                
                var isTouchDevice = !('ontouchstart' in document.documentElement);

                var myOptions = {
                    zoom: 14,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    disableDefaultUI: true,
                    zoomControl: true,
                    styles: styles,
                    scrollwheel:  false,
                    draggable: isTouchDevice
                };

                map = new google.maps.Map(document.getElementById('map'), myOptions);

                var marker = new google.maps.Marker({
                    position: latlng,
                    title: "Brow 101"
                });

                marker.setMap(map);

            }
```
  },
  onEnterCompleted: function() {
      // The Transition has just finished.
  },
  onLeave: function() {
      // A new Transition toward a new page has just started.
  },
  onLeaveCompleted: function() {
      // The Container has just been removed from the DOM.
  }
});

// Don't forget to init the view!
Services.init();`
```

**Comment by matthewjumpsoffbuildings** [comment]
Can you edit that comment and put all the code in a github gist or pastebin or something? I dont mind taking a look, but its not really relevant to the topic of this issue, this is about the Barba View/Transition/Promise api

**Comment by karltaidev** [comment]
I am looking for the same thing here. The page slows down when init heavy js code together with the transition animation. And sometime the animation finish before the js code finish init, which has element displacement for example carousel after loading especially for low computing power device and slow network. It would be ideal if the Transition can listen to Promise inside View in someway. Thanks.
