### ISSUE TITLE
Where to put my Jquery functions

### ISSUE THREAD

**Issue by Tannate** [luruke/barba.js#126]
I have Jquery scripts in my website. The most of my js functions are in a file named `main.js`. 

To make my plugins works with Barba.js I use the [Views methods][2].

So I put all my jQuery functions in my `main.js` like this :

```
    var Homepage = Barba.BaseView.extend({
      namespace: 'homepage',
      onEnter: function() {

          // Here's they are my jQuery functions.
      },
    });
    
    Homepage.init();

    Barba.Pjax.start();

```
It works for these jQuery functions. 

The problem is that I have some other jQuery functions in two other pages : `index.php`and `single.php`. I have no more choice to put them in these pages because these Jquery functions contain php code.

So I put the other jQuery functions in my `index.php` and `single.php` like this :

```
    <script type="text/javascript" src="main.js"></script>

          // Here's they are my html code.

    <script type="text/javascript">

     var Homepage = Barba.BaseView.extend({
       namespace: 'homepage',
       onEnter: function() {

           // Here's they are my jQuery functions.
       },
     });
    
     Homepage.init();

    </script>

```

It doesn't works for these jQuery functions which are in my `index.php` and `single.php`. I can't see them in my pages. Like they don't exist.

Why and how to fix it ?

  [2]: http://barbajs.org/views.html

**Comment by luruke** [comment]
Hello @Tannate ,
first of i'd suggest to serve the javascript file as external file without adding them inside your `php` files.

If you need to pass some vars from backend to js, you can just create a global variable es.

```
<script>
window.myvars = {
  test: true;
};
</script>
<script type="text/javascript" src="main.js"></script>
```

so in your js you can read `window.myvars.test`

**Comment by Tannate** [comment]
Thanks for your help luruke.
The only jQuery function that contains php is this one : 

How can I put them in my main.js ?

```

<script type="text/javascript">

    var r = parseInt('<?php the_field('red'); ?>'); 
    var g = parseInt('<?php the_field('green'); ?>'); 
    var b = parseInt('<?php the_field('blue'); ?>');


    $("body").css('background-color', 'rgb(' + r + ',' + g + ',' + b + ')');

        var alpha = Math.min($(this).scrollTop() / 2000, 1);
        var r = Math.round((230-parseInt('<?php the_field('red'); ?>')) * alpha + parseInt('<?php the_field('red'); ?>')); 
        /* red : (fin - début + début) */
        var g = Math.round((230-parseInt('<?php the_field('green'); ?>')) * alpha + parseInt('<?php the_field('green'); ?>')); 
        /* red : (fin - début + début) */
        var b = Math.round((230-parseInt('<?php the_field('blue'); ?>')) * alpha + parseInt('<?php the_field('blue'); ?>')); 

   $(document).scroll(function() {
        /* red : (fin - début + début) */
        $("body").css('background-color', 'rgb(' + r + ',' + g + ',' + b + ')');
        // console.log(r)
    });

</script>
```

**Comment by Tannate** [comment]
Maybe I didn't understand but when I click on a link in my website to go to an other page (like about.php) is like all my jQuery function are duplicated each time I click on a link !  Does I used the Views correctly ?

**Comment by 19h47** [comment]
Hi @Tannate,

Maybe you put your script tag in the barba container, so each time the view is updated the function is attach again and again ?

**Comment by khaiknievel** [comment]
Hey @Tannate,

Maybe what you can do is to attach the values as an element data-attribute. Then reference those values within main script using ```$(element).data()``` . And run the require script if the value exists. This way you can avoid placing script tags within the ```.barba-container```.

Hope this helps. Cheers.
