### ISSUE TITLE
Still able to view cached pages after logging out

### ISSUE THREAD

**Issue by PhillyWebGuy** [luruke/barba.js#127]
I'm using barba with Wordpress. I'm having an issue where I log out of WP, but I can hit the back button and still see pages in cache.

My first thought was to reset Barba.BaseCache.data, but that neither Barba.BaseCache nor Barba.BaseCache.data seem to exist, despite what the documentation says.

Another thought was to set Barba.HistoryManager.history = [] but that doesn't do the trick either.

How can clear cache so I can disallow users from viewing pages through use of back button, after logging out of an application like WordPress?

**Comment by luruke** [comment]
Hello @PhillyWebGuy ,

Usually I disable barba.js navigation when logged as admin (so it doesn't interfere with wp admin bar).

Yes, actually `Barba.BaseCache` is not exposed, the jsdoc annotation is wrong and therefore the doc. (i'll fix it in the v2)

You can access the cache via `Barba.Pjax.Cache`.

**Comment by PhillyWebGuy** [comment]
Ok, I'll set Barba.Pjax.Cache = [] on logout and see what happens...

**Comment by luruke** [comment]
There is a reset method:
`Barba.Pjax.Cache.reset()`

**Comment by PhillyWebGuy** [comment]
Nothing actually appears in that array. And if I do reset() I am still unable to use the back button to navigate to pages. 

![screen shot 2017-03-06 at 1 56 29 pm](https://cloud.githubusercontent.com/assets/449963/23624735/cd72772a-0274-11e7-8007-de6c05448926.png)

**Comment by luruke** [comment]
> I am still unable to use the back button to navigate to pages.

Hello @PhillyWebGuy , isn't that what you wanted?
To not allow people to see pages in the cache after the logged out.

Can you explain a bit better?

**Comment by PhillyWebGuy** [comment]
That was a type. The problem is that I reset() but I am still have to use back button. The data still seems to be cached. Not only that, it doesn't appear to be there in the first place when inspecting, so I can't verify it is gone, aside from the fact that I can still use back button.

**Comment by luruke** [comment]
@PhillyWebGuy the browser will always shows the back button, barba.js can't disallow that.
If you reset the cache, barba.js will just force a new xhr request for a page, that's it.

Hope it makes sense
