### ISSUE TITLE
Follow redirected requests?

### ISSUE THREAD

**Issue by tannerhodges** [luruke/barba.js#129]
I have a simple application that creates a new Project when you click an "Add New Project" link. The link points to `/projects/new` which creates a new Project on the back-end and returns a 302 redirect to the new Project's URL (e.g., `/projects/NMJqpa`).

I'd like to add a transition between these two views using Barba.js but it [forces a page refresh](https://github.com/luruke/barba.js/blob/95a8408082a3ed038defa09460e374f8ad39f6d9/dist/barba.js#L1244-L1245) because of the [302 status code](https://github.com/luruke/barba.js/blob/95a8408082a3ed038defa09460e374f8ad39f6d9/dist/barba.js#L674-L678).

Is there currently a way to follow redirected requests with Barba.js?

If not, could we add something similar to how [jquery-pjax's `X-PJAX-URL` header](https://github.com/defunkt/jquery-pjax/blob/d76e840c0f1c0a98c9dd5065b32e436e810d8d13/jquery.pjax.js#L693-L696) works? Something along these lines:

- Check for a response header in the [`load` method](https://github.com/luruke/barba.js/blob/95a8408082a3ed038defa09460e374f8ad39f6d9/dist/barba.js#L1233-L1241) (e.g., `X-BARBA-URL`).
- Use the value from that response header to [override `newUrl` in `onStateChange`](https://github.com/luruke/barba.js/blob/95a8408082a3ed038defa09460e374f8ad39f6d9/dist/barba.js#L1376).
- If no header is passed, fallback to the original requested URL.

I found a [similar issue in smoothState.js](https://github.com/miguel-perez/smoothState.js/pull/267). They added a configurable [`locationHeader` option](https://github.com/miguel-perez/smoothState.js/blob/a22f5b6b372dc532a159e967e408e4d766fa70a4/src/jquery.smoothState.js#L430-L432) for getting the URL from the response header then passing it to their [`alterStateChange` method](https://github.com/miguel-perez/smoothState.js/blob/a22f5b6b372dc532a159e967e408e4d766fa70a4/src/jquery.smoothState.js#L556-L559).

If this is a feature you'd be willing to add, I can put together a pull request in the coming weeks for review.

Thanks!

**Comment by luruke** [comment]
Hello @tannerhodges ,
thank you for your issue.

Yes, this is something I was aware of.

In the new v2 i'm going to use `fetch` API, which should automatically handle redirections.

**Comment by tannerhodges** [comment]
Awesome, thanks @luruke.

Do you have an idea when v2 will be available, or a recommended workaround in the meantime?

**Comment by luruke** [comment]
At the moment I don't have a solution since I never faced this problem.

You might try to add a `no-barba` class on the link, so barba.js will ignore it.

**Comment by tannerhodges** [comment]
Yeah, that'll do for now. Thanks again. Will definitely keep an eye out for v2.
