### ISSUE TITLE
Question about different transitions

### ISSUE THREAD

**Issue by jesperlandberg** [luruke/barba.js#130]
First of, thanks for an amazing library, by far the best I have used together with Wordpress.

I'm building a site that uses many different transitions based on where u are going and where u came from.

Is something like this the prefered way of checking which transition to use or do you recommend something else?

```
Barba.Pjax.getTransition = function() {

  if(document.querySelector('[data-namespace="home"]')) {

    // if clicked link 1 return toCaseTransition
    // if clicked link 2 return toAboutTransition

  } else if(document.querySelector('[data-namespace="about"]')) {
  
    return aboutTransition
    
  } // and so on
}
```

**Comment by luruke** [comment]
Hello @jesperlandberg 

Have a look here:
https://github.com/luruke/barba.js/issues/19#issuecomment-223874845

Do not hesitate if you have more questions.

**Comment by jesperlandberg** [comment]
@luruke 

Thanks, perfect!
