### ISSUE TITLE
Question about views

### ISSUE THREAD

**Issue by jesperlandberg** [luruke/barba.js#131]
Hi,

I am building a Wordpress site, and was just wondering how to get views to work as intended when going from one page that is using a view, to another using the same view (in this case from a project to another project).

Here is my single page view:

```
  let scroll = null
  const Single = Barba.BaseView.extend({
    namespace: 'single',
    onEnter: function() {
      const section = document.querySelector('[data-vertical]')
      const divs = document.querySelectorAll('[data-scroll-item]')

      scroll = new Custom({
        native: false,
        preload: true,
        section: section,
        direction: 'vertical',
        divs: divs,
        ease: 0.1,
        vs: {
          mouseMultiplier: 0.35,
          touchMultiplier: 3,
          firefoxMultiplier: 30
        }
      })

      scroll.init()
    },
    onLeave: function() {
      scroll.destroy()
    }
  })

  Single.init()
```

And what is happening is that onLeave and onEnter doesnt seem to execute as intended in this scenario.

Any tips?

**Comment by luruke** [comment]
Hello @jesperlandberg ,
try using `this.container` as root selector instead of `document`.

in fact if you are navigating from two pages of the same template at `onEnter` you have both pages on your DOM (so, two `[data-vertical]`)

**Comment by jesperlandberg** [comment]
@luruke dang, feels like something I could have thought of myself. Worked a charm tho=) thanks for the quick reply!
