### ISSUE TITLE
Clicking a link to the current URL triggers hard reload

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [luruke/barba.js#132]
If im on a page and I click an <a> that links to the URL of that page, instead of doing nothing Barba hard reloads the page. Is this the correct behaviour, and if so is there a correct way to override this?

**Comment by luruke** [comment]
Hello @matthewjumpsoffbuildings 
Yes it's the intended behaviour.

You can have a look here: https://github.com/luruke/barba.js/issues/34
