### ISSUE TITLE
Back button scroll transition issues

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [luruke/barba.js#133]
When using the back button, a lot of browsers seem to store the scroll position you were last on in the previous page you are going back to. So when you go back to that page, it jumps you down to that remembered position immediately

This messes with transitions such as page slide ins/outs using transforms. Is there a way barba can suppress this behaviour somehow in its PJAX handling?

edit: `history.scrollRestoration` js property and this polyfill - https://github.com/bfred-it/scroll-restoration-polyfill does the trick.

**Comment by samburgers** [comment]
sup matty (and long time!)

pretty sure i fixed that issue in an old project like this:

```
 Barba.Dispatcher.on('newPageReady', function() {
    window.scrollTo(0, 0);   
  });
```

**Comment by matthewjumpsoffbuildings** [comment]
yo sam cheers man, i actually found that the `history.scrollRestoration` property and this polyfill - https://github.com/bfred-it/scroll-restoration-polyfill does the trick. 

the issue was im doing a slide in/out css transition (left/right) and if the old page and new page have different heights and the previous pages scroll position is out of range you get some weird stuff - the thing is i cant just set scrollY to 0, cause i want to keep the old page in the same position during the transition. but ye the history.scrollRestoration problem sorts that :)

**Comment by psntr** [comment]
Hey Matthew,

I'm exactly experimenting this issue, but I can't get my head around your solution. I installed the Polyfill (scroll-restoration), but did you have to modify the original code of barba? 

I hope you can guide me to your solution.

Best regards

**Comment by spicysanta** [comment]
> Hey @matthewjumpsoffbuildings ,
> 
> I'm exactly experimenting this issue, but I can't get my head around your solution. I installed the Polyfill (scroll-restoration), but did you have to modify the original code of barba?
> 
> I hope you can guide me to your solution.
> 
> Best regards

Did you ever solve this issue?

**Comment by psntr** [comment]
@spicysanta sadly I was never able to find a proper solution with barba and scroll-restoration. I would still be happy to here if anyone has find a solution so far.

**Comment by psntr** [comment]
I will try that, thank you @spicysanta

**Comment by spicysanta** [comment]
Let me know! You would still need to add this line of code to your page transition for Barba.

`      document.body.scrollTop = 0;
`

**Comment by psntr** [comment]
It works!!! thank you!
