### ISSUE TITLE
preloading new pages

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [luruke/barba.js#134]
what is the correct way to go about attaching load events/preloaders with new barba pages?

not just on the html that is being ajaxed in, but also on the images/assets that are inside that new page?

**Comment by sndrgb** [comment]
hi @matthewjumpsoffbuildings, I think you're talking about attach events/starting plugins or custom scripts for the active view, right? In that case Barba.js provide you an util for handle this kind of things and it's called BaseView. 
Baseview is automatically called after transition completed.
For more infos watch this:
http://barbajs.org/views.html

**Comment by matthewjumpsoffbuildings** [comment]
this doesnt seem right - i want to attach load events to elements in the new page _before_ that page is added to the DOM, and the views only have functions that handle _after_ the new page is inserted into the DOM if I understand it correctly

**Comment by Djules** [comment]
Easiest way is to override the load function of Pjax to suit your needs.

```js
Barba.Pjax.load = function(url) {
  var deferred = Utils.deferred();
  var _this = this;
  var xhr;

  xhr = this.Cache.get(url);

  if (!xhr) {
    xhr = Utils.xhr(url);
    this.Cache.set(url, xhr);
  }

  xhr.then(
    function(data) {
      var container = _this.Dom.parseResponse(data);

      // here you can trigger a custom event if you will
      Barba.Dispatcher.trigger('newPageLoaded', container);

      _this.Dom.putContainer(container);

      if (!_this.cacheEnabled)
        _this.Cache.reset();

      deferred.resolve(container);
    },
    function() {
      //Something went wrong (timeout, 404, 505...)
      _this.forceGoTo(url);

      deferred.reject();
    }
  );

  return deferred.promise;
};
```

Then you can listen for the new custom event:

```js
Barba.Dispatcher.on('newPageLoaded', function(HTMLElementContainer) {
  // do what you want with the container, right before it's appended to the DOM
};
```

**Comment by matthewjumpsoffbuildings** [comment]
:/ do i have to override the whole load function like this?

@luruke how hard would it be to add a new event to the Views class, as well as the existing onEnter and onEnterCompleted, something like `onData: function( data )`, which is called when the new ajax page data is loaded and parsed, but the new html hasnt been inserted into the DOM yet

**Comment by luruke** [comment]
Hello @matthewjumpsoffbuildings;

Can't you just write a custom transition that, before finishing, it makes sure that all the images/stuffyouwant are loaded before finishing the transition/showing the page?

**Comment by matthewjumpsoffbuildings** [comment]
One issue Ive had with preloading in the past is if certain imgs/resources are cached, and you attach the load listeners to the HTML _after_ it has been added to the DOM, then some of the load events wont fire cause the element is already loaded from the cache before the load listener is attached.

To avoid this ever being an issue Id prefer a way to attach the listeners to the elements before they have been added to the DOM

**Comment by tj** [comment]
Isn't this a new capability with service workers? Utilizing the browser's streaming html parsing

**Comment by matthewjumpsoffbuildings** [comment]
is there any news on this? all i really need is some kind of barba dispatcher event i can listen to that is called when the new page html is ajaxed in, but before it has been inserted into the dom

**Comment by frankmarineau** [comment]
I'd love to see this happen too. My use case is loading splitted js bundles for the specific pages being loaded. Right now I have to wait for the page to be inserted into the dom to start loading the js, instead of starting as soon as the user hovers over a link.

**Comment by matthewjumpsoffbuildings** [comment]
ok well i was trying to get around this by setting up PreloadJS to run on all the `<img>` elements in the new page, but the problem is, because they are already inserted into the DOM by Barba, the browser already starts loading them, and this takes precedence over the PreloadJS queue.

I _need_ to be able to modify the HTML of the new page _before_ it is inserted into the DOM. Theres no other way around it

**Comment by bl4ckdu5t** [comment]
Does this address things like loading a tweet properly in a pjaxed page? For things I need to init in code I do that onTransitionEnd of the dispatcher but Twitter is embedded and I've had the same with a few other scripts like that.

**Comment by matthewjumpsoffbuildings** [comment]
I made a pull request adding a new Dispatcher.trigger as recommended by @Djules here: https://github.com/luruke/barba.js/issues/134#issuecomment-289442951

I tested it out and it works perfectly. Thats all we need - a new Dispatcher event we can listen to when the HTML is ready, but just before its attached to the DOM

https://github.com/luruke/barba.js/pull/147
