### ISSUE TITLE
Disable prefetch only for certain links ?

### ISSUE THREAD

**Issue by daslicht** [luruke/barba.js#136]
Hi, 
is it possible to disable prefetch for only certain links and not all please?

Cheers Marc

**Comment by luruke** [comment]
Hello @daslicht ,
not possible at the moment but you can easily modify this function https://github.com/luruke/barba.js/blob/master/src/Pjax/Prefetch.js#L42

You can either modify it at runtime, wrapping it inside your own function or create a build with your modified code.

Cheers

**Comment by daslicht** [comment]
I just ran into another issue, is there a way to disable barba for forms as well ? ```no-barba``` seams not to work when i add it to the button ?
