### ISSUE TITLE
Someone fix the docs (barbajs.org) already!

### ISSUE THREAD

**Issue by waxter013** [luruke/barba.js#138]
The website has been unreadable for me for months. The <nav> and #barba-wrapper nodes have a width of 100%; The nav is overlapping the docs! Just give both of them a fixed width or something. This a desktop only issue. Mobile is golden!

It's such a simple fix (took me about 30 seconds), I'm surprised it's not done already.

**Comment by luruke** [comment]
Hello @waxter013 ,
what is the issue exactly?
Can you post a screenshot?

I have no problem on latest chrome, firefox and safari under osx.

**Comment by waxter013** [comment]
Yup. I still have the issue, but I gave you the wrong info earlier. It's not on the docs page (http://barbajs.org/docs/*.html). It's an issue with the main website (barbajs.org/*.html). The problem only exists on screens with widths between 60rem and about 87rem. My screen resolution is 1366x768, so I just barely make the problem range at about 85rem. Thanks Dell...

Here's a **screenshot**. 

![barbajs  error](https://user-images.githubusercontent.com/7544238/28341255-dbfba5a2-6be0-11e7-9b77-db372f2d830b.PNG)

See the slight overlap. It's more noticeable on some pages than others, but it's still just a minor issue. 

And here's a quick **fix** in CSS: 

```
@media (min-width: 60rem) {
    nav {
        width: 24rem;
    }
    #barba-wrapper {
        width: calc(100% - 24rem);
    }
}
```

Ta da!

**Comment by S1SYPHOS** [comment]
If I may ask:
Why don't you just go for a pull request? Just check out the `gh-pages` branch ..
