### ISSUE TITLE
Reload app.js after transition end?

### ISSUE THREAD

**Issue by duezerouno** [luruke/barba.js#139]
Hi @luruke , I am using [ScrollMe](http://scrollme.nckprsn.com/) for some animations and I am having a bit of an hard time making it work with Barba, it only works if I reload the page - Any idea?

**Comment by panwron** [comment]
You probably have to reinitialize your plugin on specific event and view like so:

`var Homepage = Barba.BaseView.extend({
  namespace: 'homepage',
  onEnter: function() {
      // The new Container is ready and attached to the DOM.
     // Init scrollMe here

  },
  onEnterCompleted: function() {
      // The Transition has just finished.
     // Or Init scrollMe here 
  },
  onLeave: function() {
      // A new Transition toward a new page has just started.
  },
  onLeaveCompleted: function() {
      // The Container has just been removed from the DOM.
  }
});`


Check here: http://barbajs.org/views.html

**Comment by luruke** [comment]
Hello @duezerouno, as @panwron said you need to make sure to use barba.js events.
