### ISSUE TITLE
Use a dom differ instead of a container?

### ISSUE THREAD

**Issue by davidmerfield** [luruke/barba.js#141]
Hi Luigi, thanks for creating an awesome tool. As I was fiddling around with your library, I thought it might be interesting to add a dom differ (like [this](https://github.com/fiduswriter/diffDOM) or [this](https://github.com/skatejs/dom-diff)) to handle transition between pages instead of requiring the ```barba-wrapper``` and ```barba-container``` elements. 

This would be cool because you could just add the library to an existing static site and it would make navigation faster for folks with modern browsers, and degrade gracefully for those that don't.

Had you considered something like this? Am I overlooking something obvious?

**Comment by luruke** [comment]
Hello @davidmerfield , interesting.

Technically I think it's feasible but, it will make barba.js much more complex, and that's just for the convenience of not adding a `barba-wrapper` and `barba-container`.

Also, without having a common "container" between two pages, I think create custom transition would be much harder.

Also, dom diffing comes with a performance cost.

Happy to discuss this further if you have any idea

**Comment by davidmerfield** [comment]
Fair enough, I agree it adds a lot of complexity. It sounds like you've prioritized the inter-page transitions which I totally understand. I think I'm going to experiment and try to make something which uses a differ. Will let you know how it goes!
