### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by incompletude** [luruke/barba.js#143]
Is it possible to add an accessible version number to the website and to the Github page?

Amazing work. Thx.

**Comment by luruke** [comment]
Hello @incompletude , unfortunately the docs on the website is not versioned, it means you can't access the doc to a specific version.

Is that what you mean?
In any case there aren't been any big breaking change that I recall

**Comment by incompletude** [comment]
It is necessary to visit the releases page to know what is the lastest version. I think this information should be more easily accessible on the website and in the github readme.

https://github.com/luruke/barba.js/releases

**Comment by luruke** [comment]
Thank you @incompletude , i'll keep that in mind for next release and updates.
