### ISSUE TITLE
Transition timing issue

### ISSUE THREAD

**Issue by mateomm22** [luruke/barba.js#145]
Im new into barba.js and i'm trying to understand the plugin, i made all the steps into the demo page and for some reason if i click the same link twice, the transition before the DOM changes doesn't play.

This is the code im using to make the transition.

```
var SlideTransition = Barba.BaseTransition.extend({
    start: function() {
      Promise
        .all([this.newContainerLoading, this.slideOut()])
        .then(this.fadeIn.bind(this));
    },
    slideOut: function() {
      return $(this.oldContainer).find('header').addClass('out').promise();
    },
    fadeIn: function() {
      var _this = this;
      var $el = $(this.newContainer);

      $(this.oldContainer).hide();

      $el.css({
        visibility : 'visible',
        opacity : 0
      });
      $el.animate({ opacity: 1 }, 400, function() {
      });

      $el.find('header').addClass('in');
      _this.done();
    }
  });
```

thanks

**Comment by luruke** [comment]
Hello @mateomm22 ,
if a transition is already in progress and you click a link, barba.js force the refresh to that page (https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L303)

Is that your problem?

**Comment by mateomm22** [comment]
Hi @luruke 
Thanks for the answer, but i found out the problem was the caché, i disabled the option 
 with Barba.Pjax.cacheEnabled = false; and it worked perfectly.

**Comment by luruke** [comment]
Ok, i'll close this.
