### ISSUE TITLE
Using back button after visiting 404 

### ISSUE THREAD

**Issue by docherty** [luruke/barba.js#148]
Awesome library - thanks for sharing it. I've set up a site's to work with the back button per the comment at the bottom of #87 . It works great for both forward and back buttons. However, if I visit a page that is a 404 error (it could easily happen if I link to a 3rd party site that subsequently dies), when I hit the browser back button to return to a page that I know works fine, no event seems to be triggered so although the URL is correct, the page content is blank.

I'm sure I must be missing something so if someone has any suggestions where I can start looking that would be great.

Thanks,
James

**Comment by aswinkumar863** [comment]
use `<body onpopstate="location.reload();">` on 404 error page
