### ISSUE TITLE
Transition Promise issues

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [luruke/barba.js#150]
Im having issues with the promises in the `start()` function of my transition

It appears that the `this.newContainerLoading` promise is resolving, but if I attempt to access `this.newContainer` in a function that is called immediately _after_ `this.newContainerLoading` is resolved, it is undefined.

For example, if I use this code:
```
Promise.all([
	this.newContainerLoading,
	this.gsapAnim()
])
.then(Promise.all([
	this.fadeOut.bind(this),
	this.preload.bind(this)
]))
.then(this.fadeIn.bind(this))
```
It doesnt work, because `preload()` expects `this.newContainer` to be defined.

But if I do this:
```
Promise.all([
	this.newContainerLoading,
	this.gsapAnim()
])
.then(this.fadeOut.bind(this))
.then(this.preload.bind(this))
.then(this.fadeIn.bind(this))
```
It _does_ work, because by the time `preload()` gets called, `this.newContainer` is defined.

The issue is, when the `this.newContainerLoading` promise is resolved, it appears that anything in a  `then()` that immediately follows it happens _TOO EARLY_ for `this.newContainer` to be defined.

Therefore Im thinking in your code, wherever you resolve `this.newContainerLoading` you are assigning `this.newContainer` _AFTER_ calling `resolve()`

**Comment by luruke** [comment]
Hello @matthewjumpsoffbuildings ,
`newContainer` is defined before resolving the promise, so it's strange that you have this problem.

https://github.com/luruke/barba.js/blob/9f66f8ebc03394a666fbc865c05dde99c2fc4ebf/src/Transition/BaseTransition.js#L63

I'll investigate on it when I have some time

**Comment by matthewjumpsoffbuildings** [comment]
Hmm thats bizzare. Just to confirm, this example:
```
Promise.all([
	this.newContainerLoading,
	this.gsapAnim()
])
.then(Promise.all([
	this.fadeOut.bind(this),
	this.preload.bind(this)
]))
.then(this.fadeIn.bind(this))
```
doesnt look obviously wrong to you? both `preload()` and `gsapAnim()` return `deferred.promise` using you `Utils.deferred` helper.

**Comment by matthewjumpsoffbuildings** [comment]
Hmm ok ive been debugging a bit and it turns out the 2 functions in the second `Promise.all()` are not even getting called. Im guessing there is an issue with my Promise chain.

And now, when I try this:
```
this.newContainerLoading
.then(this.preload.bind(this))
.then(this.fadeOut.bind(this))
.then(this.fadeIn.bind(this))
```
The `preload()` function _does_ have access to the `this.newContainer` variable... but it wasnt working before :/ 

Sorry for all the posts... Im pretty sure now there is something wrong with how Im using the `then()` and `Promise.all()`

**Comment by matthewjumpsoffbuildings** [comment]
Ok - turns out I _was_ using `Promise.all()` wrong. Sorry about that.

I was passing `this.fadeOut.bind(this)` and `this.preload.bind(this)` to it - but `Promise.all()` doesnt want `bind`s, it wants Promises.

Also, `then()` doesnt want Promises, it wants _functions_

So, doing this works:
```
Promise.all([
	this.newContainerLoading,
	this.gsapAnim()
])
.then(() => Promise.all([
	this.fadeOut(),
	this.preload()
]))
.then(this.fadeIn.bind(this))
```

**Comment by proov** [comment]
Interesting @matthewjumpsoffbuildings, I am doing almost the same thing ,but i don't understand something : What your `preload()` function do ? does it preload `newContainer` images ??

I would like to preload some images whit imagesLoaded, but i can't succeed. My `preloadImages()` promise have a statut of "pending" because i put `deferred.resolve()` in the ImagesLoaded callback.

But i think i am doing wrong, Promise are asynchronous, so maybe i shouldn't use a Promise functon to preload some images. Actually, I want to set up a preloader between pages if there are some images with [data-preload] attributes in the `newContainer`
