### ISSUE TITLE
Some questions about Barba.js

### ISSUE THREAD

**Issue by proov** [luruke/barba.js#156]
Hello !

I'm diving into Barba.js from 2 weeks, I really like it ! It's fast and more reactive than my homemade system with Pjax.js ^^ I read the docs, I read a part of the source code and a lot of GtHub Issues/Questions.

However there are still some things I do not know how to do, or even how to start :D (I'm using it on Wordpress btw)

- I defined a custom transition `pagesTransition` for every pages, it animates title / thumbnail and content with GSAP. But if I want to have a custom transition when i land on the "portfolio" page ? (I want the`pagesTransition` effects when i leave from any pages, and custom ones when i  come to portfolio page). I Used your `valid()` logic from #19 but if i'm doing this, i have to copy the effects from `pagesTransition` to `ToPortfolio` transition ? I must doing something wrong :D This leads to my second question ^^

- Can we share components between differents transition ? If i want to create a new custom transition to display a masonry, and i want to preload it. Can we have a component or method `preloadImages` shared between transitions ?

- Finally, How do you manage the first full load from the pjax loads between pages ? (to init scrits). I mean, if i want the sames effects i set up in my transitions when i land on the site ?

That's all :D Thanks for reading ^^
And thanks for Barba.js 👍

**Comment by luruke** [comment]
Hello!

Transition are just basic javascript objects, you can do whatever you want inside, as long you call `this.done` when finished.
It's up to you if you want to reuse parts between transitions, add preloading and etc.

When you init pjax (`Barba.Pjax.start()`) it will also fire `initStateChange` and `newPageReady`. That means that if you add your listener/views before starting pjax, those events will fire.

About the example around "masonry", yes, you could have it as component, not specifically tied to a view/transition. All you need is to use `newPageReady` event, take the third argument, find your masonry node root and init it.

Hope it clear some of your question,
sorry for not being more detailed but i'm in hurry right now :)

**Comment by proov** [comment]
No problems :) thanks to take the time to answer :D

Okay, Interesting, In your demos, you never call `Barba.Pjax.start()` I was wondering what it was for ^^.
So if i put the pages GSAP effects in `initStateChange` or `newPageReady`, they will be rendered at the first load ? But after each page changed as well ? What do you recommend then ?

**Comment by RyoIkarashi** [comment]
@luruke First off thanks for the great project :)
I have the same problem as @proov does above and want to know the best practice on this.
As @proov said above, `initStateChange` and `newPageReady` will be called every time when every page changes, which doesn't fit a function that fires only once when first page is ready/changes. I want a function like `initPageReady` that will be fired once when the first page is ready.

**Comment by mikdlawregiets** [comment]
@proov @RyoIkarashi 
Maybe a bit late, but if you define a BaseView you can call the methods eg. `Foo.onEnter()` on initial load.

**Comment by proov** [comment]
It's never too late @mikdlawregiets ! many thanks for the answer, i'll give it a try 🙌
