### ISSUE TITLE
barba-container div is taking place after script

### ISSUE THREAD

**Issue by mikhy888** [luruke/barba.js#157]
Hi,

Barba.js is really awesome pluggin.. Since am new to it...
One thing I noticed, after clicking the link, new page which contains new html contents taking place after every scripts..
ie, just before closing body tag.....
Anyone please suggest me a solution

**Comment by julbarissow** [comment]
It happens when you put the barba-wrapper into the body. Try to put the #barba-wrapper before your scripts (before body) load.

**Comment by mbsimonovic** [comment]
what are you two talking about? 

@mikhy888: "_new html contents taking place after every script_" - the new page has content before or after <script> tags? 

@julbarissow: the wrapper has to be inside the body tag, right? so what are you suggesting then, to have #barba-wrapper before other <script> tags? if that's the case, i've just tried it and doesnt seem to work.

**Comment by julbarissow** [comment]
My structure looks like this:
`<body>
<div id="barba-wrapper">
<div class="page-type-xx barba-container>
Content
</div>
</div>
Scripts
</body>"`
And it works

**Comment by khaiknievel** [comment]
If you are asking to only load for contents within ```<div id="barba-wrapper">...</div>```, instead of the whole document, then you might wanna read http://barbajs.org/partial-output.html.

Hope it helps. Cheers.

**Comment by mikhy888** [comment]
Worked!! 

Thank you
