### ISSUE TITLE
Load javascript file that is the wrapper

### ISSUE THREAD

**Issue by JoeriE** [luruke/barba.js#166]
Hello,

Is het possible to load a javascript file that is in the barba-container? I only want to load this file when that page is loaded. I've put the file in the container, but then it's not loaded. Is there another way?

Best wishes,
Joeri

**Comment by ArekZw** [comment]
I need the same

**Comment by eduplessis** [comment]
Here's what a do ... hope is gonna help

`var oldScript = $(pjax.oldDocument).find('script[src]')
            var newScript = $(pjax.newDocument).find('script[src]')
            var loadScript = [];
            oldScript.each(function(index, element) {
                if (!$(pjax.newDocument).find('script[src="' + $(this).attr('src') + '"]').length) {
                    $(this).remove()
                }
            })
            newScript.each(function(index, element) {
                if (!$(pjax.oldDocument).find('script[src="' + $(this).attr('src') + '"]').length) {
                    loadScript.push($(this).attr('src'))
                }
            })
            if (loadScript.length) {
                for (var i = 0; i < loadScript.length; i++) {
                    $.getScript(loadScript[i], function() {
                        if (i == loadScript.length - 1) {
                            loadInline()
                        }
                    })
                }
            }
`

**Comment by luruke** [comment]
Please check: https://github.com/luruke/barba.js/issues/170
