### ISSUE TITLE
Listen on data Attributes?

### ISSUE THREAD

**Issue by tbaddade** [luruke/barba.js#169]
Hej,
is it possible to listen on an element with an attribute like data-url or data-href?

Example:
```
<div data-url="/another/path/"> ... </div>
<button data-url="/another/path/">Go</button>
```

Thanks for your support and the great project.

**Comment by luruke** [comment]
Hello @tbaddade ,
sorry for the late reply.

What you mean by it?
Can you expand a little more your question?

**Comment by wiseoldman** [comment]
If you want to change page without using a link, you could use the `Barba.Pjax.goTo(newUrl)` function to create something that listens for clicks on elements with specific data-attributes. 

Source: http://barbajs.org/docs/Barba.Pjax.html

**Comment by tbaddade** [comment]
> If you want to change page without using a link, you could use the Barba.Pjax.goTo(newUrl) function to create something that listens for clicks on elements with specific data-attributes.

Thanks. This solved my problem.
