### ISSUE TITLE
Recommendation for including barba.js with require.js module loader

### ISSUE THREAD

**Issue by designingSparks** [luruke/barba.js#173]
Is there any recommendation for doing the above? Is it best to use the [commonjs converter tool](http://requirejs.org/docs/commonjs.html#autoconversion), or [manually convert](http://requirejs.org/docs/commonjs.html#manualconversion) each module?

**Comment by luruke** [comment]
Hello @designingSparks ,
the library is exported with webpack [UMD](https://github.com/luruke/barba.js/blob/master/webpack.config.js#L9) which should make the library compatible with require.js.

So there should be no need to convert.
