### ISSUE TITLE
transitionCompleted and load events

### ISSUE THREAD

**Issue by daltonrooney** [luruke/barba.js#175]
I'm trying to detect a load event on an element within a newly transitioned page, but it doesn't seem to be working. My listener looks like this:

```
document.getElementById("primary-banner").addEventListener('load', function(e){
  console.log(e.currentTarget);
}, true);
```
The console returns the correct element when the page initially loads, (without barba.js) but when I trigger it with the transitionCompleted event, it returns the element from the _previous_ page. Here's my complete example: 

```
Barba.Dispatcher.on('transitionCompleted', function(currentStatus, prevStatus) {
  document.getElementById("primary-banner").addEventListener('load', function(e){
    console.log(e.currentTarget);
  }, true);
});
```

Am I missing something with regard to the state of the DOM when transitionCompleted is fired?

**Comment by luruke** [comment]
Hello, 
normally at `transitionCompleted` event, the old page has been removed on the DOM.

Can you put a breakpoint inside the event, and make sure that you have a single `.barba-container`?

**Comment by daltonrooney** [comment]
I tried and do see only a single container element. I found a suitable workaround and can't recreate this at the moment, though, so let's close it for now and I'll reopen with more detail if it comes up again. 

Thanks for the great library, by the way, very easy to implement and I love the way it works.
