### ISSUE TITLE
Body gets deleted – Uncaught (in promise) on slow network

### ISSUE THREAD

**Issue by katerlouis** [luruke/barba.js#178]
I wanted to test my transition (+ loader animation etc.) on a slow network speed. 
The site breaks into a blank white page and devtools reveal that the body is just gone.
The console shows this:

![image](https://user-images.githubusercontent.com/1983382/29454253-c3d5298c-840c-11e7-9250-c8950a7ee78c.png)
(2 errors per load)

At first I thought this came from my transition.
But no, the default transition also produces this. The page seems to still be loading in the backgorund, and after a loooot of time the page is back as expected. But no loader (which should stay there until the newContainerLoading-promise is resolved) and the menu / footer / bottom-bar are gone. 

Could you shed some light in what is going on there?

The speed where the issue occurs is GPRS or slower. 
Everything faster seems to work as expected.
![image](https://user-images.githubusercontent.com/1983382/29454201-94b12b4c-840c-11e7-9e7d-5487b694bffd.png)

**Comment by luruke** [comment]
Hello @katerlouis ,
i've created a preset with same speed of GPRS on devtools (on newer version, gprs preset has been removed).

Unfortunately I can't replicate the issue.

Normally there is a 5s timeout, after that the new page will be loaded normally:
https://github.com/luruke/barba.js/blob/master/src/Utils/Utils.js#L40

**Comment by katerlouis** [comment]
It can be seen here: http://20grad.kreativzirkel.de/restaurant (obviously not finished :D)
As you describe there are only slow and fast 3G in Chrome devtools– The issue still occurs on Slow 3G

**Comment by EvanKnowles** [comment]
I've seen the same issue (the two uncaught promises) when testing with a really slow connection, but in my case the timeout did trigger and navigation started. The really slow connection meant that the next page didn't load anyway though, which might be causing the white screen you see?
