### ISSUE TITLE
Library status

### ISSUE THREAD

**Issue by dangelion** [luruke/barba.js#179]
Hi @luruke 
I found your library and it's simply awesome, really! I'd like to adopt it in our professional projects but I'd like to know what's the actual status of your library? Is it still maintained? Are you planning newer features, bugfixes, updates, ...? Please, let me know. Thanks!

**Comment by luruke** [comment]
Hey @dangelion ,
We use the library at work, but in the past month I didn't had time to work on it.

I also started a v2, but there is no release planning soon.
