### ISSUE TITLE
Initial page is not cached

### ISSUE THREAD

**Issue by katerlouis** [luruke/barba.js#183]
The first page to start the lifeCycle is not cached. 

I load page1, transition to page2, go back to page1, - page1 still needs to be loaded. 

Is this a bug in my case, or a missing feature so far?

If it is a missing feature, I'd like to suggest adding ability to cache the initial barba-container on `Barba.Pjax.start()` – URL and container are available, so it should be possible. Or am I missing something?

**Comment by luruke** [comment]
Hi @katerlouis ,
yes, actually this is a missing feature more than a bug.

**Comment by katerlouis** [comment]
What do you think about a feature like this? Worth implementing? 

Is there a way to hook onto Barba's caching system and cache the site myself?
Playing myself with Barba.BaseCache and Barba.Pjax.Cache would definitely be easier with some quick guidance of you :)

Thanks!
