### ISSUE TITLE
Fire Transitions by link class

### ISSUE THREAD

**Issue by emiglio** [luruke/barba.js#187]
Hi,
i would like to know, if it is possible to fire different transitions just by the class of the link you are clicking.
For example i have several links in one page (a class="leftscroll", a class="rightscroll", a class="upscroll" etc.). if i click on a link with the class "leftscroll" i want to fire an animation that scrolls the page to the left (like in the "Next/Prev Demo") and so on. If i click on the back button of the browser i want it to be played reverse. 

Is that possible with barba? And if it is, how? I am not very good in Javascript by the way... ;-)

**Comment by luruke** [comment]
Hey @emiglio ,
`Barba.Pjax.getTransition` is a function, you can define your own logic and return a Transition object.

That being said, you can just save a reference of your last clicked element, and check for the css class and then return the right transition.

**Comment by emiglio** [comment]
thank you very much. that solved the problem!
