### ISSUE TITLE
Does barba work with postbacks?

### ISSUE THREAD

**Issue by nojaf** [luruke/barba.js#188]
Would barba also work when submitting a POST form?

**Comment by obelmont** [comment]
What type of form are you looking to submit from?
Transitions from form submissions wont occur with barba.
A solution I have used in the past is to build an AJAX function into the relative view and run an animation from there.

**Comment by luruke** [comment]
@nojaf You should handle form submission on your own. Barba do not handles the forms

**Comment by nojaf** [comment]
Ok, thx.
