### ISSUE TITLE
Is it SEO friendly?

### ISSUE THREAD

**Issue by awsomedesigner** [luruke/barba.js#189]
Hello @luruke ,

Its awesome. Thank you for the all.

I want to know that is it SEO friendly library, like if i use barbajs in my existing website which is based on pure html css js. and i am confused  that if i use barba js is there make impact on my Google search result rank?

Sorry for my bad English.

Thank you

**Comment by luruke** [comment]
Hello @awsomedesigner ,
barba.js is SEO friendly.

For more info:
https://www.smashingmagazine.com/2016/07/improving-user-flow-through-page-transitions/
http://barbajs.org/how-it-works.html
