### ISSUE TITLE
Barba.HistoryManager.currentStatus is undefined

### ISSUE THREAD

**Issue by destefanis** [luruke/barba.js#19]
Hey there! 

Love the library, but I seem to keep running into an issue where the `Barba.HistoryManager.currentStatus()` object is always returned undefined. Whereas `prevStatus()` seems to work perfectly.

I'm following one of your demo's code in order to use a variety of transitions.

```
Barba.Pjax.getTransition = function() {
    var transitionObj = FadeTransition;

    if (Barba.HistoryManager.currentStatus().namespace === "homepage") {
      transitionObj = HomeTransition;
    }

    return transitionObj;
 };

```
Is there a preferred way for determining what transition to use when you want separate pages to use unique animations? 

Is there any chance we could add a demo with namespaces/views? I'm finding them difficult to use correctly given most pages will have two on a page initially.

Thanks!

**Comment by luruke** [comment]
Hi @destefanis !
Are you sure that `Barba.HistoryManager.currentStatus()` returns `undefined`, or it's just the `.namespace` value?

In the second case, it's normal.

When `.getTransition` is called, the next page is not loaded yet, that means that we don't know the `data-namespace` yet on the next container.

Usually I use different solutions:

**1. by URL**
___
You can make a check on `Barba.HistoryManager.currentStatus().url` to choose what Transition to use.

**cons:** could be tricky to keep track of the URL for a multilanguage / CMS driven site

**2. by namespace**
___
You can make a generic Transition, that waits `newContainerLoading` to be resolved, at that point `.namespace` will be populated and you can continue the transition accordingly.

**cons:** You need to wait the loading of the next page before starting the transition

**3. by latest clicked element**
___
You may want to save the latest clicked element
```javascript
let lastClickEl;
Barba.Dispatcher.on('linkClicked', (el) => {
  lastClickEl = el;
});
```
then, in `.getTransition`, decide the transition based on this.

**How I structure my transitions:**
___
I use commonJS modules for all my project, and I have all my transition in separate files.

To each transition I implement a `valid()` method, that could return `true` or `false`, based if that transition has the right or not to be executed.

A typical `valid` function may look like this:
```javascript
valid() {
    const prev = Barba.HistoryManager.prevStatus();

    return prev.namespace === 'page-blabla' && (window.innerWidth > 800);
}
```

and in my .getTransition I do something like:
```javascript
getTransition() {
  if (FromHomeSlider.valid()) {
    return FromHomeSlider;
  }

  if (PortfolioToCaseStudy.valid()) {
    return PortfolioToCaseStudy;
  }

  if (CaseStudyReadMore.valid()) {
    return CaseStudyReadMore;
  }

  if (CaseStudySibling.valid()) {
    return CaseStudySibling;
  }

  return FadeTransition;
}
```

This structure helps me to be very flexible, and to use that three different technique to choose if that particular transition needs to run or not.

Hope this reply fits your needs.
Cheers!

**Comment by destefanis** [comment]
Informative and thorough response! I might suggest adding something like this to the documentation. However, this is perfect, I appreciate the help.

**Comment by 19h47** [comment]
Hi everyone,

I'm trying to do like @luruke  with a `valid()` method in each transition. I think it's very clever.
So I declare a `prev` and a `next` var with `Barba.HistoryManager.prevStatus` and `Barba.HistoryManager.currentStatus` for each in this method. So I can manage my transisitions very precisely (home to page, post to page, etc).

My transition is a promise of `newContainerLoading` but `Barba.HistoryManager.currentStatus` stay undefined. I don't understand why. 

With `newContainerLoading` the new content is load and HistoryManager has been updated, isn't it? So `currentStatus` should not be undefined, right?

Thanks for the help. 😊

**Comment by luruke** [comment]
Hi @19h47 , Do you have an example you can share?
Even a small one, just to make it more clear :)

Thanks

**Comment by 19h47** [comment]
Yes, of course. 

So I have my transition.

```
var FadeTransition = Barba.BaseTransition.extend({
  	start: function() {
    	Promise
      		.all([this.newContainerLoading, this.fadeOut()])
      		.then(this.fadeIn.bind(this));
  	},
  	fadeOut: function() {
  	},
	fadeIn: function() {
  	},

  	valid: function() {

    	        const prev = Barba.HistoryManager.prevStatus();
    	        const next = Barba.HistoryManager.currentStatus();

         	console.log(prev.namespace + ' to ' + next.namespace);

        	return prev.namespace === 'home' && next.namespace === 'page' 
	}
});
```

And then: 

```
Barba.Pjax.getTransition = function() {

	if (FadeTransition.valid()) {
        	return FadeTransition;
  	}
};
```


Is my logic is correct?

**Comment by luruke** [comment]
Basically the namespace is grabbed when the next paged is loaded (it's the `data-namespace` on the container), so, you can't know in advance the namespace until `newContainerLoading` is resolved.

Does it makes sense?

**Comment by 19h47** [comment]
Ah ok, I'm too fast. 😅

I have to think differently. Thank you so much for your time, and for Barba.js!

**Comment by mikehwagz** [comment]
Really enjoying Barba!

I've come up with a technique for managing transitions that I wanted to share. Curious if anyone else has used this technique. Would really appreciate any feedback!

```js
// All transitions are managed by a single reducer transition

Barba.Pjax.getTransition = () => {
  return ReducerTransition
}



// transitions/map.js

import Transition from './'

export default {
  home: {
    single: Transition.fade
  },
  single: {
    home: Transition.slideUp
  },

  // Default transition
  default: Transition.fade
}



// transitions/reducer.js
// once the newContainerLoading promise resolves, we can check if a custom transition is defined in the map. If it's not, fall back to the default transition defined in the map.

import Barba from 'barba.js'
import map from './map'

const ReducerTransition = Barba.BaseTransition.extend({
  start() {
    this.newContainerLoading.then(() => {
      const from = Barba.Pjax.History.prevStatus().namespace
      const to = Barba.Pjax.History.currentStatus().namespace

      return (map[from][to] || map.default)(
        this.oldContainer,
        this.newContainer,
        this.done.bind(this)
      )
    })
  }
})

export default ReducerTransition



// then define transitions like so
// transitions/fade.js

function fade (oldContainer, newContainer, done) {
  function animateOut () {
    // call animateIn when animateOut is complete
  }

  function animateIn () {
    // ...
  }

  return animateOut()
}

export default fade
```

**Comment by luruke** [comment]
Thank you @mikehwagz for sharing this 👍 
This is indeed a good approach when need to have different animation `from -> to`.

Only drawback is that you must wait the next page to be loaded to know which transition to use, but in most cases it shouldn't be a problem.

**Comment by mikehwagz** [comment]
Thanks for the feedback @luruke! You've done an excellent job with this library. Hopefully the loading isn't too much of an issue on slower connections.

**Comment by TylerOlthuizen** [comment]
@luruke Back 

**To the way how you structure your custom transitions.**

_You may want to save the latest clicked element

let lastClickEl;
Barba.Dispatcher.on('linkClicked', (el) => {
  lastClickEl = el;
});
then, in .getTransition, decide the transition based on this._

**And then you are checking what was clicked and in your get transition you set this:**

_getTransition() {
  if (FromHomeSlider.valid()) {
    return FromHomeSlider;
  }

  if (PortfolioToCaseStudy.valid()) {
    return PortfolioToCaseStudy;
  }

  if (CaseStudyReadMore.valid()) {
    return CaseStudyReadMore;
  }

  if (CaseStudySibling.valid()) {
    return CaseStudySibling;
  }

  return FadeTransition;
}_


**Are you running the Barba.Dispatcher.on('linkClicked', (el)... in each of the functions you have made?**

**Comment by willbrowningme** [comment]
Got this working by following the above example using 
`const prev = Barba.HistoryManager.prevStatus();`
and
`const next = location.pathname.substr(1);`
To get the URI, I can then check the previous and next pages to make sure the correct transition is fired.

**Comment by Guaby** [comment]
Why do you need the "prevStatus" for a transition that is for the next page?

**Comment by willbrowningme** [comment]
@Guaby If you only want a certain transition to occur when going from a specific page to another then you need to check what the previous page/namespace was.

That way the specific transition won't happen if you visit the page from every single other page, only the ones you choose.

**Comment by luruke** [comment]
@josias-r 

Chrome shows the objects in the console per reference.
When you `console.log`, in that precise moment the value is undefined.

Then when you expand the object you see the new namespace. That's because the object was modified

**Comment by josias-r** [comment]
@luruke 

That makes sense, thank you very much, I was thinking it might be something like that.
