### ISSUE TITLE
Running different scripts between pages

### ISSUE THREAD

**Issue by nboliver** [luruke/barba.js#190]
Some of my pages will have different scripts that are conditionally added by plugins, depending on the page. Is there a best practice to running these different scripts after the new page has been injected? Currently only the scripts from the original page are executed (even if the script is inline, in the new page's content).

**Comment by luruke** [comment]
You should use barba.js events, and "reload" your plugins

**Comment by hartey11** [comment]
Hi, could you please provide some examples of this?

**Comment by milkdesign** [comment]
yes please! :)

**Comment by nboliver** [comment]
Using events, we can run additional js after a page load. This is what I am doing right now:

```
  Barba.Dispatcher.on('newPageReady', () => {
    const routes = new Router(pages);

    routes.loadEvents();
  });
```

The problem with this is that the original scripts that ran on the first page load will also need to be "cleaned up" before the page change (`initStateChange`), in case they conflict with the new scripts.

**Comment by milkdesign** [comment]
hey @nboliver 
this is also where i got so far. but now i think i got the same problem you were running into. how do you "clean up" the old code?

i have a script full of animations that i would like to run after every new page is ready.

**Comment by khaiknievel** [comment]
Hey @nboliver,

Not sure what the ```Router``` does. Like what is mentioned, you prolly wanna "clean up" on the barba.js events. You can prolly use 'initStateChange', just before the oldDom is removed.

```js
Barba.Dispatcher.on('initStateChange', function (newDom, oldDom) {
  // This event is also triggered on the initial page load, where there is no "oldDom"
  // Determine if there is a refs to the oldDom
  if (oldDom) {
    // Assuming the router have a method 'destroyEvents' to handle the "clean-up"
    routes.destroyEvents();
  }
})
```

Hope it helps. Cheers.
