### ISSUE TITLE
Questions about modules lifecycle

### ISSUE THREAD

**Issue by gfnool** [luruke/barba.js#191]
Hi @luruke and thank you for this project!

I'm moving from a classic _plugin-based_ coding style to a _SPA_ solution and barba.js seems to be the right choice without jumping on the big frameworks.

I would love to know more about your approach to modules init / destroy on page changes.

I guess you are using the views to init the modules contained in a particular view and then destroy them on exit. Is it right?

But, if that is the way:

1) I have to know which modules are contained in a single view in advance. Any suggestion about a solution that find the needed modules reading the DOM ("js-*" classes maybe). The problem would be the dynamic _requires_ of the modules in the view, right? 

2) During development it's always useful to test components in an isolated view. How can I test my modules if I always need a view to init them? I develop front end using Pattern Lab so I would like to have my component fully testable even out of the views (that is a template, in the styleguide language). What's your suggestion about it?

Thank you for your time!

**Comment by luruke** [comment]
Hi @gfnool ,
thanks for using barba.js.

>I guess you are using the views to init the modules contained in a particular view and then destroy them on exit. Is it right?
Yep.

> I have to know which modules are contained in a single view in advance.
Yes, I usually associate barba.js views to "templates", where I know in advance which js modules I need to use. But of course there could be generic modules used on any template.

For that I usually prefer to create a singleton instance that listen the `newPageReady ` event.

For example, let's say I have a `Slider` class, that gets an html element and init a basic slider.
Then I will create a simple "loader",

Just to give you a prof of concept:
```javascript
const instances = []

Barba.Dispatcher.on('newPageReady', (current, prev, dom) => {
    [..dom.querySelectorAll('.slider')].forEach(s => {
       instances.push({
            namespace: current.namespace,
            instance: new Slider(s)
       })
    })
});

Barba.Dispatcher.on('transitionCompleted', (current, prev) => {
  //destroy all instances of the old "page" (prev.namespace)
});
```

**Comment by gfnool** [comment]
Yes, it makes sense.

The only thing I have to work out is how to build a test environment for every component but maybe I just need a generic test.js script loaded in the styleguide only that init everything.

I'm looking forward to start working with this solution.
Thank you again.

**Comment by tokant** [comment]
@luruke could you explain how you destroy all instances? Clearly emptying the instances array is not enough. Do you set it to null and delete it like this?

instances = null;
delete instances;

What about event listeners?

Any pointers and tricks are appreciated! :-)

**Comment by gfnool** [comment]
@tokant how to destroy module instances deeply depends on how you init them and how they are built. A common pattern is to call a destroy method built in the module (where you can destroy listeners too), and if you are storing those instances in an array, like the example above, you delete the instance from the array too.

**Comment by gfnool** [comment]
@luruke Yes, although I think that one of the strong points of Barba is to be agnostic about that. Personally I would like to try [conditioner.js](https://github.com/rikschennink/conditioner) for modules lifecycle, or something like that, using the [dynamic import of webpack](https://github.com/rikschennink/conditioner-boilerplate-webpack/blob/master/src/index.js).
