### ISSUE TITLE
Function to fires ones only

### ISSUE THREAD

**Issue by psntr** [luruke/barba.js#192]
Is there a way to make a function fires only once? 
The following code was inserted inside a onEnter: function() {}, but it seems to fires everytime.
```
var something = (function() {
    var executed = false;
    return function() {
        if (!executed) {
            executed = true;
            // do something
        }
    };
})();

something(); // "do something" happens
something(); // nothing happens
```

**Comment by obelmont** [comment]
This is a scoping issue more than a Barba issue I think. 
The below code should work, I've set the executed variable as a part of the view object.

`
const View = Barba.BaseView.extend({  
  executed: false,
  onEnter(){
    if (!this.executed) {
      this.executed = true;
      // do something
    }
`

**Comment by psntr** [comment]
I see, indeed It's not so much about a barba problem, but more how to deal it with it in Barba, anyhow I will try your solution. It seems to make sense!
