### ISSUE TITLE
Page loading before leave animation

### ISSUE THREAD

**Issue by JackMichael** [luruke/barba.js#193]
I'm having trouble understanding this plugin. I want to create animations between pages, but can't seem to be able to delay the page loading so my animation can finish on page leave. In other words the next page loads before the page leave animation is complete.

`	
       Barba.Pjax.start();

	var Work = Barba.BaseView.extend({
	  namespace: 'work',
	  onEnter: function() {
	     // The new Container is ready and attached to the DOM.
	     //  Loader slides down to 0%
	  },
	  onEnterCompleted: function() {
	      // Page elements loaded
	  },
	  onLeave: function() {
	      // A new Transition toward a new page has just started.
              //  Loader slides up to 100%
	  },
	  onLeaveCompleted: function() {
	     //  Loader still at 100% height
	  }
	});
	Work.init();`

**Comment by obelmont** [comment]
I would use the [transitions](http://barbajs.org/transition.html) to handle this.
