### ISSUE TITLE
IE11 doesn't display responsive images (<picture>) on barba-page-transition

### ISSUE THREAD

**Issue by katerlouis** [luruke/barba.js#196]
Can be seen here: 
dev.20grad.com (there is no simpler way to explain what I mean, 
Use the main nav to experience the issue. I am almost exclusively using responsive images, like so

`<picture>
    <source media="(min-width: 800px)" srcset="SOMEARTDIRECTION_w200.jpg"
    <img srcset="USUALLY-FOR-PHONE.jpg" />
</picture>`

Obviously IE11 doesn't support the picture-tagg. That's why I use the polyfill by scottjehl
https://github.com/scottjehl/picturefill - since the polyfill seems to (at least for me) work fine in IE11 I assume the problem lies within Barba.

Normal img-tags are working with Barba-Page-changes, as seen on the "Bar" or "Patio" site for instance. There are 2 square images a few viewports scrolled down.

A resize results in a correct display of the responsive images. 

Since the page is highly image-driven, I need them to work badly. 
I hope we can solve this issue.

Thanks, 
katerlouis

**Comment by luruke** [comment]
Hey @katerlouis ,
you should just update your polyfill after the page change.

as the doc of picturefill says:

>You can run the picturefill() function at any time in JavaScript yourself as well, which may be useful after making updates to the DOM, or when conditions relevant to your application change:

So, just run `picturefill()` at `newPageReady` event

**Comment by katerlouis** [comment]
Thanks- Works- Bam!
