### ISSUE TITLE
Still Alive ?

### ISSUE THREAD

**Issue by xcrap** [luruke/barba.js#197]
I just wonder if the project it's still alive or it will be another smoothState. I just wonder because it's just a usefull script and like SmoothState was also kind of forgotten and this haven't updates for a year... :)

**Comment by luruke** [comment]
Hello @xcrap ,
you're right, has been a while i haven't updated the library, but it's still working 😄 , and I'm still using it on personal and work projects.

take it as a token of stability ⚖️

**Comment by xcrap** [comment]
Just to keep a note that would be great to work with forms, also multipart/form-data for file attachments, that was something that SmoothState had. Dealing individually with each form of each website tend to take me so much longer. Special forms should be taken separately but for most normal contacts forms and other the integration would be a blast.

Just a suggesting, take care.
