### ISSUE TITLE
Problems getting Barba to work correctly

### ISSUE THREAD

**Issue by bhuisman1992** [luruke/barba.js#198]
Hi there,

I'm currently working on a project (WordPress theme) where i want to include Barba. I've got it working, well.. almost! I've created some pages, each page has a couple of internal links. When is start from the homepage the transitions work as expected (i am using the fade transition from the docs). But when i start from an other page.. let say the blog page the transitions don't work. Only when i get back to the homepage and start clicking links the transitions work again. 

I've asked a friend of my and he thinks there are problems with the routing? This is new for me..

I've used only the fade transition from the docs.. nothing else like views or events.

Hope you guys van help!

**Comment by oguilleux** [comment]
Barba works perfect with WordPress no problem there. What does your console say ? Does it have any errors ?
