### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by fulvioromanin** [luruke/barba.js#199]
hi,
first and foremost thank you for the great library. It's like a breathe of fresh air.
I have a server with https certificates and i made static web pages for our upcoming web site.

<img width="72" alt="schermata 2017-10-14 alle 12 28 58" src="https://user-images.githubusercontent.com/905077/31574949-5937e0be-b0db-11e7-8725-d5742cffe288.png">

When i move from page to page with barba i lose my certificate (see picture above).
Any idea?
Thank you!

**Comment by luruke** [comment]
Hello @fulvioromanin ,
I'm using barba.js on different HTTPS websites, never had any issue.

Witch browser are you using?

**Comment by fulvioromanin** [comment]
google chrome. Might be that i'm using barba incorrectly, i'm sort of a javascript code monkey.
Can i PM you the test somehow (if you have the time...)?

**Comment by luruke** [comment]
Hey @fulvioromanin ,
you can send me a mail (you can find the detail in my profile).

I'll have a look as soon I have some time

**Comment by fulvioromanin** [comment]
thanks a lot: no pressure, when and if you can.
