### ISSUE TITLE
Blacklist links click

### ISSUE THREAD

**Issue by anhskohbo** [luruke/barba.js#20]
Thanks for great project, I have a question it's how to ignore click link in somewhere?
I see source core barda.js listen every click in a tag.

**Comment by luruke** [comment]
Hi @anhskohbo 

As stated on the FAQ of the website:
> I's possible to ignore barba.js on some links?
> You can just add the class .no-barba, or add your own check logic replacing the function Barba.Pjax.preventCheck

Here https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L194
you can have an overview of all the checks that are done before preventing or not a click.

Cheers

**Comment by anhskohbo** [comment]
Thanks!
