### ISSUE TITLE
View hangs when page can't load.

### ISSUE THREAD

**Issue by svenvandescheur** [luruke/barba.js#200]
In short
===

Barba.js doesn't seem to (document how to) deal with failed page loads properly. I.e. if I stop my devserver and click a link. Barba.js starts a transition, which never resolves. The browser seems to hang at this point without being able to provide feedback to the user.

Code used
===

```js
let FadeTransition = Barba.BaseTransition.extend({
  start: function() {
    this.oldContainer.style.opacity = 0.25;

    this.newContainerLoading
        .then(this.done.bind(this))
        .catch(e => alert('Error'));  // Expect this to be called when server is down
  },
});

Barba.Pjax.getTransition = function() {
  return FadeTransition;
};

Barba.Pjax.start();
```

The `catch` callback (promise rejection) doesn't get called. I'm unable to provide user feedback using this approach. The browser throws an "unhandledrejection" and the promise never seems to resolve (leaving the browser unresponsive).

Expected result
===
The reject callback to be called.

Actual result
===
Browser becomes unresponsive, promise never resolves.

Attempted workaround
===

As the browser gives me something, the unhandledrejection error. I tried listening to this event using an event listener:

```
window.addEventListener("unhandledrejection", () => {
  // Do some DOM stuff here.
});
```

This sort of works but is very unstable and unreliable as, as mentioned earlier. The browser is unresponsive at this time. Also, this seems like a wrong way to go as this may include other errors.

**Comment by luruke** [comment]
Hello @svenvandescheur ,
strange, when there is an error, barba should redirect you to that page:

https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L170
