### ISSUE TITLE
Keyboard / Swipe navigation and transition detection

### ISSUE THREAD

**Issue by nonlinearcom** [luruke/barba.js#203]
Hi @luruke,

I'm following the solution you suggested on #19 saving the latest clicked element in order to decide which transition is valid. 

```
let lastClickEl;
Barba.Dispatcher.on('linkClicked', (el) => {
  lastClickEl = el;
});
```
```
valid: function() {
  let prev = Barba.HistoryManager.prevStatus();
  let next = lastClickEl.getAttribute('data-link');
  return prev.namespace === 'home' && next === 'project';
}
```
Everything is working well as long as I navigate the site clicking from one link to another, the problem comes when I try to add a Keyboard / swipe navigation. Is there any way to listen for those kind of events? I know I can call the `Barba.Pjax.goTo(url);` but I couldn't find a way to pass a parameter useful for the transition detection.

Thanks in advance!

Manuel

**Comment by khaiknievel** [comment]
One suggestion is to add a hidden link within the ```.barba-container``` that tells define the prev/next url.

Example.
```html
<div class="barba-container">
  ...
  <a id="prev-page-url" href="http://url.com/prev-url" style="display:none;"></a>
  <a id="next-page-url" href="http://url.com/next-url" style="display:none;"></a>
</div>
```

Then listens to the keyboard/swipe events, just query the prev/next link and get the url. Now you can call ```Barba.Pjax.goTo(url)``` or just trigger a click on the element. 

Hope it helps. Cheers.
