### ISSUE TITLE
Wordpress Menu Toggle

### ISSUE THREAD

**Issue by tiansial** [luruke/barba.js#204]
So, I'm building a WordPress site on the Roots Sage platform.

I have a standard hamburger menu, that I'm toggling for a overlay with the navigation.

I searched for this same problem, but none of the solutions solved mine.

When I toggle the menu, past first page, the toggle function does not get run.

base.php: https://gist.github.com/tiansial/a8fa11dd5f8d3e834c3b5c84f0626b62
header.php: https://gist.github.com/tiansial/167fb9d8064b579b81c46b560caecdac
main.js: https://gist.github.com/tiansial/ca746d7fe1efdd70e2bf965dedbdeb71

Menu behaviour: https://giphy.com/gifs/26Ff05c3LpftH857G

**Comment by obelmont** [comment]
Hey those last 3 links are all the same. Could you update them please?

**Comment by 9585999** [comment]
@tiansial hello, I ran into a problem, but I still use https://github.com/mango/slideout, I decided to solve only the toggle button outside the container.

```blade
  <body @php(body_class($layout['content']))>

    <div id="wrap-aside" class="slideout-menu slideout-menu-left">
      @include('layouts.wrap-aside')
    </div>

    <div id="wrap-main" class="slideout-panel slideout-panel-left">

      <button id="navbarToggler" class="navbar-toggler" type="button" aria-label="Toggle navigation"></button>

      <div class="wrap-main-container">
        @php(do_action('get_header'))
        @include('partials.header')

        @include('layouts.wrap-main')

        @php(do_action('get_footer'))
        @include('partials.footer')
      </div>
    </div>

    @include('partials.modal')
    @php(wp_footer())
    @include('partials.counters')
  </body>
```

**Comment by tiansial** [comment]
@obelmont updated

**Comment by khaiknievel** [comment]
I seems that ```.mobile-menu``` element lives within the ```.barba-container```
https://gist.github.com/tiansial/a8fa11dd5f8d3e834c3b5c84f0626b62#file-base-php-L38

And var myMenu is referencing ```.mobile-menu```
https://gist.github.com/tiansial/ca746d7fe1efdd70e2bf965dedbdeb71#file-main-js-L22

The reference to ```.mobile-menu``` is lost when the container is being replaced.
Hence ```js myMenu```  is not referring to the new ```.mobile-menu```. 

What you can do is to move the ```.mobile-menu``` element out from the ```.barba-container```. Then, I think you will need to handle the ```.active``` state on your links.

Or you can make new reference of ```.mobile-menu``` on the newPageReady event.
```js
 var myMenu = document.querySelector(".mobile-menu"),
 ... 
 Barba.Dispatcher.on('newPageReady', function(newStatus, oldStatus, container) {
  myMenu = document.querySelector(".mobile-menu")

  // or use the container from the args. (which is your new "page")
  myMenu = container.querySelector(".mobile-menu")
});

```

Hope that helps. Cheers.
