### ISSUE TITLE
Barba.js with yandex metrica webvisor

### ISSUE THREAD

**Issue by 9585999** [luruke/barba.js#206]
Hi, I encountered such a problem, yandex webvisor does not display transitions based on this documentation https://yandex.ru/support/metrika/code/ajax-flash.html I got this code 

```js
Barba.Dispatcher.on('newPageReady', function(currentStatus, prevStatus) {
  yaCounterXXXXXX.hit(currentStatus.url, {
    title: document.title,
    referer: prevStatus.url,
  });
});
```
 but the problem is that in main.js I can not put it because the object yaCounterXXXXXX is not defined and linter does not miss, if I put it into the script tag then the object Barba becomes undefined ...

How to solve this problem???

**Comment by luruke** [comment]
Hello, is it just a problem with the linter?
make sure that yaCounterXXXX exists before calling it
