### ISSUE TITLE
Slider not iniating 

### ISSUE THREAD

**Issue by nelsonswork** [luruke/barba.js#211]
I'm using a slider and it won't initiate unless I reload while on the page. A alert will run but the script won't start until I reload the page. 

I've tried embeding the javascript on the page on ready(). 

I've tried embed the javascript on page ready. 	
Barba.Dispatcher.on('newPageReady', function() { ..slider do things..

This also didn't work. Only on load will the slider 
var work = Barba.BaseView.extend({
      namespace: 'work',
	  onEnter: function() {
	  },
      onEnterCompleted: function() {
			   $('.portfolio-slider').slick({ ....

Any help would be much apreciated.

**Comment by kjbrum** [comment]
Try using `Barba.Dispatcher.on`:

```
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, rawHTML) {
    $('.portfolio-slider').slick({
        ...
    });
});
```

**Comment by dmcshehan** [comment]
@kjbrum Thank you very much. You saved my life!

**Comment by kjbrum** [comment]
@dmcshehan It's listed on the events page. http://barbajs.org/events.html

**Comment by dmcshehan** [comment]
I have another question. When I use Barba js on my website, php WordPress functions like "body_class()" isn't working. I think it's because ajax. What do you suggest?

**Comment by luruke** [comment]
@dmcshehan add `body_class` on your `barba-container`, instead of the body.
