### ISSUE TITLE
Done() function issue

### ISSUE THREAD

**Issue by marishkaSunrise** [luruke/barba.js#212]
Hi! Thank you for your awesome plugin. I faced some issues while installing it. It would be great if you can help me to deal wit it. 
Html looks like this:

```
<body>
	<div id="barba-wrapper">
               <div class="barba-container" data-namespace="homepage2">
	             My content
             </div>
        </div>
</body>
```
I initialized the plugin and added the transition:
```
Barba.Pjax.start();
var FadeTransition = Barba.BaseTransition.extend({
		start: function () {
			Promise
				.all([this.newContainerLoading, this.fadeOut()])
				.then(this.fadeIn.bind(this));
		},

		fadeOut: function () {
			
			$('#main').hide();
			return $('.barba-bg').animate({
				width: '100%'
			}, 700).promise();
		},

		fadeIn: function () {
			
			var _this = this;
			var $el = $(this.newContainer);
			$el.css({
				visibility: 'visible',
				opacity: 1
			});
		
			$('.barba-bg').animate({
				width: 0
			}, 700, function () {
				
				$(this.oldContainer).hide();
				
				_this.done();
			});
		}
	});

	Barba.Pjax.getTransition = function () {
		return FadeTransition;
	};
```
Everything works as expected BUT in my console I see this error:

```
barba.js:599 Uncaught TypeError: Cannot read property 'removeChild' of null
    at Object.done (barba.js:599)
    at HTMLDivElement.<anonymous> (b-init.js:37)  //line in my script - _this.done();
    at HTMLDivElement.e.complete (jquery.min.js:3)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at i (jquery.min.js:3)
    at Function.r.fx.tick (jquery.min.js:3)
    at ab (jquery.min.js:3)

```
Can you please help me with this issue?

**Comment by luruke** [comment]
Hi there,
https://github.com/luruke/barba.js/blob/master/src/Transition/BaseTransition.js#L75
the `done` function, removes the oldContainer from the DOM.

Can you make sure that `this.oldContainer` is defined and has a parentNode before calling `.done`?

**Comment by robcsimps** [comment]
On closer inspection it has nothing to do with class names. It's throwing this error if an element has a CSS animation applied to it and I'm calling `this.done();` on the new container using on `animationend`.

So it might be calling `this.done();` once the container and any elements with animations inside the container have finished animating.

Figured I'd put this here incase anyone else has a similar issue.
