### ISSUE TITLE
Flickering between page transitions

### ISSUE THREAD

**Issue by vanhunselm** [luruke/barba.js#218]
Hi guys!

I was wondering if someone could help me with the following issue:
When I was testing my website with clicking around, from link to link to check if there where issues between loading transitions I came to the following issue:

If I am navigating from my main nav at the top there are no problems. But when I want to go to a new page from a button in the page wrap I have some flickering between my page transitions. 

The best way to check it yourself is: 
1. go to [my live website](http://ptchr.nl/mailcampaigns/klantcases.html)
2. scroll a little bit down to the button at the right : 'bekijk deze case' and click
3. In the load from the current page to the new page there you see a white gap or something. The blue loader is going to the background and you can see the oldContainer.

I can't found out the solution, so hopefully there is anyone that can help me!

Thanks @luruke for the great work!

**Comment by Adamoc14** [comment]
Hi i'm having this problem with my site too, my site is at https://artbyanc.netlify.app , when you load this first it will perform the eye animation perfectly when performing a Barba transition to another page however the eye flickers. Just wondering what you did @HunselM @luruke to fix this problem.

**Comment by olliepeg** [comment]
Did this problem ever get resolved @Adamoc14  @HunselM ? I have exactly the same issue. 

Thanks

**Comment by Adamoc14** [comment]
Hi @olliepeg,
Nope. I never found a solution, I just took the loading eye animation out of the other pages I was using Barba on. Can't say the same for @HunselM because I don't know how he solved it but the page I designed for a client is here if you want to have a look-  https://artbyanc.com 👍

**Comment by olliepeg** [comment]
Thanks @Adamoc14 not really a solution for me though.

I'll see if I can find something and I'll post the solution here. Worth noting the additional Barba Prefetch Plugin did nothing.

I don't know why this original thread was closed by @luruke unless he found a solution.

**Comment by olliepeg** [comment]
@Adamoc14 my issue was having fixed or absolutely positioned elements that I was animating in with the Barba sync:true function. Turning sync to false fixes or keeping sync to true but making everything relative positioning also fixes it.

For now I have settled with turning the sync function off. I think the sync function tries to load the page instantly, and that causes a flash before the animation kicks in. @luruke  is there a way round this in the future?
