### ISSUE TITLE
Question About React.js & Barba.js

### ISSUE THREAD

**Issue by khanprog** [luruke/barba.js#221]
Can someone provide a boilerplate for using barba.js in react.js ? Or the procedure of using it with react.js, I want to do transition on different components using the react-router.

**Comment by obelmont** [comment]
Probably better off using [react-transition-group](https://github.com/reactjs/react-transition-group) for this.

**Comment by khanprog** [comment]
yeah did that with react-transition-group but if barba.js  provide support for that cool things gonna be developed through that :)

**Comment by kamalendugarai** [comment]
I want to revoke this conversation again as there is a new version available and it supports more cool stuff. I want to use Barba with react js. I know there are similar libraries available I can use but my choice of development is Barba.js, I love the way it works. So, will anyone please shed some light on this.

**Comment by obelmont** [comment]
#553 @xavierfoucrier's answer to using barba with react or another frontend framework might help point you in the right direction. Essentially though it's probably better to use a react library. I mentioned react transition group above but these days I've been using framer motion to handle my animations and page transitions in react.

**Comment by yvikasofficial** [comment]
@kamalendugarai  Barba.js is not compatible with react. They need to redo the entire library using react router or something else which i guess is not going to be from barba.js side. Hopefully some one from react community might pull this off in the future.

**Comment by Nytsee** [comment]
The way Barbajs works today is a completely different approach than React in term of navigation / routing ...
