### ISSUE TITLE
Barba transition issue with the fadeIn

### ISSUE THREAD

**Issue by HectorLS** [luruke/barba.js#222]
## _"barba.js": "^1.0.0"_

Hello, first of all thanks by this awesome lib discovered just a few days, 😄 

I'm setting up a simple fadeOut and fadeIn transition.

**javascript** 
```javascript
Barba.Pjax.Dom.wrapperId = 'pjax-wrapper';
Barba.Pjax.Dom.containerClass = 'pjax-content';

var options = {
      start: function() {
        Promise
        .all([this.newContainerLoading, this.fadeOut()])
        .then(this.fadeIn.bind(this));
      },
      fadeOut: async function() {
        var deferred = Barba.Utils.deferred();
        this.oldContainer.classList.add('fadeOut');

        // 1º option setTimeout way
        // await setTimeout(() => {
        //   console.log('fadeOut Ended');
        // }, 300);

        // 2º option event 'transitionend'
        this.oldContainer.addEventListener('transitionend', () => {
          console.log('fadeOut Ended');
          deferred.resolve();
        }, false);

        return deferred.promise;
      },
      fadeIn: async function() {
        this.newContainer.classList.add('fadeIn');
        this.done();
     }
 };

Barba.Pjax.start();
Barba.Dispatcher.on('linkClicked', function(element) {
     lastElementClicked = element;
});


var customTransition = Barba.BaseTransition.extend(options);
   Barba.Pjax.getTransition = () => {
     return customTransition;
}
```

**scss file**
```scss
.pjax-content {
  opacity: 1;
  transition: opacity 300ms ease-out;
  will-change: opacity;

  &.fadeOut {
    opacity: 0;
  }

  &.fadeIn {
    opacity: 1;
  }
}
```

I have the problem with the fadeIn function because the newContainer just go in without the fade.
Not sure how to approach this problem 😢 

because the newContainer will come with the opacity 1 given by my css right ? so i have to first set the opacity to 0 in the fadeOut function ?? seems weird so any light here would be much appreciated.

Also i had the same problem with the fadeOut function and i solved it first with a promise, a setTimeout and a transitionend listener. Which one is the best approach ? 😕 

Thanks in advance

**Comment by wiseoldman** [comment]
This is an old question and you've probably figured out why it didn't work by now, but I'll explain it in case other people are having the same problems.

Let's take a look at the fadeIn method from the documentation: http://barbajs.org/transition.html

`fadeIn: function() {
    /**
     * this.newContainer is the HTMLElement of the new Container
     * At this stage newContainer is on the DOM (inside our #barba-container and with visibility: hidden)
     * Please note, newContainer is available just after newContainerLoading is resolved!
     */

    var _this = this;
    var $el = $(this.newContainer);

    $(this.oldContainer).hide();

    $el.css({
      visibility : 'visible',
      opacity : 0
    });

    $el.animate({ opacity: 1 }, 400, function() {
      /**
       * Do not forget to call .done() as soon your transition is finished!
       * .done() will automatically remove from the DOM the old Container
       */

      _this.done();
    });
  }`

And let's have a look at the description for newContainer

> HTMLElement of the new container. (with visibility: hidden;)

In the example from the documentation you can see that the properties **visibility: visible and opacity: 0** is applied to the newContainer element, this is what you're missing. You can't fade the new container in, when it already has an opacity of 1 so you have to change it to 0 first.

**Comment by darrickfabian** [comment]
say @wiseoldman, I too have a quick question if you have the time. In this demo: http://barbajs.org/demo/nextprev/index.html

I'm having an issue getting this swipe effect to work without gsap. using base jquery animate is seemingly not able to have both the old and new containers animating on the page at the same time. Is gsap required for this effect?

thanks so much.
