### ISSUE TITLE
Listener if the user click the browser BACK button

### ISSUE THREAD

**Issue by HectorLS** [luruke/barba.js#223]
Hello
I checked the API serching for a 'browser BACK listener' but i didn't find it.

Is there a listener to run if the user click the browser back button ? 
Because i want to reset the some params in the body to the initial state.

**Sample case:**
_1. Index load -> background white
2. user hover a link and i change the background to blue ( because that page linked has background blue)
3. page with the blue background loaded using barba._

Now if the user click the browser back button he is going to see the index with the background blue. And should be white like when he load the page via url

So in case there is no listener for that, can i at least change the document stored by barba for the back link ?

**Comment by magicspon** [comment]
Something like this should help... 

```
let linkClicked = false

Dispatcher.on('linkClicked', () => {
  linkClicked = true
})


Dispatcher.on('initStateChange', ( => {
  if (!linkClicked) {
    console.log('state changed without a link being clicked... back button?')		
  }
})

Dispatcher.on('transitionCompleted', () => {
  linkClicked = false
})
```

**Comment by bronze** [comment]
was looking for a solution to this myself, saw a comment on https://www.bountysource.com/issues/35867798-barba-js-v2-open-discussion by @bramcordie that did the trick for me (had to switch some lines though).
Leaving this here so it may help someone else.

```
var popping = false;

window.addEventListener('popstate', function () {
  popping = true;
});

Barba.Pjax.start();

Barba.Pjax.getTransition = function() {
  return popping ? HideShowTransition : FadeTransition;
};

Barba.Dispatcher.on('initStateChange', function() {
  popping = false;
});
```
or set popping false on click
```
var lastElementClicked;
Barba.Dispatcher.on("linkClicked", function(el) {
  lastElementClicked = el;
  popping = false;
});
```
