### ISSUE TITLE
Mimic the browser back button History Manager

### ISSUE THREAD

**Issue by RhysyG** [luruke/barba.js#225]
How can I get my app back buttons working like the browser back button using the History Manager?

Navigation flow example:

Home > Notifications > Post

By clicking back I want

Post > Notifications > Home

Mimicking the browser back button.

At the moment I am using

`PrevLink.href = Barba.HistoryManager.prevStatus().url;`

However this leaves me in an endless loop:

Post > Notifications > Post > Notifications > Post > Notifcations ect

I know `Barba.HistoryManager.history;` has an array of all my URL’s but how can I go back from this:

- Home
- Notifications
- Post

If I go back from Post, then I have 4 in the array and I'm not sure how to get to Home.

- Home
- Notifications
- Post
- Notifications

Thanks

**Comment by RhysyG** [comment]
I ended up solving this not using History manager but simply javascript:history.back()

**Comment by coreymade** [comment]
@RhysyG Where did you put this in your code.  I am having a problem where hitting the browser back button instantly changes the page, but you can see the animation starting to work....

**Comment by RhysyG** [comment]
@coreymade I just put this on a back button I made myself. Yes in my project clicking the browser back button changes the page too.
