### ISSUE TITLE
Barba transition on jQuery click function

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmm** [luruke/barba.js#228]
Hi,

does anybody has as example on how to use a barba.js transition with a jquery click function? I want to have different animations that will be executed when clicking on a specific link. 

Something like this:

```
$(id).click(function(event) {
     start: function() {
        Promise
          .all([this.newContainerLoading, this.fadeOut()])
          .then(this.fadeIn.bind(this));
     },
});
```

**Comment by wiseoldman** [comment]
Maybe this answer can help you? https://github.com/luruke/barba.js/issues/19#issuecomment-223874845
