### ISSUE TITLE
no reload when i go back

### ISSUE THREAD

**Issue by Taigistal** [luruke/barba.js#229]
**Situation**
If you click on a link and the new page is loaded by pjax. Then you got back (by link or by browser-back-button) and the first view is loaded new.  

**When is that a problem?**
When your first view is a shop or a blog and you load posts/articles by infinit-load-ajax-onscrolldown, and got back you start at the top of the page and not on the scroll position you clicked the link. and all the post for this position have load again.
***Example:***
http://gemeindeneugruenden.de/blog/

In an other example i load a map and you can visit the pages when you click on the orange icons in the map and then "MEHR ERFAHREN". (http://gemeindeneugruenden.de/netzwerk/). Especialy here the problem is big, cause the full map have to load again when you go back.

**Question**
Is there a work around? Is it possible to load the single-view on to top of the archive-view (or map-view) and then remove this view simply when you go back? Or any other way? Is it clear what i mean? did you ran into any similar problems in your work?

**Comment by gregogalante** [comment]
@Taigistal do you have found a solution or workaround for the problem? I have a similar issue with an e-commerce website with infinity scolling.

**Comment by Taigistal** [comment]
@gregogalante 
No, sorry.

**Comment by revelyn99** [comment]
I've been struggling with this, too. @Taigistal @gregogalante did you guys look at [159 ](https://github.com/luruke/barba.js/issues/159)? I believe this is the same issue, and it seems that @Mellis84 solved it using localStorage.
