### ISSUE TITLE
 How to load scripts depending on the page where I am

### ISSUE THREAD

**Issue by leandrovidela** [luruke/barba.js#230]
Hi,

I am working in a site with different pages and when I go to another page the script does not load, I mean, the functions related to that page are not executed.

If I use a bundle and I go to another page, it does not work either.

How can i solve this?

Thanks!

**Comment by kekkorider** [comment]
It's not that difficult, you just need to [set up a View](http://barbajs.org/views.html) and execute that function on the `onEnterCompleted` event.

Example: you want to run a function on a single news, so you set a `data-namespace="single-news"` attribute on the `.barba-container` div into that page

```
<div class="barba-container" data-namespace="homepage">
```
Than you initialize that view into your JS file

```
const SingleNews = Barba.BaseView.extend({
    onEnterCompleted: () => {
        myfunction();
    }
});

SingleNews.init()
```

That's it!

**Comment by leandrovidela** [comment]
Hi @kekkorider,

I did it as you indicated and I had to add an "off" to the function, otherwise when I navigated to another page the function was still called.

This way it works, what do you think? 

`function pageTwo (){
  console.log($('#element-on-page-two').offset().top);
  console.log($(window).scrollTop());
}  

var SingleNews = Barba.BaseView.extend({
  namespace: 'page-two', 
  onEnter: function(){
    $(window).on('scroll', pageTwo);
  },
  onLeave: function() {
    $(window).off('scroll', pageTwo);
  }  
});`


Do you know another way?

Thank you very much!

**Comment by kekkorider** [comment]
If you need that function to stop executing when leaving the page, that's the correct way to do it ;)
