### ISSUE TITLE
Wordpress Ninja Forms?

### ISSUE THREAD

**Issue by hartey11** [luruke/barba.js#234]
Hi,

Has anyone managed to get the ninja forms plugin to work with barba?

**Comment by magicspon** [comment]
What would you want barba to do with your forms?

**Comment by luukScheur** [comment]
Ninja Forms is a Wordpress plugin, it loads by javascript and only fires when page is loaded. It does not fire when switching/loading pages with Barba. Is there an option/hook to reload certain html/scripts in Barba?

**Comment by brandenMB** [comment]
Anyone have luck with this? Just ran into it.

**Comment by monacofrancisco** [comment]
Anyone had any luck with this?

**Comment by maxjutras** [comment]
+1 for this

**Comment by splurtcake** [comment]
Having the same issue

**Comment by amanullahtanweer** [comment]
Any solution for this?
