### ISSUE TITLE
Using in Drupal?

### ISSUE THREAD

**Issue by someika** [luruke/barba.js#238]
Hello!
I'm looking for a page transition library for my Drupal site.  I want  some cool ajax transition between two nodes. Should I use Barba (at first I thought about Stranger things Barb!) and how? I added barba.min.js to my theme, wrapped the output of nodes with barba classes, what should I do next? Or is it for advanced in JS users?
Thank you

**Comment by magicspon** [comment]
If you have your markup setup correctly, and the javascript has loaded, `Barba.Pjax.start();` should get things started for you...

http://barbajs.org/installation.html

**Comment by asipple1** [comment]
I would like to help out here. The following is using animate.css to animate bounceOutRight the old container and bounceInRight the new container. With Drupal adds a bunch of classes to the body so you want to make sure you re-add them back-in hence the for loop in the "in" function. Cheers!
`import Barba from 'barba.js';

Barba.Pjax.start();

document.addEventListener("DOMContentLoaded", function() {
  var FadeTransition = Barba.BaseTransition.extend({
    start: function() {
      Promise
        .all([this.newContainerLoading, this.Out()])
      .then(this.In.bind(this));
    },

    Out: function() {
      this.oldContainer.classList.toggle('bounceOutRight');
      return new Promise(function(resolve, reject) {
         window.setTimeout(function() {
           resolve();
        }, 600);
      });
    },
    In: function() {
      let body_classes = Barba.Pjax.Dom.currentHTML.match(/body\sclass=['|"]([^'|"]*)['|"]/)[1];
      let body_class_array = body_classes.split(' ');
      let body = document.getElementsByTagName('body')[0];
       body.className = '';
       for (let body_class of body_class_array) {
        body.classList.add(body_class);
        }
      this.newContainer.classList.toggle('bounceInRight');
      this.done();
    }
  });
  Barba.Pjax.getTransition = function() {
    return FadeTransition;
  };`
