### ISSUE TITLE
problem with waypoints

### ISSUE THREAD

**Issue by hellobarrio** [luruke/barba.js#239]
Hi...
i'm trying to work with your library but i've a problem with this function...

```
// When the footer is 50% offset it add the class becameYellow to section

$('footer').waypoint({

	handler: function(direction) {

		if (direction === 'up') {

			$("section").removeClass("becameYellow");

		} else {

			$("section").addClass("becameYellow");

		}

	},

	offset: '50%'

});

```
I called the function on page load (and works) and in every barba view but when i change page 
the class 'becameYellow' is always added to the section.

It's very strange because all the other functions do not give problems... for example this:
```
// Every time the class animation enter on the the viewport

j('.animation').waypoint({

	handler: function() {

		j(this.element).addClass("start");

	},

	offset: '90%'

});

```
in every view i call this functions 

```
$(window).scrollTop(0);
$("main").removeClass("becameYellow");
```

it is like every time I change the page the footer was in the viewport but it's not actually..

sorry for my english...
can you help me?
thanks
francesco

**Comment by luruke** [comment]
Hello @hellobarrio ,
Probably during your transition, when you hide the old container the footer comes up and it become visible for some time.

I would suggest to debug adding a breakpoint inside your waypoint handler, and see what's the situation in that moment

**Comment by hellobarrio** [comment]
Ok the footer comes up and I know... but how can i fix it?
Footer is inside the old container...

tnx
