### ISSUE TITLE
Transitions give errors on IE11

### ISSUE THREAD

**Issue by dendeffe** [luruke/barba.js#245]
I used this tutorial to get the transitions working: https://redstapler.co/barba-js-tutorial-add-transition-effect/

However, on IE 11 I get errors, for instance on
this.newContainerLoading.then(val => this.fadeInNewcontent($(this.newContainer)));

Can I get this working on IE11?
Or only load Barba.js if the browser is not IE11/supports the JS?

**Comment by abhishekaugust84** [comment]
I am also facing same issue

**Comment by timotheus0106** [comment]
me2. any workaround?
