### ISSUE TITLE
Routing, Deep Linking, and custom URLs 

### ISSUE THREAD

**Issue by javierforero** [luruke/barba.js#246]
Hi @luruke / guys,

I am pretty new to Barba.js and I've been playing around with it; However, I haven't found any documentation about deep linking or custom urls.

Basically I have a site where I have a navbar, body content, and a footer. I want to swap out the body content as I navigate to different links while my nav and footer stay the same.  I know this is easily done by creating a view and wrapping your html in a div with a class of ``.barba-container``. 

It's all groovy until I deep link, or refresh the page in one of the views that don't have the navbar or the footer. I basically just get the content. Is there a way around this?

Also, is it possible to get rid of the html extensions and have the URL just be the view name?

Any help would be greatly appreciated.

**Comment by wiseoldman** [comment]
You should always have the HTML for both your header and footer in the generated pages. Barba will only swap out the stuff you place in it's wrapper.

If you don't add a header and footer for all your pages, google have no way of knowing that they should all have those, and you'll miss out on a lot of your internal page links.
