### ISSUE TITLE
Barba.js and Webpack bundles

### ISSUE THREAD

**Issue by cutme** [luruke/barba.js#247]
I use Webpack and on my website each of my subpages loads a separate "bundle.js" file.

**webpack.config.js:**

```
entry: {
        index: "./src/index.js",
        work: "./src/work.js",
        project: "./src/project.js",
        services: "./src/services.js"
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: "[name].bundle.js",
    }
...
```

Is it possible to load these bundle files on each subpage separately? 
Do I have to have one common.bundle.js?

Currently, it only loads the contents of index.bundle.js, which is actually located under `<div id= "barba-wrapper"> </ div>`.

**Comment by magicspon** [comment]
you could use the new dynamic import syntax.

```
import(`/project.js`)
	.then(resp => {
		resp.default()
	})
	.catch(err => {
		console.error(err)
		reject()
	})
```
