### ISSUE TITLE
Scrollbar Resize

### ISSUE THREAD

**Issue by moszart** [luruke/barba.js#253]
Hello, I started using barba just a few days ago, and I noticed that the scrollbar doesn't resize when a new page is loaded. For example, if I open the home page (which has a lot of content) and then I go to a post, that new page stays with the height of the home (leaving a blank space after the footer).

What could it be the reason for this? 

Thanks in advance!

**Comment by begonaalvarezd** [comment]
Hello! I am having the same problem. Any thoughts?

Thanks!
