### ISSUE TITLE
Scroll position restoration on popstate page transitions not working consistently with basic hide/show transition

### ISSUE THREAD

**Issue by blimpmason** [luruke/barba.js#254]
First of all I love working with this library and use it on almost all of my projects. Thanks to @luruke and all the contributors.

I'm trying to figure out how to restore scroll position consistently when using the browser back / forward buttons with basic page transitions. For example, if you scroll to the bottom of a long index page, then click to a shorter page, then hit the browser back button, ideally the user should land in the same position on the index page. But they don't. This is especially detrimental when browsing product grids on e-commerce sites because the customer can lose their place and give up. 

It seems they land where they were on the index page minus the height of the page they just came from (if that page is shorter). If the page you are coming back from is longer then there is no issue and scroll position is restored.

To illustrate this issue I setup a really simple demo:

https://blimpmason.github.io/barba-scroll-test/index.html

Steps to reproduce the issue:
1. Scroll to the bottom of the index page so item 20 is visible
2. Click "Single Item" in the nav
3. Click browser back button 

If you scrolled all the way down to item 20 in the index, you'll return to item 19 (which happens to be the page height of the index minus the page height of the page you are returning from).

If you instead follow these steps, scroll position is restored:
1. Scroll to the bottom of the "5 Items" page
2. Click into "10 Items" from the nav
3. Click the browser back button

You should land right back at the bottom of 5 Items with item 5 showing. I assume this is because the page you are returning from is taller than the page you are returning to.

Here is the simple transition I'm using in the demo:
```
var HideShowTransition = Barba.BaseTransition.extend({
	start: function start() {
		this.newContainerLoading.then(this.finish.bind(this));
	},
	finish: function finish() {
		document.documentElement.scrollTop = 0;
		this.done();
	}
});
```

If anyone has any ideas or potential solutions I'd love to hear them. I've also been experimenting with the [MoOx/pjax](https://github.com/MoOx/pjax) library which includes reliable scroll restoration, so I know it's possible. If I'm not missing something obvious, perhaps this feature could be incorporated into v2.

**Comment by gitsilvan** [comment]
This looks like #229 and I have the same problem
