### ISSUE TITLE
The best way to handle Barba.Pjax.preventCheck

### ISSUE THREAD

**Issue by jdaude** [luruke/barba.js#255]
Hello

First of all, thanks for this awesome library.

Could you please tell me how to handle properly Barba.Pjax.preventCheck, because I use barba with wordpress and when my client want to use the adminbar and navigate trought the website, Barba.js works, but when I click to "edit page", the backoffice of the previous landing page show up.

So for now i did a quick fix with this code :

            if ($('body').hasClass('admin-bar')) {
              
              Barba.Pjax.originalPreventCheck = Barba.Pjax.preventCheck;

                Barba.Pjax.preventCheck = function(evt, element) {
                  return false;
              };
            }

But I have an error `Uncaught TypeError: Cannot read property 'href' of null at Object.onLinkClick (barba.js?ver=4.9.1:1)`

Thanks a lot.

**Comment by crobbinsdg** [comment]
The easiest way is to add the class those links share (.ab-item) to a list of ignore classes.

```
// ignore rules
Barba.Pjax.originalPreventCheck = Barba.Pjax.preventCheck;
Barba.Pjax.preventCheck = function(evt, element) {
	if (!Barba.Pjax.originalPreventCheck(evt, element)) {
		return false;
	}

	// ignore pdf links
	if (/.pdf/.test(element.href.toLowerCase())) {
		return false;
	}

	// additional (besides .no-barba) ignore links with these classes
	// ab-item is for wp admin toolbar links
	var ignoreClasses = ['ab-item', 'another-class-here'];
	for (var i = 0; i < ignoreClasses.length; i++) {
		if (element.classList.contains(ignoreClasses[i])) {
			return false;
		}
	}

	return true;
};
```

**Comment by Natalie-er** [comment]
Hello!
Please tell me how to solve the same problem in barba version 2.
Can't find a solution from the documentation https://barba.js.org/
