### ISSUE TITLE
Barba! Choose what to reload?

### ISSUE THREAD

**Issue by pevdp** [luruke/barba.js#259]
Hello ! 

I've an issue with using Barba.

Here is the website : 
http://www.pierreemmanuelvandeputte.com/index.php

My menu is buging, when I switch pages, the name of the current page should be underline, but it's not when I switch page, you have to refresh the page to get the effect... I dunno why barba interract here...
Does anyone can help me to figure this out?
Thanks!

Pierre

**Comment by thisbailiwick** [comment]
Barba is replacing the content within the div `#contact.barba-container`. Your header is not within that container so it's not being updated.
Your options are to use js to manually add/remove the class `.active` on your menu item links or to replace the full header by changing where your barba classes are within the dom.

**Comment by prilcool** [comment]
why are all this unresolved issues being closed ? there is no solution provided  just hints , I checked the guys website seems he still could not understand your solution so he did not implement barba js and commented it out ,  If you are a coder or develop you should take pride and provide proper solutions to tickers  that actually help someone resolve there issues prior to closing the ticket.  Just saying according to ITIL standards for  ticket closure  this is below standard . facts.

**Comment by pevdp** [comment]
True... Thanks for your truly comment.
All the best,
Pierre

**Comment by idrisdopico** [comment]
The answer: Move your header to where it's inside of the Barba container
