### ISSUE TITLE
Animations not working in Safari

### ISSUE THREAD

**Issue by somehandle** [luruke/barba.js#26]
I've tried out all the demos in Safari 9.1.1 but none of the animations seem to work. What browsers are supported with this?

**Comment by luruke** [comment]
Hi @somehandle!

Normally they should work on Safari.

I will not have access to a laptop until monday so I can't test it right now.

Can you check if there are any error in the console?

**Comment by somehandle** [comment]
There aren't any errors in the console but it doesn't affect any of the functionality in terms of changing pages. Just no animations currently.

**Comment by patrick91** [comment]
@somehandle hey, it works for me (sorry for the fast GIF)

![](https://patchscreen.s3-eu-west-1.amazonaws.com/kibako/58857D5E-BEF6-44CA-87EA-5AE6E19AB921/2016-06-1016_38_18.gif)

On which OS are you trying the demos?

**Comment by somehandle** [comment]
@patrick91 - I'm on El Capitan - 10.11.5, Safari is completely vanilla, I don't have any extensions installed

**Comment by patrick91** [comment]
Same as me, then :)

Sorry for asking silly questions, but, is javascript enabled? https://up.kibakoapp.com/ArdTJHh6xQ

**Comment by luruke** [comment]
@somehandle Very strange. If JavaScript is enabled can you debug one of the demo adding a breakpoint to the Tweenlite call?

**Comment by luruke** [comment]
@somehandle, can you retry?
TweenMax is loaded from an external cdn, maybe there was some problem with it...

Just tested on mac osx 10.11.2 with Safari 9.02 and everything works fine.

I'll close the issue until we have more info,
Cheers.
