### ISSUE TITLE
Barba with Angular with no router

### ISSUE THREAD

**Issue by joSFD** [luruke/barba.js#260]
Hi !

I'm using Angular1x on a Wordpress custom theme, but without the routing solution.

Barba is working well, but when the new html is inserted, directives and controllers are not triggered.  

```
Barba.BaseTransition.extend({
   done: function() {

   }
})
```
-> What should i call here to apply directives & controllers that are in the injected html ?

I guess it is more an Angular question but i thought i could give a try here.  
Any idea ?  Other way to see it ?

Thank you very much.

Johan

**Comment by TheOld** [comment]
Hey @joSFD did you find a solution for this? I'm having the exact same issue. 😞

**Comment by joSFD** [comment]
@TheOld Unfortunately not yet.  The thread is also on [Stackoverflow](https://stackoverflow.com/questions/49639365/barba-js-with-angularjs-with-no-router), you might vote it up.  I'll need to sort it out max for the end of next month.  I'll put the solution here and there.  Let me know if you find any bits of it.  Cheerz !

**Comment by luruke** [comment]
This looks more an issue / question related to angular than barba.js
