### ISSUE TITLE
Adding .current-menu-item to Wordpress nav links

### ISSUE THREAD

**Issue by hlotvonen** [luruke/barba.js#263]
Hi!
I'm using Barba with Wordpress.
Works wonderfully, the only problem I have is updating navigation link classes.

Normally on Wordpress, clicking on a Menu Navigation link gives the `<li>` element a class `.current-menu-item`, which can be useful for styling options.

The problem is that the navigation element is outside the `#barba-wrapper` and `.barba-container` so it doesn't get the transitions:

```
<body <?php body_class(); ?>>
<nav>
  <?php wp_nav_menu( ); //prints a list with links ?> 
</nav>
<div class="content-wrapper" id="barba-wrapper">
```
and I have a hard time figuring out how to give `.current-menu-item` to the corresponding list item.
I read this answer but left confused: [#95](https://github.com/luruke/barba.js/issues/95)
What would be the best way to do this? Thanks!

**Comment by psntr** [comment]
@hlotvonen you can refer to this post:
https://github.com/luruke/barba.js/issues/43
