### ISSUE TITLE
transitionCompleted fires on page refresh?

### ISSUE THREAD

**Issue by mikemedoro** [luruke/barba.js#264]
I was wondering why the transitionCompleted event fires when you do a hard browser refresh when a transition isn't happening? I'm trying to detect when a hard refresh happens compared to a barba event but can't seem to get this working.

I want to reinitialize a WordPress(Contact Form 7) plugin on transitionCompleted which works fine, but if you go directly to that page or do a browser refresh, it gets initilized twice and the form sends duplicate messages.

Any insight here?

```
Barba.Dispatcher.on('transitionCompleted', function (currentStatus, oldStatus, container) {

        console.log('transition complete');
	initContactForm();

});
```

**Comment by Kwapi** [comment]
I'm having the same issue

**Comment by luruke** [comment]
It's firing the event because you're binding the event listener before you're initialising barba.
If you don't want to change the order, you can add a check the length of `Barba.Pjax.History.history`, so you know how many pages the user visited.
