### ISSUE TITLE
no transition when using windows.location.href

### ISSUE THREAD

**Issue by federicosan** [luruke/barba.js#265]
I have a slide menu with divs, each div has an onClick method = to windows.location.href ="name.html"  for example. The transitions work well when clicking a normal anchor tag but fail on this kind of linking. Maybe I have to set something else for this to work? just using the example codes for transitions.

**Comment by psntr** [comment]
you have to use 
`Barba.Pjax.goTo('name.html')`

**Comment by xavierfoucrier** [comment]
Use `barba.go` in BarbaJS v2.
> See https://barba.js.org/api/classes/core_src.core.html#go.
