### ISSUE TITLE
Click works only in the first page but not in second, third and next pages

### ISSUE THREAD

**Issue by mattiaband** [luruke/barba.js#268]
the transition between the pages works very well.
but I have a problem, I am not able to trigger the click on the second, third etc page, the click works just if you are in the first page.
something like this

```
$(".xxxxx").on('click',function(){ 
console.log('clicked'); 
})
```

any ideas?

**Comment by watzing** [comment]
@mattiaband You'll need to reattach the event listeners when the DOM is loaded.

Hook into the Barba event API like so:

`Barba.Dispatcher.on('transitionCompleted',  () => {
  $(".xxxxx").on('click',function(){ 
      console.log('clicked'); 
  })
});`

**Comment by mattiaband** [comment]
thanks @watzing , it works ;)

but I have another doubt, this means that I have to duplicate (repeat) the same code when DOMContentLoaded and when Barba 'transitionCompleted' ?

**Comment by quentinneyraud** [comment]
Hi @mattiaband ,

Yes, you have to call these lines of code each time you add `.xxxxx` elements. 
Or you can use [delegated event handlers](http://api.jquery.com/on#direct-and-delegated-events) :

```javascript
$(document).on( "click", ".xxxxx", function() {
  console.log('clicked', $(this))
});
```

But check [performances warnings](http://api.jquery.com/on#event-performance) (Replace `document` by the closest parent of your `.xxxxx` elements which will stay in your page across animations, maybe `#barba-wrapper`)

**Comment by mattiaband** [comment]
great!
thanks @quentinneyraud and @watzing ;)
