### ISSUE TITLE
Is there a way to update multiple containers and automatically update meta?

### ISSUE THREAD

**Issue by terion-name** [luruke/barba.js#27]
Common usecase: a site that has a layout and inner contents. Inner contents should be updated with a transition, layout elements (nav menu, header, footer) — instantly (you click in a link an menu state changes, or event whole layout changes).
So is there a way to update several containers independently and with different transitions? 
And also, to change page meta (e.g. title)?

**Comment by luruke** [comment]
Hi @terion-name!

You can just have one container and one single transition at the time.

For the elements outside the container (usually footer and header) you should update manually using Barba.js events.

The title meta is already updated automatically.

For my experience, usually:
- The only thing I change outside the container are the active class on the menu.
- Apart from the title meta, all the others tags don't need to change.

Hope it makes sense.
Can you give me some examples where barba.js features are not suitable for your needs?

Cheers

**Comment by terion-name** [comment]
@luruke thank you
Currently I'm deciding about to use barba or not (it looks great btw, so I really want), so I don't have live examples at the moment. But the case why I'm asking this question is current site that have different header and footer states on different pages. Not just nav active states, but the entire header/footer contents
And I don't see events in barba that can help with this :(
Currently I see just one solution — wrap entire layout with barba-wraper and change the whole page body and handle transition effects manually by events..

**Comment by luruke** [comment]
Hello, @terion-name .

So, yes, in your case you may try to wrap all your body in a container.

Cheers

**Comment by luis-carvalho** [comment]
Hey folks, similar problem here. 
Apart from the meta title, normally the pages on my websites should change the og:image and og:title for the social media sharing (facebook, twitter, etc).
So @luruke , as I could understand, your solution is to change these parameters by js, right?
By the way, huge Barba fan here!!! 
Just launched this: http://douroscala.pt

**Comment by luruke** [comment]
Hello @luis-carvalho ,
nice website!

Your "issue" has been already discussed:
https://github.com/luruke/barba.js/issues/82
http://stackoverflow.com/questions/41793016/barba-js-pjax-js-and-head-replacing

**Comment by thisanimus** [comment]
I'm working on a project and I wanted to include meta:theme-color and msapplication-TileColor in the head for a little bit of pizazz.  I was able to dynamically rewrite the whole header by grabbing the PJAX head string from Barba.Pjax.Dom.currentHTM, and rewriting the DOM head:

```javascript
  Barba.Dispatcher.on('newPageReady', function(el) {
    var el = document.createElement( 'html' );
    el.innerHTML = Barba.Pjax.Dom.currentHTML;
    var newhead = el.getElementsByTagName('head')[0].innerHTML;
    document.getElementsByTagName('head')[0].innerHTML = newhead;
  });
```
