### ISSUE TITLE
Click and go to same container

### ISSUE THREAD

**Issue by seppeclijsters** [luruke/barba.js#273]
I have a container (in Wordpress) 
`<div class="barba-container" data-namespace="projectDetail">`

When I click on another project, the link will redirect to thesame "projectDetail" container but with other content.  In this case my Javascript won't work anymore because it goes to the same container. Anyone knows a solution?

`const DetailPage = Barba.BaseView.extend({
    namespace: 'projectDetail',
    onEnter: function() {

    },
    onEnterCompleted: function() {
        // The Transition has just finished.

    },
    onLeave: function() {
    },
    onLeaveCompleted: function() {
        // The Container has just been removed from the DOM.
    }
  });

**Comment by luruke** [comment]
You would need to handle the js lifecycle using barba events or views.
