### ISSUE TITLE
Issue with memory leak when using plugins

### ISSUE THREAD

**Issue by zmitic** [luruke/barba.js#274]
First, let me tell you that I **love** barba! It is so much easier to use it than tons of NG components with repeatable code. 

But I do have a problem and will use one example: I understand I can't use something like this:

```js
$(document).ready(function () {
    $('.select2entity').select2entity();
});
``` 

but if I use it like this:

```js
Barba.Dispatcher.on('newPageReady', function (current, prev, rawContainer) {
    let container = $(rawContainer);
    container.find('.select2entity').each(function () {
        $(this).select2entity();
    });
});
```

will it create memory leaks?

This was just a simple example, I have leaks left and right and I can't figure where they are coming from. 

I do have some events registered in this way (again, same fake example for simplification):

```js
$(document).on('click focus mousedown', '.app-uploader:not(.initialized)', function () {
    $(this).addClass('initialized');
    $(this).select2entity();
});
```

Which one should I use? Do I have to unbind events on ``newPageReady`` first before binding them again?

The problem is that application I made is already pretty big and I just started using heap snapshots. I am afraid that browser will start to slow down if visitor visits many pages.

Thanks.

**Comment by luruke** [comment]
Hello @zmitic ,
in theory you should manually handle the init/destroy of the different plugins/third party at page change.

So, you need to make sure that plugins are exposing a kind of destroy/unbind methods and call them when needed.
