### ISSUE TITLE
Having trouble with basic fadeIn transition

### ISSUE THREAD

**Issue by mindatlarge** [luruke/barba.js#275]
Great lib, but i just can't get it to work, even basic transition like fadeIn, its so frustrating.
What am i missing????
I've made an example, 

https://aeroplancow.github.io/

Thanks in advance.

**Comment by mindatlarge** [comment]
When i add Barba.Pjax.start();
then link doesn't work.

**Comment by shanewmurphy** [comment]
Ok watch 
https://www.youtube.com/watch?v=EApR7BCzXCk
https://redstapler.co/barba-js-tutorial-add-transition-effect/

![screen shot 2018-05-17 at 18 08 27](https://user-images.githubusercontent.com/3694619/40206286-4207028a-5a27-11e8-9322-7ca7ca20e6f5.png)

Best of luck!

**Comment by mindatlarge** [comment]
Yeah, i tried that as well but then i get this kind of error.

![screen shot 2018-05-18 at 00 39 58](https://user-images.githubusercontent.com/36458806/40207297-1a6769ec-5a34-11e8-943b-df488184394a.png)

**Comment by mindatlarge** [comment]
**_solution:_**
run in through localhost
