### ISSUE TITLE
Animations not working when navigating back to previous page

### ISSUE THREAD

**Issue by shanewmurphy** [luruke/barba.js#277]
Honestly, this plugin is more trouble than its worth!!! 

I've got the basic set-up fadeIn & fadeOut between pages. 

When I navigate back to the previous page the animations using anime.js won't reanimate back in only if I refresh the page.

**Comment by apsolut** [comment]
maybe you are using just $(document).ready... 
did you try  to use:  `Barba.Dispatcher.on('newPageReady', function() {
 //your scripts here ...
});`

**Comment by shanewmurphy** [comment]
Hi, @apsolut thanks for your reply.

Wasn't using $(document).ready function 

I've tried you're solution below with no enjoy, it's ignoring the fadeIn - fadeout behaviour.

Anyway, I'm done (trash can) with this plugin, for one of the most utter frustrating plugins.

**Comment by CassiusHR** [comment]
> Hi, @apsolut thanks for your reply.
> 
> Wasn't using $(document).ready function
> 
> I've tried you're solution above with no enjoy, it's ignoring the fadeIn - fadeout behavior.
> 
> Anyway, I'm done (trash can) with this plugin, for one of the most utter frustrating plugins.
> 
> The only way to use Barba.js is by NOT using it!

You could try actually learning some javascript instead of cyring.
