### ISSUE TITLE
Listen to an event that fires before the AJAX call is made

### ISSUE THREAD

**Issue by bravokiloecho** [luruke/barba.js#279]
Is there currently a way to listen to an event that fires before any AJAX call is made? Something like:

```
Barba.Dispatcher.on('beforeLoad', function() {
  //your listener
});
```
If this doesn't exist, would it be possible to add it to this really useful library?

Many thanks!

**Comment by luruke** [comment]
Hello @bravokiloecho ,
what would be the usage of such event?

**Comment by luruke** [comment]
Ok, i see @bravokiloecho .
I'll check if add such event in a new version.

**Comment by bravokiloecho** [comment]
Brilliant, thanks @luruke!

I'm excited to hear there might be a new version. I use Barba.js a lot and find it really helpful. So many thanks for all your work on it!
