### ISSUE TITLE
Make this project available via Bower

### ISSUE THREAD

**Issue by jankal** [luruke/barba.js#28]
Dear @luruke!

What about making this project available via Bower?

**Comment by jankal** [comment]
Didn't read #21

**Comment by thomasmikkel** [comment]
I agree. Bower support would be great.

**Comment by luruke** [comment]
Hi @thomasmikkel , have you tried to install with bower from github?

The command should be:
```
bower install luruke/barba.js
```

**Comment by thomasmikkel** [comment]
Thanks
