### ISSUE TITLE
Please provide an example that uses CSS transitions

### ISSUE THREAD

**Issue by shermandy** [luruke/barba.js#281]
I am struggling to adapt the available demo code to work with CSS transitions. I do not want to use jQuery because I am building a lightweight website. Plus, jQuery is DEFINTIELY overkill for a simple fade in/fade out effect.

If someone could help me understand how to adapt the fade in/out effect but with vanilla JS and CS transitions, I would be forever in their debt!

**Comment by luruke** [comment]
@shermandy you can use whatever you want for the transitions.
You just need to write the logic, have a look at the documentation or example to find out how.
