### ISSUE TITLE
Hard reload on Barba.Pjax.goTo when using URL parameter

### ISSUE THREAD

**Issue by psntr** [luruke/barba.js#282]
I've seen the previous post #34  about the hard load on clicked elements.

But in my case, I'm not using a click element to trigger the page change but I use a "select" option with the "url" store in:
`<select>
  <option value="?category=apple">apple</option>
  <option value="?category=banana">banana</option>
</select>
`
upon change I trigger a `Barba.Pjax.goTo($(this).val())`

`	$('select').on('change', function(){
		Barba.Pjax.goTo($(this).val())
	})
`

Then I tried to adapt the code found on #34 but no chance…
`var links = document.querySelectorAll('option[value]');
var cbk = function(e) {
 if(e.currentTarget.value === window.location.href) {
   e.preventDefault();
   e.stopPropagation();
 }
};
for(var i = 0; i < links.length; i++) {
  links[i].addEventListener('change', cbk);
}`

**Comment by luruke** [comment]
Hello @psntr , I believe the issue is more related to your app logic.
I would just add a check before the .goTo call

**Comment by psntr** [comment]
@luruke indeed, I had to finally changed the code logic now it's working.  Thank you for keeping us updated on the issue! Have a nice day

**Comment by colinory** [comment]
@psntr what did you change? I'm having the problem that only the url changes. But I don't see the page transition and the content change..

**Comment by psntr** [comment]
It's been a while, but I finally just change to:

`$(' select').on('change', function(e){
		var newURL = $(this).find('option:selected').val()
		Barba.Pjax.goTo(newURL)
	})`
