### ISSUE TITLE
More control over initial styling of newContainer

### ISSUE THREAD

**Issue by dunnl** [luruke/barba.js#286]
This was also discussed in issue #33 but I think nothing came of it.

Currently, when the `newContainer` is inserted into the DOM by [putContainer](https://github.com/luruke/barba.js/blob/9f66f8ebc03394a666fbc865c05dde99c2fc4ebf/src/Pjax/Dom.js#L135), it is hidden with `visibility: hidden`. But this takes up space on the screen still. In my application, this causes issues by pushing other elements away from where they should be. I think I would like to toggle the `display` property instead, but I don't see a way to accomplish this.

More broadly, I suggest allowing users to control how the new element is inserted. It seems that I can control how the `oldContainer` fades out, and how the `newContainer` fades in, but I can't control the initial styling of the `newContainer` to begin with.

Note that it wouldn't make much sense for me to serve the page with my containers set to `display:none` by default. I think there is a distinct need to let users set the initial styling of the new container strictly when it was inserted by Barba.

**Comment by dunnl** [comment]
I was able to accomplish what I wanted by supplying my own `Barba.Pjax.Dom.putContainer`. That's good enough for me, but since it's annotated with `@private` I'm wondering if this is a good long term solution.

**Comment by CassiusHR** [comment]
Can you help me with this? im having the exact same problem and i cant fix it.

**Comment by luruke** [comment]
Hey @dunnl ,
i've used visibility instead of display for different reasons as explained in the ticket you mention.

However you can change it just overriding the styles in your transition, no?
As soon the newContainer is ready, you can just change the styles, would it be a solution?
