### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by Mraghe** [luruke/barba.js#288]
Hi there,
first of all, thanks for this awesome plugin, it's really useful and versatile.

I've passed the last 3 days fighting against this error

> Uncaught (in promise) TypeError: Cannot read property 'style' of undefined

I've tried to debug with chrome inspector element but I can't undestand where the problem is. It says that the problem is on the function "done()" of my custom.js

The url of the site is www.adwm.it/test/

it gave me this error on the first time I enter in the site and try to enter in a single post, or from the single post when I go back to the home. It seems like it can't load the newContainer before applicate the style, so it gave me the newContainer but the style is "visibility: hidden".

The same site is hosted in my localhost (with xaamp, apache, php 7.x) and it hasn't any problem. 

If someone has any idea of the problem I will be very grateful. 

If you need more information, just ask and excuse me if I have not been very clear with my English

**Comment by luruke** [comment]
Hello @Mraghe ,
I can't replicate the issue right now.

Are you making sure the newContainer is ready and loaded before trying to change the style?
