### ISSUE TITLE
Views aren't showing in the right containers?

### ISSUE THREAD

**Issue by insanetisane** [luruke/barba.js#29]
Hi there,
I was running a little test but something seems off. You can see it here:
https://plnkr.co/edit/5GbDn8Rque7hZ2gNEPrY?p=preview

Seems to be putting the content in the wrong place. Am I missing something?

**Comment by luruke** [comment]
Hi @insanetisane, thanks for trying Barba.js.

In your demo you are not using "Views".
For Views I mean this: http://barbajs.org/views.html
Which is essentially just an helper to handle the javascript status for a specific container.

In your code what is wrong is that you have multiple container per page.
You can just have one container per page.

Also, in test.html you are launching `Barba.Pjax.start()` twice, one including script.js and the other one from the inline javascript.
Also note that, `Barba.Pjax.start()` needs to be called when the DOM is ready, so, avoid to include your script.js in the head.

Hope it makes sense!
Let me know if you still have problems

**Comment by insanetisane** [comment]
Hey @luruke, thanks for the quick reply!
Ah now I understand. I assumed the name-spacing meant that you could have multiple containers on a page. Makes sense now! Thanks!
