### ISSUE TITLE
Barbas make all my other js stop

### ISSUE THREAD

**Issue by loicng** [luruke/barba.js#291]
Hello i search a lot
i also see dispatcher and other code 
but nothing worked

when i use barba js
all my other script didnt load on newpage .
but it appear

can anyone know how to solve it?

**Comment by tan-ahmed** [comment]
I have same issue but I believe it's something to do with this:
https://github.com/luruke/barba.js/issues/32

I literally just need my lazy load script to run
var bLazy = new Blazy();

**Comment by c0mrx** [comment]
When any site does an AJAX call, it cannot re evaluate script tags. Please see this issue: #32 

You need to reinitialize your scripts in using barba events. http://barbajs.org/events.html

For instance: 

```
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {
  // Re-init your scripts here.
});
```

So for tan-ahmed's example, you'd have the bLazy script outside of the barba container, and initialize in in JS.

```
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {
  var bLazy = new Blazy();
});
```

**Comment by adisoftUmag** [comment]
Hello

Related to this problem. How can i reinitialize this part of code which dont work after barba.js load new page

```
        $('#dole').on('click', function() {
          $('#dole').toggleClass('active');
        });

```

I make all work when i put it in finish after this.done();

```
        finish: function() {
          document.body.scrollTop = 0;
          this.done();
          $('#dole').on('click', function() {
            $('#dole').toggleClass('active');
          });
        }
```
but i'm interested how to do it with - Barba.Dispatcher.on

**Comment by c0mrx** [comment]
@adisoftUmag You would probably want to use the `transitionCompleted` event, which fires after the old page has left the DOM and the new page has transitioned in. So it would be as follows: 

```
Barba.Dispatcher.on('transitionCompleted', function(currentStatus, oldStatus, container) {
  $('#dole').on('click', function() {
       $('#dole').toggleClass('active');
     });
});
```

**Comment by adisoftUmag** [comment]
@c0mrx Thx for help. It works

**Comment by tan-ahmed** [comment]
@c0mrx 
You legend!!

I did 

```
<script>
jQuery(document).ready(function($) {
    Barba.Dispatcher.on('transitionCompleted', function (currentStatus, oldStatus, container) {
    var bLazy = new Blazy();
  });
});
</script>
```

and this solved my problem, thanks so much dude

**Comment by Alaamasoud** [comment]
Hello,
How can i fix this problem if i use v2 ?

**Comment by aydinvivik** [comment]
How can i fix this problem if i use v2 ?

**Comment by Jonatan-r** [comment]
> @c0mrx
> You legend!!
> 
> I did
> 
> ```
> <script>
> jQuery(document).ready(function($) {
>     Barba.Dispatcher.on('transitionCompleted', function (currentStatus, oldStatus, container) {
>     var bLazy = new Blazy();
>   });
> });
> </script>
> ```
> 
> and this solved my problem, thanks so much dude

Doesn't seem to be working for current version? v2? 

This is dead: http://barbajs.org/events.html

Can't find anything like this in new docs?

**Comment by comrx** [comment]
@Jonatan-r This response was for v1. For v2 you'll have to use [Hooks](https://barba.js.org/docs/advanced/hooks/) You can see all of the different hooks [here](https://barba.js.org/docs/advanced/hooks/#Base-hooks).

Example:
```
barba.hooks.enter(() => {
  // init your js here
});
```

**Comment by Jonatan-r** [comment]
@comrx Thank you!!! 😄 Sorry, stupid me hadn't explored the docs thoroughly enough

**Comment by comrx** [comment]
@Jonatan-r,

No problem, happy coding! 😄

**Comment by Jonatan-r** [comment]
@comrx Thanks! 

I had understood this though: http://barbajs.org/events.html :

```
barba.init({
  views: [{
    namespace: 'home',
    before() {
      // update the menu based on user navigation
      menu.update();
    },
    enter() {
      // refresh the parallax based on new page content
      parallax.refresh();
    }
  }]
});
```

– As if I could just dump my scripts in the `enter() ` and then it would run.. but it sems that doesn't work

**Comment by Jonatan-r** [comment]
> @Jonatan-r This response was for v1. For v2 you'll have to use [Hooks](https://barba.js.org/docs/advanced/hooks/). You can see all of the different hooks [here](https://barba.js.org/docs/advanced/hooks/#Base-hooks).
> 
> Example:
> 
> ```
> barba.hooks.enter(() => {
>   // init your js here
> });
> ```

Yup. This works perfectly :)))

**Comment by mirmoc** [comment]
I'm on V3 and it doesn't seem to work. How can I make it work?

`enter () {
				Barba.Dispatcher.on('transitionCompleted', function(currentStatus, oldStatus, container) {
					$(".wrapper-intro-text, #logo").on("click", function (e) {
						e.preventDefault();
						$("body").toggleClass("on");
					});
					
					$(".hamburger").on("click", function (e) {
						e.preventDefault();
						$("body").toggleClass("min");
					});
				  });
			}`

**Comment by comrx** [comment]
Hi @mirmoc!

Barba.Dispatcher is for use in V1. I see you're using [Hooks](https://barba.js.org/docs/advanced/hooks), so the proper code here would be:

```
... 

enter () {
  $(".wrapper-intro-text, #logo").on("click", function (e) {
    e.preventDefault();
    $("body").toggleClass("on");
  });

  $(".hamburger").on("click", function (e) {
    e.preventDefault();
    $("body").toggleClass("min");
  });
}
```

For the `.hamburger`... It would be best to add that listener globally (outside of the barba function), since it's sitting outside of the barba container and only needs that listener once.

I'd also caution using `.toggleClass()`, and actually replace that with a hasClass conditional, like so:

```
  $(".hamburger").on("click", function (e) {
    e.preventDefault();
    if ($('body').hasClass('min') == false) {
      $("body").addClass("min");
    } else {
      $("body").removeClass("min");
    }
  });
```

Anything outside of the barba container only needs listeners added once, as they never leave the DOM (unless you change them yourself with custom code). Therefore, it's best to keep them out of the transition code and have them initialized on their own.

If you need something to run after every transition regardless of namespace, you can also use [Global Hooks](https://barba.js.org/docs/advanced/hooks/#Global-hooks). These should be kept outside of the transition function as well:

```
barba.hooks.enter(() => {
  window.scrollTo(0, 0);
});
```

Hope this helps!

**Comment by mirmoc** [comment]
Amazing! Thank you. That fixed my problem, also the advice with the toggle. It wasn't working with toggle inside Barba.

**Comment by mirmoc** [comment]
I have a little fiddly bit for a rookie like me. Outside Barba I'm calling this function like this

`document.addEventListener('load', (event) => {
	const videos = document.querySelectorAll('video')	
	const observer = new IntersectionObserver(entries => { 
		entries.forEach(entry => {
			entry.intersectionRatio > 0 ? entry.target.play : entry.target.pause()
		})
	})	
	videos.forEach(video => {
		observer.observe(video)
	})
})`

And in my Barba hook it doesn't work (sorry, a bit longer)

`			enter({ current, next, trigger }) {
			return new Promise(resolve => {
	
				window.scrollTo({
				top: 0,
				behavior: 'smooth'
				})

				const videos = document.querySelectorAll('video')	
				const observer = new IntersectionObserver(entries => { 
					entries.forEach(entry => {
						entry.intersectionRatio > 0 ? entry.target.play : entry.target.pause()
					})
				})	
				videos.forEach(video => {
					observer.observe(video)
				})
				
			const timeline = gsap.timeline({
				onComplete() {
					resolve()
			}
			})

			  const pTag = document.querySelectorAll('p')
			  const header = document.querySelector('nav, .title')
	
			  timeline
				.set(next.container, {opacity: 0})
				.to(next.container, {opacity: 1}, 0)
				.to(pTag, {opacity: '1', delay: 1, stagger: .2 }, 0)
				.to(header, {y: '0%'}, 0)
				.to(header, {opacity: 1}, 0)
			})	`

**Comment by DanDvoracek** [comment]
For the ones reading this and using V2, I managed to fix this using the afterOnce() and afterEnter() hooks. The best is to set up views ([barba views](https://barba.js.org/docs/advanced/views/)) for that and add the hooks in there. This way you can use the "data.next.container" to target the correct elements in JS. 

I took the path to create a [JS class](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Classes) per view, this way I have been able to properly refactor the scripts.

**Step 1:**

```
import Home from './barba/pages/Home';

barba.init({
  ...
  // Pass views specific scripts
  views: [Home],
...
});
```

**Step 2:**
```
import Swiper, { Navigation } from 'swiper';

class Home {
    namespace = 'home';

    // Custom function
    initSliders(sliders) {
        //...
    }

    // When page loads or reloads
    afterOnce = data => {

        this.initSliders(sliders);

    };

    // When transitioning from another page
    afterEnter = data => {
        this.initSliders(sliders);
    };

}

export default new Home();
```


Hope this helps someone.

**Comment by Laura-ddr** [comment]
Hello I am using Barba V2 with scroll locomotive 
I managed to destroy and reload the scroll locomotive script.

`barba.hooks.beforeLeave((data) => {scroll.destroy();});`
`  barba.hooks.after((data) => {scroll.init();});`

only I have a file "/js/parts/blog.js" called in the footer in which I include the animation of my home.
It works on the first page load but when I navigate and come back to the home my script doesn't work anymore.

Could you enlighten me I am a beginner with barba
