### ISSUE TITLE
how to handle additional deep linking within a page - like a carousel

### ISSUE THREAD

**Issue by moldedjelly** [luruke/barba.js#298]
First up, awesome library.

I've got it working well on the beginnings of a site, but wandering if it's possible to intercept the url change and prevent the ajax load from happening so that some selective URL changes might be able to be handled by the current loaded View.

I can see that using "Barba.Pjax.preventCheck" I can intercept link clicks and analyse the href on the element clicked, and return false and preventDefault() to have the system not react, but I want it to still change the URL, but not do the ajax load and instead call a method on the current View - for example to handle deep linking for a carousel within a page.

And I'm guessing I'd need to also catch URL changes just through the back/forward navigations... so I'd need to do the intercepting above inside the Dispatcher event "initStateChange" - but not sure how I'd stop the default ajax loading from there either. 

Any help or ideas much appreciated.

**Comment by luruke** [comment]
Hello @moldedjelly ,
I never had to do that...so I'm not sure if It can be done easily.

I would probably use location hash for that, without changing the URL via pushstate - also because the new url won't exist "server-side".
