### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by timsamuelsson** [luruke/barba.js#299]
Is this still maintained? It would be good to know before i start using it for my next project.

//Tim

**Comment by thisbailiwick** [comment]
It mostly seems so based on issues/pull request/commit details. There's another project I briefly looked at which may do something similar and is active. I haven't looked into it yet though: https://github.com/gmrchk/swup

**Comment by luruke** [comment]
I didn't had much time to dedicate to this project recently.
Hopefully it should change in the near future :)
