### ISSUE TITLE
custom js and carousels not working

### ISSUE THREAD

**Issue by shashwattiwari** [luruke/barba.js#301]
Hi,

I tried bootstrap carousel and owl carousel but it's not working along with barba.js.  Is there any way can I do it with your script?

**Comment by c0mrx** [comment]
You need to use events. There are probably over 100 issues here with the answer. Have a look at issue #291.

**Comment by shashwattiwari** [comment]
Thank you so much! I referred to your `<a href="https://github.com/luruke/barba.js/issues/291#issuecomment-408439082" target="_blank">comment</a>` and it worked.
