### ISSUE TITLE
Global functions on every page

### ISSUE THREAD

**Issue by sebszocinski** [luruke/barba.js#305]
Hey guys, is there a way to setup global functions that run on initial page load and re-run on Barba's `newPageReady` dispatcher as well for **every page** _(not namespace specific)_

Currently I have to do this in my main file which is a bit ugly...

```	
require('./libs/smoothscrolling.js')
// load smoothscrolling script on initial pageload
Barba.Pjax.start()

Barba.Dispatcher.on("newPageReady", function(c, p, html) {
	require('./libs/smoothscrolling.js')
	// re-run smoothscrolling script on new Barba transition
})
```

**Comment by c0mrx** [comment]
@sebszocinski Have you tried using views? You'd have to set it up for each namespace, but `onEnter` and `onEnterCompleted` run on the initial page load, as well as after transitions have occurred so you'd only have to init `smoothscrolling.js` once per namespace.

`
<div class="barba-container" data-namespace="homepage">
`

`
var Homepage = Barba.BaseView.extend({
  namespace: 'homepage',
  onEnter: function() {
      // The new Container is ready and attached to the DOM.
  },
  onEnterCompleted: function() {
      // The Transition has just finished.
  },
  onLeave: function() {
      // A new Transition toward a new page has just started.
  },
  onLeaveCompleted: function() {
      // The Container has just been removed from the DOM.
  }
});

// Don't forget to init the view!
Homepage.init();
`

**Comment by sebszocinski** [comment]
hi @c0mrx yeah i'm well aware of Views and use them all the time, but thats exactly the issue i'm trying to avoid... having to repeat adding `smoothscrolling.js` to each view file. I have about 10 already on this particular project and will be adding more... but I want `smoothscrolling.js` to be global and run across the whole site including every page... surely there is another way?

**Comment by gordonwes** [comment]
``` 
function initPage(newPage) {
    initSmoothScrolling(newPage);
    // other function
}

function initSmoothScrolling() {
    var elem = newPage.querySelector('your-selector');
    // ........
}
var MovePage = Barba.BaseTransition.extend({
    start: function () {
         Promise
             .all([this.newContainerLoading, this.outPage()])
             .then(this.inPage.bind(this));
     },
     outPage: function () {
         // hide the start page
     },
     inPage: function () {
         var newWrap = this.newContainer;
         // show the destination page
         initPage(newWrap);
     }
});

**Comment by luruke** [comment]
You can just use global barba.js event to bind your "global" functions at each page change
