### ISSUE TITLE
Search form in header with transitions to results page

### ISSUE THREAD

**Issue by JayBox325** [luruke/barba.js#308]
I have a Search form in the header of my site that I'd like to submit with Ajax, run a transition and return the results template on the next page.

Is this currently possible? A lot of chatter I've read on the issues for Barba.js suggest using Ajax to submit a form and return the response within the same page.

I am building this with a CraftCMS project and it was suggested to use a plugin to lead to the results template, but this won't be within my Barbja transition framework.

My page transitions are a mask that obscures the screen with the page title for the next container on. So if my users click 'about us' in the nav, the mask says 'about us' inside. I'd like to see if there's currently the ability to use this transition for my results page.

I can supply any markup if it'd help to see.

Thanks

**Comment by luruke** [comment]
Hello @JayBox325 ,
currently barba doesn't handle the forms, you'll need to handle them "manually".
