### ISSUE TITLE
Reload js on home?

### ISSUE THREAD

**Issue by gnom** [luruke/barba.js#309]
Hi!
I installed barba on my futur site, but I do not understand why all my animations are no longer loaded when I return to the home? 
https://agence-logo.fr/agencelogo2017/

What is the solution ? 
Thank you !

**Comment by luruke** [comment]
Hello @gnom ,
probably your issue is that since barba.js transforms your site as a kind of single page application you need to handle the lifecycle of your js plugins using the events when the page "changes"
