### ISSUE TITLE
Barba.BaseTransition.start() missing from API

### ISSUE THREAD

**Issue by ZachSaucier** [luruke/barba.js#31]
`Barba.BaseTransition.start()` is missing from [the API](http://barbajs.org/docs/Barba.BaseTransition.html). It should at least say that it needs to be implemented and when it is called.

P.S. Is the API or the [splash page](http://barbajs.org/index.html) open source so we can help make contributions?

**Comment by luruke** [comment]
Hi @ZachSaucier !
You're right, definitely needs to be added in the API Doc.
It is partially explained here: http://barbajs.org/transition.html

The API Documentation is automatically generated with [JSDoc](http://usejsdoc.org/), through some special comments directly in the code. Then, the documentation is generated running `npm run generatedoc` on the project.

Barba.js is my first project with JSDoc, so there may be better convention or way to use it.

Said that, you're more then welcome to contribute with PR!
All the website (and the docs) is on the gh-pages branch, so, feel free to contribute!

**Comment by luruke** [comment]
Will be live on next release.

Reference commit: https://github.com/luruke/barba.js/commit/1550f69d346443aa6ad313bf23790c2201921e1d
