### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Promise' of undefined

### ISSUE THREAD

**Issue by elmorsy282** [luruke/barba.js#310]
```
		$('document').ready(function(){
			Barba.Pjax.start();
			var pagetrans = Barba.BaseTransition.extend({
				start: function() {
					Promise
						.all([this.newContainerLoading, this.left()])
						.then(this.right.bind(this));
				},
				left: function() {
					var transon = $(".transition").animate({left: '0px'});
					return $(this.oldContainer).transon.Promise;
				},
				right: function() {
					var _this = this;
					var $el = $(this.newContainer);
					$(this.oldContainer).hide();
					$el.css({
      					visibility : 'visible',
    				});
					var transoff = $(".transition").animate({left: '100%'});
					var dones = function() { _this.done(); };
					$el.transoff.dones;
				}
			});
			Barba.Pjax.getTransition = function() {
  				return pagetrans;
			};
		});
```
**the transition not working fine just start slide left and doesn't back right**

**Comment by elmorsy282** [comment]
i'am not good in jquery

**Comment by luruke** [comment]
Hello @elmorsy282 ,
I guess the problem it's in your transition, i'm not that sure about this line:

```
var transon = $(".transition").animate({left: '0px'});
					return $(this.oldContainer).transon.Promise;
```

I'm  closing since it's not a direct problem with the library

**Comment by elmorsy282** [comment]
i changed all code this the new one still transition not working
`	$('document').ready(function(){
		//var bgTrans = TweenMax.to(".zoxx-trans", 0.5, {right:0});
		//var qtTrans = TweenMax.to(".trans-quotes", 0.5, {opacity:1, delay:1});
		//var bgTransf = TweenMax.to(".zoxx-trans", 0.5, {left:"100%",ease: Back.easeOut,delay:3});
		var pagetransition = barba.BaseTransition.extend({ 
			start: function(){
				Promise.all([this.newContainerLoading, this.trans()]).then(this.transs.bind(this));
			},
			trans: function(){
				TweenMax.to(".zoxx-trans", 0.5, {right:0});
				TweenMax.to(".trans-quotes", 0.5, {opacity:1, delay:1});
			},
			transs: function(){
				var _this = this;
				var $el = $(this.newContainer);
				$(this.oldContainer).hide();
				$el.css({
      				visibility : 'visible',
					opacity : 0
    				});
				var tt = TweenMax.to(".zoxx-trans", 0.5, {left:"100%",ease: Back.easeOut,delay:3});
				$el(tt,function(){
					_this.done();
				});
			}
		});
		Barba.Pjax.getTransition = function(){
  			return pagetransition;
		};
		Barba.Pjax.start();
	});`
