### ISSUE TITLE
In my website i added barba.js, But the issue is when i go to inner pages barba animations are working but other javascript functions are not working

### ISSUE THREAD

**Issue by sankarsans** [luruke/barba.js#312]
i have a website in my html page i added barba.js, it works fine but if i go to inner pages barba animations are working fine. but other javascript functions are not working.

so i added this barba script in html page,

```
$('document').ready(function(){
  //initIndexJs();
  var transEffect = Barba.BaseTransition.extend({
    start: function(){
      this.newContainerLoading.then(val => this.fadeInNewcontent($(this.newContainer)));
    },
    fadeInNewcontent: function(nc) {
      nc.hide();
        var _this = this;
          $(this.oldContainer).fadeOut(1000).promise().done(() => {
            nc.css('visibility','visible');
              nc.fadeIn(1000, function(){
                _this.done();
                })
              });
            },
          });
          Barba.Dispatcher.on('transitionCompleted', function(currentStatus, oldStatus, container) {
            initIndexJs();
            //callForPageLoad();
    });
    Barba.Pjax.getTransition = function() {
      return transEffect;
    }
    Barba.Pjax.start();
});
```
actually i need all the functions (barba.js and javascript) are working perfectly without any issues.
 so anyone please help me to solve this problem..

**Comment by luruke** [comment]
Hello @sankarsans ,
as explained multiple times in other issues:
Barba transforms your site in a kind of single page app, so you have to init/destroy your script plugins manually using events or views.

**Comment by sankarsans** [comment]
hai @luruke ,
Thanks for the answer.
so one more doubt is,
i have to init barba scripts or javascripts??

**Comment by prabhathAmila** [comment]
remove cache and re-init
