### ISSUE TITLE
iOS: Unhandled Promise Rejection: undefined

### ISSUE THREAD

**Issue by IrishGitty** [luruke/barba.js#314]
Hello, @luruke!

Thank you for your work! I hope we get a fix for my issue. #311  has the same problem but in a much different setup. You guessed a CORS problem in that case. Maybe I have such a problem but I don't know how to fix it because problems in this area are new to me.

Please have a look:

# Problem occurs in
iOS 11.2.1 in Safari 11.0 Mobile

# Setup
* barba.js 1.0.0
* scrollOverflow 0.0.9, a customized version of iScroll 5.2.0 for fullPage.js
* fullPage.js 3.0.2

# Problems' explanation
**In short**:
At one case the links in the mobile menu, which gets an instance of iScroll, don't get triggered and the page is getting reloaded by the browser.

**At length**:
I'm using barba.js and on some pages fullPage.js for it's possibility to have a full page slider. If fullPage.js is active the user navigates through the slides and at some point decides to get back to the first slide there is the option to open the mobile menu and tap on the entry of the current page. The menu gets an instance of iScroll to become scrollable on smartphones because the menu overflows the screen at small screen sizes.

Reaching the first slide using the menu works but if the user now opens the mobile menu again and wants to navigate to a different page the menu closes and the page is getting reloaded by the browser.

# Used code

## iScrolls' section in fullPage.js

```
scrollOverflow: true,
scrollOverflowOptions: {
  bounce: true,
  preventDefault: false,
  scrollbars: false,
  click: true,
},
```

## Additionally initiate iScroll on the mobile menu
```
if (typeof iScrolledMenu == 'undefined') {
  var iScrolledMenu = new IScroll('.mobile-navigation-wrapper', {
    mouseWheel: false,
    scrollbars: false,
    click: true,
    tap: true
  });
}
```

## Prevent triggering of barba.js because of tapping a link and just move to the first slide of the fullPage.js section
```
event.preventDefault();
event.stopPropagation();

fullpage_api.moveTo(1, 0);
```

# Expected output
If the user reached back to the first slide using the mobile menu and taps on a link to a different page barba.js should trigger as always and the page transition should be running.

# Actual output
barbja.js' transition is not being triggered and the browser reloads the page. Furthermore the eponymous `Unhandled Promise Rejection: undefined` is mentioned finally. It appears after the event `onLeave`:

![unhandled_promise_rejection_undefined](https://user-images.githubusercontent.com/25523252/47616630-e297ad80-dabf-11e8-985e-b2891c215db3.png)

Thank you very much in advance for helping us.
~ IrishGitty

**Comment by enableds** [comment]
@IrishGitty , can you shed some light on how this got solved?

**Comment by enableds** [comment]
@IrishGitty , how did you manage to solve this?

**Comment by mrtamagotchi** [comment]
@IrishGitty I'd love to know how you solved this as well!
