### ISSUE TITLE
Backbutton behaviour with lastElementClicked

### ISSUE THREAD

**Issue by Avisseau** [luruke/barba.js#318]
Hello !

I've created a [codepen project](https://codepen.io/m_90/project/editor/XwGLRy) so you can run the code quickly. 

Page transition behaviour works fine when I click on the nav links. 
Unfortunately, I can't get it to work when clicking on back and next button. Could someone advise me on the best way to resolve this issue.

I've set my transition architecture based on this hierarchy 
```
Barba.Pjax.getTransition = function() {

 if( lastElementClicked.className === 'link_detail' && Barba.HistoryManager.prevStatus().namespace === 'main')
    {return MainToDetail;}  
    
    if( lastElementClicked.className === 'link_home' && Barba.HistoryManager.prevStatus().namespace === 'detail')
    { return DetailToMain;} 
    
    if( lastElementClicked.className === 'link_detail' && Barba.HistoryManager.prevStatus().namespace === 'detail')
    {return DetailToDetail;}
 };
```
Thanks in advance :)

**Comment by gfnool** [comment]
I guess it's because you are not providing a default transition, if none of those IF statement it's true you are not returning a transition.
Try to create a "base transition" like a simple fade and use it as a fallback.

**Comment by Avisseau** [comment]
Thanks for your help gnfool,
Issue closed.
