### ISSUE TITLE
Scripts within container are not evaluated

### ISSUE THREAD

**Issue by ZachSaucier** [luruke/barba.js#32]
When a new container is loaded, any `<script>` tags within the container are not evaluated by default. This is because the browser doesn't know to look for JavaScript within the added HTML.

This is not necessarily a bad thing, given it could lead to duplicated code running such as event listeners, but I thought it would be useful to report and discuss.

If you want to run any code within the `<script>` tags, evaluate them by using something like `eval(this.newContainer.querySelector("script").innerHTML);` just before you run [`this.done()`](http://barbajs.org/docs/Barba.BaseTransition.html#.done) on the transition

**Comment by luruke** [comment]
Hi @ZachSaucier, on purpose I don't want the javascript being evaluated when loading a new container.

The idea behind Barba.js and PJAX navigation is that you evaluate your js/css just on the first page where the user lands. 

You have Events and Views made specifically to run code when a new container is loaded.

Anyway, if you want to can easily implement this behavior with something like this:

```javascript
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {
    eval(container.querySelector("script").innerHTML);
});
```

**Comment by johannesmutter** [comment]
To prevent warning for non existing script elements — _(Cannot read property 'innerHTML' of null(…))_
However: eval is evil 😉
```javascript
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {
	var js = container.querySelector("script");
	if(js != null){
		eval(js.innerHTML);
	}
});
```

**Comment by brandlewco** [comment]
do you have an example of this for 2.x

**Comment by moisesmissecart** [comment]
barba.hooks.after((data) => {
    let js = document.querySelectorAll('#main script');
    js.forEach((item) => {
        eval(item.innerHTML);
    });
});

**Comment by frunkad** [comment]
This worked for me in v2


```javascript
barba.hooks.after((data) => {
    let js = data.next.container.querySelectorAll('main script');
    if(js != null){
            js.forEach((item) => {
                console.log(js)
                eval(item.innerHTML);
            });
    }
});
```

**Comment by MrEyelet** [comment]
Where should I attach this code ? I have main.js script where I have imported some other scripts including barba transition.

The script looks like this:
![code](https://user-images.githubusercontent.com/20690376/104853091-f1681600-58fe-11eb-8471-a51b855920f6.png)

But it doesnt help, my main.js script is not reinitialized

**Comment by MrEyelet** [comment]
Ok, in my case I did it like this, and it solved my roadblock

```
    barba.hooks.after(() => {
      const bottomDOM = document.getElementsByTagName("body")[0]
      const newScript = document.createElement("script")
      const oldScript = document.querySelector(".main-script")
      newScript.src = "js/main-dist.js"
      newScript.className = "main-script"
      oldScript.remove()
      bottomDOM.appendChild(newScript)
    })
    ```

**Comment by mudlabs** [comment]
Be good if there was a `data-barba-script` attribute you could attach to inline `<script>` tags. So Barba know there's a script that needs execution. You could make it execute on `newPageReady` by default.

```html
<script data-barba-script>...</script>
```

**Comment by DanDvoracek** [comment]
I use something similar to @MrEyelet but I can't figure out how to make this work. I basically have plenty of inline scripts that I would like to reload after the page transition. The following snippet seems remove and appends scripts back into the html, but it doesn't seem to be reinitialised.. Any idea why ? 

```
barba.hooks.after(function (data) {
      const els = document.querySelectorAll('script');
      for(let i = els.length; i--;) {
          const copy = els[i];
          els[i].remove();
          document.body.appendChild(copy);
      }

  });
```
I'm not really sure of how to reload my inline scripts to be honest. I thought that would do the trick. The lack of documentation about that is frustrating, so any help would be welcome. 

PS: I have scripts like livewire, alpine, gsap etc running and I lose most of them after one transition.

**Comment by ilyasseisov** [comment]
Hi.

here is my Barba code:
 ```
barba.init({
      sync: true,
      transitions: [
        {
          async leave(data) {
            const done = this.async();

            pageTransition();
            await delay(1100);
            done();
          },
        },
      ],
    });
```

Can you please tell, what code and where should I insert it, so other scripts won't break.

Thanks in advance!
