### ISSUE TITLE
Separate widget doesn't load with Barba.js unless that specific page is the first one loaded

### ISSUE THREAD

**Issue by LRode** [luruke/barba.js#322]
Hi everyone, just started using this library today, and so far it has been great!
There is just one issue I am having with it. I am using the following Clutch widget on my Home page:

`<div class="clutch-widget" data-url="https://clutch.co" data-widget-type="2" data-height="90" data-clutchcompany-id="33683"></div>`

The widget loads when the Home page is the first page loaded with Barba, however if the user is first on a separate page, for instance "About", and then selects the Home page, the widget does not load. 

If anyone has any insights for ways I can force that widget to load it would be much appreciated.
Thanks!

**Comment by ammein** [comment]
Yeah , I also encounter the same issue that one of my widget did not load where it requires to run a script. What if the plugins needs a script to re-run and we could not initialize back due to the library limited capabilites.

**Comment by luruke** [comment]
Hello @LRode , you should use the dispatcher events and update your script accordingly.
