### ISSUE TITLE
Barba + Form Post send ( for login )

### ISSUE THREAD

**Issue by Arthur31** [luruke/barba.js#324]
Hi,
First of all, thank you very much for your project ^^' 👍 
So, i have an web application on node.js and i try to use barba on it, it's work pretty fine but between my login page and my logged page, the transition don't take effect. My question is : barba support natively sending form ( in post ) or i need to patch something ? 

Thanks for your reply

Arthur Marty

**Comment by luruke** [comment]
Hello @Arthur31 ,
barba doesn't support forms, and I don't think will be in the scope of the library.

You should handle that manually via ajax.
Cheers
