### ISSUE TITLE
Setting scroll during transition

### ISSUE THREAD

**Issue by ChrisButterworth** [luruke/barba.js#325]
I'm trying to set the scroll position when navigating through the pages, currently using `Barba.BaseCache.set` and `get` to save and retrieve the scroll position and using `window.scrollTo(0, Barba.BaseCache.get('scroll'))` but it doesn't seem to work.

I've place it within my transition, using the `newPageReady` event and even `transitionComplete` but none seem to work.

Any ideas or guidance on this would be great.

**Comment by luruke** [comment]
Hello @ChrisButterworth ,
did you solved this?

The barba cache is currently used just to save URL and their HTML inside, for prefetching/caching.
You should save your scroll position elsewhere
