### ISSUE TITLE
Reload Barba if ajax content

### ISSUE THREAD

**Issue by EightArmsWebmaster** [luruke/barba.js#327]
Thanks so much for an amazing library. 

I have some code that is performing some ajax, independent of Barba:
```
$("#filterSectors li a, #filterTopics li a").click(function(e){
    e.preventDefault();
    var url = $(this).attr("href");
    fetchPosts(url).then(function(data){
      $("#post-list").replaceWith(data.content);
    });
  });
```
Any content with `<a>`'s in it doesn't trigger barba on click. Is there a way I can refresh the links in Barba after load?
```
Barba.Pjax.start();
```
Didn't do the trick unfortunately...

**Comment by EightArmsWebmaster** [comment]
@wiseoldman hey, thanks for responding, but we're referring to the content loaded not triggering Barba, not that click events don't work.

For example, if you load a page, then do something like this:

```
Barba.Pjax.start();
$("body").html('<a href="/page.html">Page</a>');
```

Clicking the `<a>` link won't trigger Barba, as Barba was initialised before the link was added to the page. We're looking for a way to restart Barba, as in remove all the event listeners and re-add them..

**Comment by wiseoldman** [comment]
My bad I misread the question. I'm not sure about this case I haven't experienced that issue before.

I just tried the below code to test it and I'm not having any problems

```javascript
Barba.Pjax.start();

setTimeout(() => {
  const WRAP = document.querySelector('#test');
  const LINK = document.createElement('a');

  LINK.setAttribute('href', 'http://localhost:8888/wp_hundsbaek/ydelse/infrastruktur-miljo/');
  LINK.innerText = 'Test';

  WRAP.appendChild(LINK);
}, 1000);
```

**Comment by luruke** [comment]
@EightArmsWebmaster , that's strange.

Barba event listeners is attached to the `body`, so it should  recognize all the newest link you add in your page.

https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L95

I think you're problem is another.

Are you sure your newest link is eligible for a transition?

https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L240
