### ISSUE TITLE
Get the class or the data attribute of the link that I just clicked

### ISSUE THREAD

**Issue by markendley** [luruke/barba.js#328]
I'm trying to use
`Barba.Pjax.getTransition = function() {
`

So I can have a different Transition for different links.

I know how to get the URL of the link that I just clicked, but is there a way I can get the link that I just clicked as Object.

Ideally I wanna get the class or the data attribute of the link that I clicked.

**Comment by luruke** [comment]
Hello @markendley ,
in the next version this will be by default.

Right now you can hack something like this:

```
var lastElementClicked;
Barba.Dispatcher.on('linkClicked', function(el, event) {
  lastElementClicked = el;
});
```

So you can use `lastElementClicked` and get your HTMLElement just clicked.
