### ISSUE TITLE
Barbajs reloads on second click.

### ISSUE THREAD

**Issue by vdiaza** [luruke/barba.js#348]
Hi!
first of all, I just want to say how good this plugin is and I thank everyone who works on it.
but, I am having an issue, which im not sure why it occurs since I am using almost the same code I used for another site I build couple weeks ago and it didn't happen.

The issue is that on the second click of a link, the page completely reloads. The first click works perfectly though. I have been trying to find the bug,but im not able. I think it has something to do with the transition, since it works fine without it.

Here is my code.

		var webTransition = Barba.BaseTransition.extend({
			start: function(){
				Promise
				.all([this.newContainerLoading, this.pageOut])
				.then(this.pageIn.bind(this));
			},
			pageOut: function(){
				return new Promise(function(resolve, reject) { 
				 	$('.page-transition-outer').removeClass('init finished')
				 	initSlider.kill($)
				 	setTimeout(() => {
				 		resolve();
				 	}, 800)
				 });
			},
			pageIn: function(){
				document.body.scrollTop = 0;
				var $el = this.newContainer
				this.oldContainer.style.display = 'none';
				$el.style.visibility = 'visible';
				$el.style.opacity = 1;
				$('.page-transition-outer').addClass('init finished')
				this.done;
			}
		})

		Barba.Pjax.getTransition = function() {
			return webTransition;
		};

		Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, newPageRawHTML) {
			history.scrollRestoration = 'manual';
				initScripts.global()
				initSlider.init();
				initScripts.ending();
			});

		});
	}

    Barba.Utils.xhrTimeout = 0
    Barba.Pjax.start();
    Barba.Prefetch.init();

I have been trying changing the transition to something simpler, but still no works

Hope you can help, thank you!

**Comment by pavel-mazhuga** [comment]
> The issue is that on the second click of a link, the page completely reloads.
This is not a bug, this is how barba works. Check the source code to get more info about the library.

**Comment by vdiaza** [comment]
@pavel-mazhuga  I probably did not specify well, but the issue appears when I press in different links. I am aware that when you press on the same link that you are on it will force reload the page. But this problem is on any second transition that begins.

**Comment by pavel-mazhuga** [comment]
@vdiaza I see you are not calling this.done function, maybe this is the reason.

**Comment by vdiaza** [comment]
I did call it on the pageIn function

**Comment by DMDc0de** [comment]
@vdiaza if that's still the code you are using, you are not calling `this.done` since you're missing the parenthesis `this.done()`

**Comment by vdiaza** [comment]
@DMDc0de  thank you! that fixed it!
