### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by luruke** [luruke/barba.js#35]
Wondering what is possible to do in order to make the library more accessibile.
Maybe using `ARIA Live Regions` or apply some WCAG guideline?

Open question :)

**Comment by ZachSaucier** [comment]
Using `aria-live` seems like a good idea.

One other improvement would be to allow alternative animations or to turn them off more easily for people who get motion sickness using some user selected setting. Of course, this sort of thing can be done outside of barba in the implementation

**Comment by luruke** [comment]
Done in https://github.com/luruke/barba.js/commit/188de0364c1cc3e046fb389fdd36cb53303800bf
