### ISSUE TITLE
Non-strict equality warning from UglifyJs.

### ISSUE THREAD

**Issue by dblodorn** [luruke/barba.js#36]
First off you've made an amazing library! it's been awesome to work with, and I just launched a project that takes great advantage of it! - http://thekitchennation.com/
Removing the page refresh is a biggie for me.

One small issue is that when I run the production build with my webpack setup i always get this error from the uglify plugin:

    WARNING in ./public/js/app.js from UglifyJs
    Non-strict equality against boolean: != false [./~/barba.js/dist/barba.js:535,0]
    Non-strict equality against boolean: != false [./~/barba.js/dist/barba.js:549,0]

if I go into your build and change (for example - on line 535)
    
    if(e in this.events === false)
to: 
    
    if(e in this.events == false)
no issues - but then I'm going to assume that may cause issues down the road.

**note that there are no problems in dev mode (no minification).**

any thoughts would be appreciated, and more than anything I wanted to bring this to your attention.

**many thanks for you work!**

**Comment by luruke** [comment]
Hi there!
First of all thanks for using Barba.js and for opening an issue 👌
It's always great to see people using barba.js in production 🚀

I'm going to rename the Issue title to a more appropriate one,
I also assume you typed "webkit" instead of "webpack".

It seems a warning from UglifyJs, that I suppose you use after creating the bundle with webpack.

I tried from cli with the verbose mode but I had no warning:
```
uglifyjs barba.js --v
```

I'm using **2.6.3**
```
➜  dist git:(dev) uglifyjs -V
uglify-js 2.6.3
```

Do you use any specific setting for uglify?
Can you show your webpack config?

Cheers

**Comment by luruke** [comment]
Another thing:
It looks like is just a warning, so I assume uglifyjs continue and writes the final file, right?

**Comment by dblodorn** [comment]
Yes the final file does get written. so no problem there.

I have "webpack": "^1.13.1" installed.
which is using uglify-js 2.6.3

here's a link to the webpack config:
https://gist.github.com/dblodorn/d83f25816cc3cc9861f4adddb853e57d

I don't have a specific setting set for uglify.

thanks!

**Comment by luruke** [comment]
Thanks @dblodorn .
I will try to do some tests when I have time.

Anyway the strange thing is that,
from the WARNING it looks like UglifyJs detects a non strict equality (==) and asks for a strict equality (===) and not the inverse!

So, it loos very strange.

Looking at their codebase it's even more clear:
https://github.com/mishoo/UglifyJS2/blob/1840a0b2827efdad64dcabcf44883a34e5ca06cc/lib/compress.js#L2832

**Comment by dblodorn** [comment]
Yes very strange indeed, well I'm glad I could bring this to your attention - for whatever it's worth!
good thing is that it is working.
thanks again @luruke!

**Comment by luruke** [comment]
I did multiple testing but I'm not able to replicate the warning...
If the problem persist try to open an issue to uglify-js

Thanks for the contribution @dblodorn
