### ISSUE TITLE
How to work with transitions and views?

### ISSUE THREAD

**Issue by na86** [luruke/barba.js#37]
Hi @luruke,

thanks for barba.js, it is really impressive! 
i'm moving on with my project using barba, now it's time to add some cool transition between pages. 

i've tried to set some new transition, but they're too faster. Animation isn't smooth or wont showup.
How to work with transition and views, and why views parameter seems to be ignored? 

There's a more complete guide i should follow? 
Could you give me some advice? 
thanks in advance, 

na

**Comment by luruke** [comment]
Hello @na86 ,
By default Barba.js has a default transition `HideShowTransition`, which just hide the old container and show the new one.

If you want to implement a transition you have to write your own `Transition` object.

You can find more information on the documentation:
http://barbajs.org/transition.html

What you mean for "why views parameters seems to be ignored?", can you show a sample code?

**Comment by na86** [comment]
Thanks for the answer!

I didn't know how to use transition inside views. 
page change is too fast to see the transition to the next page. 

what's the relation between views and transition? 
how to use it together? 
btw i will keep on trying! 

(sorry, i can't show you my code now, i left my computer home 👎  :( )

Thank you Luke!

**Comment by luruke** [comment]
`Views` are just helpers to handle JS lifecycle/status.
You don't need to use Views in order to create transition.

For this kind of help / question you can write on the gitter chat:
https://gitter.im/luruke/barba.js

The issue board on github is mainly just for bug of the library / discussion about feature/implementation.

Cheers!
