### ISSUE TITLE
Exemple animation don't triggers correctly

### ISSUE THREAD

**Issue by arnaud-xp** [luruke/barba.js#38]
Hi there !

I'm currently using Barba.js to build my new website (possibly a future exemple to showcase I hope :) ) but I'm struggling using it.
I only tried to play with Transitions using the fade in/out exemple from the documentation, but there is an issue I can't solve : the fadeOut animation displays correctly (my containers slowly fades in 750ms), but the new container is displayed instantly (opacity set to "1") despite the use of .animate().
Here is the fadeIn function I use: 
```js
var AwesomeTransition = Barba.BaseTransition.extend({
        start: function () {
            Promise
                .all([
                    this.newContainerLoading,
                    this.fadeOut()
                ])
                .then(this.fadeIn.bind(this));
        },
        fadeIn: function () {
            var _this = this;

            $(this.oldContainer).hide();

            $(this.newContainer).css({
                opacity: 0
            });
            //The following animation triggers instantly
            $(this.newContainer).animate({opacity: 1}, 750, function () {
                _this.done();
            });
        },
        fadeOut: function () {
            return $(this.oldContainer).animate({opacity: 0}, 750).promise();
        }
    });
```

Hope you guys can provide some help with this :/

Cheers !

**Comment by luruke** [comment]
Hi @arnaud-xp !
Thanks for using Barba.js!

`this.newContainer` element is by default as `visibility: hidden`.
You can check the [documentation](http://barbajs.org/transition.html) for more information.

So, just changing your code to:
```javascript
$(this.newContainer).css({
    opacity: 0,
    visibility: 'visible'
});
```

Should work :)

Feel free to close the ticket if the problem is solved

**Comment by arnaud-xp** [comment]
Hi @luruke !

I just made the change but the problem stays the same :/

Any other clue ?

Cheers !

**Comment by luruke** [comment]
Are you sure?
I just tested the Transition and it works fine.

Just to be clear, the final code should be something like:

```javascript
var AwesomeTransition = Barba.BaseTransition.extend({
    start: function () {
        Promise
            .all([
                this.newContainerLoading,
                this.fadeOut()
            ])
            .then(this.fadeIn.bind(this));
    },
    fadeIn: function () {
        var _this = this;

        $(this.oldContainer).hide();

        $(this.newContainer).css({
            opacity: 0,
            visibility: 'visible'
        });
        $(this.newContainer).animate({opacity: 1}, 750, function () {
            _this.done();
        });
    },
    fadeOut: function () {
        return $(this.oldContainer).animate({opacity: 0}, 750).promise();
    }
});
```

If the problem persist, try to check if you may have some CSS rule that interfere, or try to post a working example somewhere.

Cheers

**Comment by arnaud-xp** [comment]
Hey again !

I double checked your code, we have the same thing. I didn't found any css rules interfering but if you want to have a look, check here => http://350bf6a3.ngrok.io/

Cheers !

**Comment by luruke** [comment]
Hey again

You have a nice CSS rule:

```css
* {
    transition: all ease 0.3s;
}
```

Not only this is a performance killer, but also means that every time jQuery update the opacity tween there is a css transition on it.

Removing it should work.

Let me know

**Comment by arnaud-xp** [comment]
Holy hell I forgot to remove this one :/

Thanks for the help and sorry for the loss of time ^^

Cheers !
