### ISSUE TITLE
Get current and target page URLs

### ISSUE THREAD

**Issue by arnaud-xp** [luruke/barba.js#40]
Hello again,

In the documentation, you wrote that it was possible to customize the getTransition() method to change the transition used by Barba.

```javascript
/**
 * Here you can use your own logic!
 * For example you can use different Transition based on the current page or link...
 */
```

My question is, how can you retrieve the current page URL, as well as the target link clicked by the user within this method ? 

Here is my getTransition() method :
```javascript
Barba.Pjax.getTransition = function () {
        /**
         * @todo: Select transition depending on current page and clicked link
         */
        
        var currentUrl = window.location.href,
            targetUrl = Barba.Utils.getCurrentUrl();

        console.log(currentUrl, targetUrl);
        
        return XporgTransition;
    }
```

It seems that on this example window.location.href is already setted to the next page URL and getCurrentUrl() returns the same value.

Am I handling this badly ? Do you have another method to achieve this ?

Cheers !

**Comment by luruke** [comment]
Hello @arnaud-xp !
Yes, in `.getTransition` the URL is already changed.

You can use `HistoryManager` to retrieve the old page/namespace, you can see the API [here](http://barbajs.org/docs/Barba.HistoryManager.html)

I also refer to you this https://github.com/luruke/barba.js/issues/19#issuecomment-223874845, which may be useful

Feel free to close the issue if you solved this.
Cheers

**Comment by arnaud-xp** [comment]
Hello @luruke !

Thank you for your hint the ```HistoryManager``` will do the trick :) 

I will have a look at the ```View``` object and probably will try to structure the transitions the same as you do. This is a very neat way :)

Cheers !
