### ISSUE TITLE
how to remove link listener

### ISSUE THREAD

**Issue by luglio7** [luruke/barba.js#47]
Hi
How can I remove a "barba pjax listener" from a link ? 
for example in Wordpress i would like to remove the listener from the wp admin bar links, i can not set the barba ignore class to those links so i think the best option is to remove the click listener on those anchors.

**Comment by luruke** [comment]
In your case you may just disable Barba.js Pjax is the user is logged as administrator: 

```
if (window.ADMIN_BAR_VISIBLE) {
      Barba.Pjax.preventCheck = function() {
        return false;
      };
    }
```

Of course you need to pass `window.ADMIN_BAR_VISIBLE` from wordpress;

**Comment by luglio7** [comment]
i don't want to disable the pjax :)

**Comment by luruke** [comment]
Then, if you want to ignore some links you can add the class `.no-barba` on the `a` tag.
Otherwise, you can replace the `Barba.Pjax.preventCheck`, adding your own logic control.


https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L207

**Comment by luglio7** [comment]
Nice, thank you !
