### ISSUE TITLE
get all the html

### ISSUE THREAD

**Issue by luglio7** [luruke/barba.js#49]
last ticket for today :)

I need to have access to the whole html document loaded by ajax, not only the content, is it possible ?

**Comment by luruke** [comment]
Not really at this stage, but i was thinking to add another parameter to the `newPageReady` that will give you the raw XHR response.

What is your requirement at the moment?
If I need some specific information from a new page, I usually add them on `.barba-container` as `data` attribute.

**Comment by luglio7** [comment]
I need an element outside the container which i want to replace page by page. Sadly this element can not be included inside the container.

the raw xhr response would be awesome.

**Comment by luruke** [comment]
For the moment you can do something like this:

```javascript
var originalFn = Barba.Pjax.Dom.parseResponse;

Barba.Pjax.Dom.parseResponse = function(response) {
 // do your stuff with the response
 console.log(response);
 return originalFn.apply(originalFn, arguments);
};
```

In this way you replace barba.js internal function with a custom one, where you can do whatever you want, and at the end call the original function, so that the internal behaviour stays the same.

All the methods in barba.js are public, so you can easily hack and add your own stuff :)

**Comment by luglio7** [comment]
Yea, thanks.

**Comment by rockethouse** [comment]
Hi, I'm having the same issue as I want to manipulate the new page before adding it to the DOM.

Issue I am having is I'm also using a transition based off your examples which is using setTimeouts, so the changes i'm making to the new response are happening before the timeout (on the old page) and then lost when the new page loads. 

Am I doing something wrong?

**Comment by luruke** [comment]
Hello @rockethouse, on the new version of barba you can get the full html via the `newPageReady` event.

Anyway if you want to change the dom in a specific transition, it should be pretty easy. You just need to modify the newContainer before showing it.

Can you share a demo/code to better understand you problem?

**Comment by rockethouse** [comment]
It's a bit of a mess at the moment, but here you go. You can see where I had to put a delay on the body class change based on what page we're on, using a setTimeout to match the delay further down...

I've also done another timeout for a css: top hack on ('.wrap .content') using your example above, but yeah it seems I can do it in either location.

Is there a better way to do all this? ie by using views?

Cheers

```javascript
Barba.Pjax.start();

Barba.Dispatcher.on('initStateChange', function(HTMLElement, MouseEvent) {
    $('nav li').removeClass('active');
});

Barba.Dispatcher.on('newPageReady', function(currentStatus, newPageRawHTML) {
    var link = currentStatus.url.split(window.location.origin)[1].substring(1); // get path of current page
    
    if (link === '') {
        $('nav li:first-child').addClass('active'); // home page active hack
    }
    
    link = link.split('/'); // clean up the link
    
    $('nav li.menu-' + link[0]).addClass('active');
    $('nav li.menu-' + link[0] + ' ul.sub-menu li.menu-' + link[1]).addClass('active');
    
    $('.barba-container').removeClass('fade-in'); // for some reason this doesn't get removed in the transition
    
    $('.flexslider').flexslider({
        controlNav: false,
        directionNav: false,
        slideshow: true,
        selector: ".slides > div",
        slideshowSpeed: 4000
    });
    
    window.setTimeout(function(){
        if (link[0] === 'positions') {
            $('body').addClass('alt');
        }
        else {
            $('body').removeClass('alt');
        }
    },1000); // Do things after 1 second
    
    window.setTimeout(function() {
        // console.log('starting slideshow again');
        headlineSlideshow();
    }, 2000); // Do things after 2 seconds
    
    // console.log(newPageRawHTML);
    
});

var originalFn = Barba.Pjax.Dom.parseResponse;

Barba.Pjax.Dom.parseResponse = function(response) {
    // do your stuff with the response
    
    setTimeout(function() {
        var newHeight = $('.main').height();
        var pageHeight = $('.wrap.container').height();
        
        if (newHeight > pageHeight) {
            $('.wrap .content').css('top', '0'); // absolute positioning hack depending on content size, either top or bottom. eh
        }
    }, 1400); // do this mid-transition but before fadeOut - so 100ms before? seems to work...
    
    return originalFn.apply(Barba.Pjax.Dom, arguments);
};


var FadeTransition = Barba.BaseTransition.extend({
    start: function() {
        Promise.all([this.newContainerLoading, this.fadeOut()]).then(this.fadeIn.bind(this));
    },
    
    fadeOut: function() {
        $(this.oldContainer).toggleClass('fade-out');
        // console.log('fading out');
        
        return new Promise(function(resolve, reject) {
            window.setTimeout(function() {
                resolve();
                //console.log('faded out');
            }, 1500);
        });
    },
    
    fadeIn: function() {
        // console.log('fading in');
        var _this = this;
        var $el = $(this.newContainer);
        
        $(this.oldContainer).hide();
        $el.toggleClass('fade-in',1500).promise().done(function(){
            _this.done();
        });
    }
});

Barba.Pjax.getTransition = function() {
    return FadeTransition;
};
```

**Comment by luruke** [comment]
Hello @rockethouse, you should probably have a look to transitionCompleted event:
http://barbajs.org/events.html

**Comment by mahfujcse** [comment]
Hi @luruke,

Barba.js not working with WordPress prettyPhoto popup!
can you help me?

Thanks
Mahfuj
