### ISSUE TITLE
Update body class?

### ISSUE THREAD

**Issue by mikespainhower** [luruke/barba.js#51]
Is it possible to update the body class between transitions?

**Comment by mtreik** [comment]
Yes! Use this:

var body = document.querySelector('body');
body.classname = "The new class";

**Comment by mikespainhower** [comment]
Thanks @mtreik.

To clarify, I'd like to pull the body classes from the new URL into the existing DOM (outside of the Barba container).

**Comment by luruke** [comment]
Hi @mikespainhower!
Have a look to this issue: https://github.com/luruke/barba.js/issues/49

**Comment by mikespainhower** [comment]
Ah, thank you!

**Comment by mtwalsh** [comment]
I'm still getting to grips with barba.js but this code seems to be working in terms of swapping the `<body>` classes over on page transition (using jQuery):

```JavaScript
    // Update body classes by replacing the barba.js internal function
    // See: https://github.com/luruke/barba.js/issues/49#issuecomment-237966009
    var originalFn = Barba.Pjax.Dom.parseResponse;
    Barba.Pjax.Dom.parseResponse = function(response) {
        // Because jQuery will strip <body> when parsing a HTML DOM, change
        // <body> to <notbody>, then we can grab the classes assigned to it
        // See: http://stackoverflow.com/a/14423412/4081305
        response = response.replace(/(<\/?)body( .+?)?>/gi, '$1notbody$2>', response);
        // Get the classes on the <notbody> element
        var bodyClasses = $(response).filter('notbody').attr('class');
        // Apply the classes to the current body
        $('body').attr('class', bodyClasses);
        // Call the original barba.js function
        return originalFn.apply(Barba.Pjax.Dom, arguments);
    };
```

**Comment by luruke** [comment]
@mtwalsh 👍 

In the next version of barba, i'm planning to add a new argument to the `newPageReady` that returns the raw HTML, so you will not need to replace `.parseResponse`.

Stay updated :)

**Comment by mtwalsh** [comment]
@luruke That sounds great, thanks for sharing your work on barba.js, it's awesome!

**Comment by hartey11** [comment]
Hi, Thanks for the fix. Is there anyway to make sure it only changes the body classes once the new page has loaded? I'm working on a new site and if you click a link that's already cached the body classes change before the page transition is complete and you can see the styling removed from the page?

**Comment by mtwalsh** [comment]
@hartey11 Yes, you should be able to assign the body classes to a global variable, which you then apply later on.  For example:
 
```JavaScript
    // Create a global variable to store the bodyClasses
    var bodyClasses;
    // Update body classes by replacing the barba.js internal function
    // See: https://github.com/luruke/barba.js/issues/49#issuecomment-237966009
    var originalFn = Barba.Pjax.Dom.parseResponse;
    Barba.Pjax.Dom.parseResponse = function(response) {
        // Because jQuery will strip <body> when parsing a HTML DOM, change
        // <body> to <notbody>, then we can grab the classes assigned to it
        // See: http://stackoverflow.com/a/14423412/4081305
        response = response.replace(/(<\/?)body( .+?)?>/gi, '$1notbody$2>', response);
        // Get the classes on the <notbody> element
        bodyClasses = $(response).filter('notbody').attr('class');
        // Call the original barba.js function
        return originalFn.apply(Barba.Pjax.Dom, arguments);
    };
```

And then later on...

```JavaScript
// Apply the classes to the current body
$('body').attr('class', bodyClasses);
```

**Comment by hartey11** [comment]
Thanks that worked!

**Comment by nicooprat** [comment]
Got it working with events too:

````js
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, newPageRawHTML) {
  var response = newPageRawHTML.replace(/(<\/?)body( .+?)?>/gi, '$1notbody$2>', newPageRawHTML)
  var bodyClasses = $(response).filter('notbody').attr('class')
  $('body').attr('class', bodyClasses)
})
````

**Comment by spidoche** [comment]
@nicooprat events works well, thanks.

**Comment by antoinejaunard** [comment]
Hi,
I would like to update a class of antoher element than the body, like this:
```
<div class="page page--home">
  <div id="barba-wrapper">
    <div class="barba-container">
      …
    </div>
  </div>
</div>
```

```
<div class="page page--article">
  <div id="barba-wrapper">
    <div class="barba-container">
      …
    </div>
  </div>
</div>
```
How can i write it ?
Thanks

**Comment by 9585999** [comment]
@nicooprat I use barba.js with Wordpress, and this code really works, but the problem is that the classes change before the animation starts, which creates certain difficulties when working, if in css there are dependencies on body classes ...

**Comment by nicooprat** [comment]
This event should be fired right between the two transitions. So the class should change when no content is visible. I think there is an issue in your transition declaration, are you using Promises to ensure the In transtion starts when the Out has finished (and the content is loade)? Can you try with the basic fadeInOut transition in the docs?

**Comment by 9585999** [comment]
@nicooprat Hi, thanks for the feedback.

I use the base transitions from the documentation, here is an example of the code that I have at the moment

```js
    // •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
    // Barba.js
    // •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
    Barba.Pjax.Dom.wrapperId = 'wrap-main';
    Barba.Pjax.Dom.containerClass = 'wrap-main-container';

    $('a[href^="' + getHomeUrl + '"]').each(function() {
      this.addEventListener("click", (event) => {
        event.preventDefault();
      });
    });

    Barba.Pjax.start();
    Barba.Prefetch.init();

    let FadeTransition = Barba.BaseTransition.extend({
      start: function() {
        Promise
          .all([this.newContainerLoading, this.fadeOut()])
          .then(this.fadeIn.bind(this));
      },

      fadeOut: function() {
        return $(this.oldContainer).animate({
          opacity: 0,
        }).promise();
      },

      fadeIn: function() {
        let _this = this;
        let $el = $(this.newContainer);

        $(this.oldContainer).hide();

        $el.css({
          visibility: 'visible',
          opacity: 0,
        });

        $el.animate({
          opacity: 1,
        }, 500, 'linear', function() {
          _this.done();
        });
      },
    });

    Barba.Pjax.getTransition = function() {
      return FadeTransition;
    };

    Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, newPageRawHTML) {
      $('a[href="' + currentStatus.url + '"]').each(function() {
        this.addEventListener("click", (event) => {
          event.preventDefault();
        });
      });

      let response = newPageRawHTML.replace(/(<\/?)body( .+?)?>/gi, '$1notbody$2>', newPageRawHTML);
      let bodyClasses = $(response).filter('notbody').attr('class');
      $('body').attr('class', bodyClasses);
    });
```

**Comment by nicooprat** [comment]
Ok first thing you could rewrite you first block like this:

```js
$('body').click('a[href^="' + getHomeUrl + '"]', (event) => {
  event.preventDefault()
})
```

This way, the listener is alway live on body and check if element matches when the event happens. So it would automatically works on newly added elements without anything more. And you can remove all semi-colon too :)

Back to your issue, [as per the docs](http://barbajs.org/events.html) it should work... Maybe @luruke will have a better idea of what's going on here?

**Comment by 9585999** [comment]
@nicooprat Yes, thanks, your version of the code I like more.

Regarding the problem, I added styles for clarity and increased the animation time to 1s, below you can see how it works.

```scss
.archive #wrap-main {
  background: red;
}
```

![kapture 2017-10-08 at 14 47 19](https://user-images.githubusercontent.com/16165904/31316536-21c5391c-ac38-11e7-849b-4a8d7e445769.gif)

**Comment by 9585999** [comment]
The event is triggered as soon as a new container is ready, and judging by the name 'newPageReady' it should be ...

I tried to delay the event via setTimeout (), but this solution does not work so long as the delay sometimes slips ...

Can anyone have any ideas on how to stick this event between the old container and the new container will start to appear?

**Comment by nicooprat** [comment]
It's pretty weird, my code is almost the same as yours and works as expected. I agree that the name `newPageReady` is a bit confusing!

Could you try to set some `debugger` in your code to see what's going on? For example, add a breakpoint at the start of the event, and check in the Elements tab in the inspector to see what the HTML looks like at this moment. In my case, I see this:

![capture d ecran 2017-10-09 a 14 06 47](https://user-images.githubusercontent.com/645641/31337342-2139b6f8-acfb-11e7-903e-4fc3f27213b3.png)

It's at this precise moment that the body classes should be swapped.

Or you could create a Codepen with a small test to reproduce the issue?

**Comment by 9585999** [comment]
@nicooprat I created [codepen](https://codepen.io/9585999/project/full/ZQwnmg/), the behavior is the same ...

**Comment by nicooprat** [comment]
I'm really confused, indeed the event seems to be fired as soon as the content has been loaded, even if the Out transition hasn't finished. But it doesn't work like this on my project. I really think Barba API should be cleaned up...

Anyway, got this working: https://codepen.io/nicooprat/project/editor/ZMYGVe (have a look at `newBodyClasses`). It's really dirty but can't think of anything better at the moment.

Btw, you shouldn't have to preventDefault on links as Barba does it already.

**Comment by 9585999** [comment]
@nicooprat I also thought about this option, but Linter does not miss it ...

![img 2017-10-09 16 35 33](https://user-images.githubusercontent.com/16165904/31340777-ec5d5f24-ad0f-11e7-9bf8-af5a3a7263ac.PNG)

and about the links thank you, I did not know that Barba already forbids himself.

In general while as a temporary solution hung the body_class on .wrap-main-conteiner ...

**Comment by nicooprat** [comment]
I actually defined the variable at the beginning of the file in order to be globally scoped ;)

**Comment by 9585999** [comment]
@nicooprat yes, indeed, I did not notice :)

**Comment by cfxd** [comment]
Hello, I was wondering if anyone was able to get this working so that the new `body` classes are added after the fade out transition without using a `setTimeout()`?

**Comment by OksanaRomaniv** [comment]
Hello, how can I achieve this with Barba v2?

**Comment by dangelion** [comment]
Same for me, how to do this with Barba v2?

**Comment by dangelion** [comment]
I'm doing this with Barba v2

```
    barba.hooks.afterLeave((data) => {
      // Set <body> classes for "next" page
      var nextHtml = data.next.html;
      var response = nextHtml.replace(/(<\/?)body( .+?)?>/gi, '$1notbody$2>', nextHtml)
      var bodyClasses = $(response).filter('notbody').attr('class')
      $("body").attr("class", bodyClasses);
    });
```

Don't know if it's the best way but it seems work.

**Comment by julianfox** [comment]
@dangelion work well in my case and the code look clean to me, thanks :-)

**Comment by timotheus0106** [comment]
thanks @dangelion works great for me too.

**Comment by MarcGaumont** [comment]
> Got it working with events too:
> 
> ```js
> Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, newPageRawHTML) {
>   var response = newPageRawHTML.replace(/(<\/?)body( .+?)?>/gi, '$1notbody$2>', newPageRawHTML)
>   var bodyClasses = $(response).filter('notbody').attr('class')
>   $('body').attr('class', bodyClasses)
> })
> ```

Thanks this works perfect.

**Comment by djave-co** [comment]
To combine some of the above, a jQuery-less, Barba v2 version:

```barba.hooks.afterLeave((data) => {
  // Get body class from incoming page
  let regexp = /\<body.*\sclass=["'](.+?)["'].*\>/gi,
    match = regexp.exec(data.next.html);
  if (!match || !match[1]) {
    // If no body class, remove it
    document.body.setAttribute("class", "");
  } else {
    // Set the new body class
    document.body.setAttribute("class", match[1]);
  }
});
```
