### ISSUE TITLE
Two containers

### ISSUE THREAD

**Issue by CreativeSeo33** [luruke/barba.js#56]
How i can to make two containers:
```
<div id="barba-wrapper">
  <div class="barba-container">
    content
  </div>
 <div>
   ....some content
 </div>
 <div class="barba-container">
    content
  </div>
</div>
```

**Comment by luruke** [comment]
Hi there, at this stage barba.js do not supports multiple container per page.

Can you explain better your needs?

Cheers

**Comment by CreativeSeo33** [comment]
Sorry for my english.
On my website http://www.lustra-gus.ru/hrustalnye-lyustry/ , i need reload goods and <h1>, when using sorting and filter. But I do not have to reload the filter.
I need:
```
<div id="barba-wrapper">
  <div class="barba-container">
    <h1>Heading</h1>
  </div>
 <div class="filter">  
 </div>
 <div class="barba-container">
    goods
  </div>
</div>
```

**Comment by CreativeSeo33** [comment]
Sory for my english.
On my website http://www.lustra-gus.ru/hrustalnye-lyustry/ i need reload goods and h1, when using sorting and filter. But i do not have to reload filter.
I need:
```
<div id="barba-wrapper">
  <div class="barba-container">
    <h1>Heading</h1>
  </div>
 <div class="filter">  
 </div>
 <div class="barba-container">
    goods
  </div>
</div>
```

**Comment by luruke** [comment]
I guess it would be easier in your case to handle everything manually with ajax
