### ISSUE TITLE
Can I use barbajs for a widget/component on page

### ISSUE THREAD

**Issue by pgangwani** [luruke/barba.js#57]
Hello @luruke , I have requirement to create wizard kind of structure in widget which has nested steps, so after 1st step is validated (form filled and call for 2nd screen content) and content available for 2nd step , I would be transitioning to second step and so on..

Tech stack : 
I am using Backbonejs for that component with handlebar for templating.

Can I create that widget using barbajs, difference may be I would be generating content based on ajax call(json) for templating . Hope you are with me till now.

**Comment by luruke** [comment]
@pgangwani - I guess it would be easier for you to handle the steps manually via ajax instead of using Barba.js
