### ISSUE TITLE
Abort a transition

### ISSUE THREAD

**Issue by nosp4mSnippets** [luruke/barba.js#60]
Hi, 

I'm doing my first project using Barba.js and I love it so far.

I was wondering if there is a way to abort a transition during one of the enter/leave phases ? 
For instance : 
```
onLeave: function( ) {
      if( somethingIsWrong ){
           Barba.stop( ); // something like that !
     }
} 
```
Many thanks

**Comment by luruke** [comment]
Hi @nosp4mSnippets .

You can't at the moment stop the transition (mostly because barba.js doesn't know how you implemented your transition).

You can check if a Transition is in progress with `Barba.Pjax.transitionProgress`, then you should implement the 'blocking' transition on your own.
