### ISSUE TITLE
preventCheck when trying to browser to a PDF (or other file types?)

### ISSUE THREAD

**Issue by jonnyscholes** [luruke/barba.js#61]
First off _love_ this project. So thank you!

What do you think about having `preventCheck` return false if trying to browse to file types we can reasonably expect will break the application - for example PDFs or .doc/x files? I know it is fairly trivial to overwrite the `preventCheck` function (and have done so so far) however it strikes me as a scenario that would break _most_ implementations of Barba and so perhaps it could be handled within the framework?

The `.no-barba` is the most obvious solution to this - however a lot of links to files are input via richtext and many CMS' don't have the liberty of easily adding/removing classes to those links.

Happy to submit a PR for this if it's a good idea - otherwise overwriting works for my immediate needs.

**Comment by luruke** [comment]
Hey @jonnyscholes !
I could add a regex/file extension on the href url, but I don't thing is a good idea.
My doubt is that an URL that ends with .pdf that doesn't necessary means that the file is a pdf.

What is your idea?

(By the way In the next version I'll also make sure to support the download attribute)

**Comment by jonnyscholes** [comment]
Supporting the download attribute would be awesome! (I would be happy to submit a PR for this btw). But doesnt help many users who are stuck with things like TinyMCE which dont (easily) allow adding of attributes/classes to inserted anchor links. For example default Wordpress websites dont allow any changes of anchor HTML at all.

Technically someone could have a link that ends in .pdf (or other file extensions) that returns a valid HTML page - but I would have thought they would be the exception, and not the rule. Most urls that end in `.pdf` are a pdf download seeing is a very widely recognized format - along with others like `doc` and `docx`. 

From my point of view it would be more reasonable for people that are returning html from a `.pdf` endpoint to override the `preventCheck` method than those that are not - as it is a pretty odd thing to do.

We could implement it in a way that is configurable so users can override the formats by doing something like:

`Barba.Pjax.start({ignoreFiles: ['pdf', 'doc', 'exe', 'dmg']})`

(or similar)

**Comment by luruke** [comment]
Thanks @jonnyscholes .
I'll think about it.

Maybe another solution could be to check the HTTP Content-Type header.

Thanks for the issue!

**Comment by luruke** [comment]
Added support for download attribute in the new version.
https://github.com/luruke/barba.js/commit/965a2668fe29eec90014d507529d75de7064a521

**Comment by jonnyscholes** [comment]
I think between the `download` attribute and the docs including how one would do this (which it does [here](http://barbajs.org/faq.html)) this issue can be closed. I'm more than satisfied as a user :)
