### ISSUE TITLE
Using Barba with keyboard trigger links

### ISSUE THREAD

**Issue by loximoz** [luruke/barba.js#62]
Hi,
I try to manipulate my actual links with an accessibility on keyboard. The trigger on the click is detect by javascript, but Barbajs not take it for make the transition.

There is a possibility to launch Barba with this kind of navigation ?

Yhanks a ot by advance !

**Comment by luruke** [comment]
Hi @loximoz 
It should work with no problem using the keyboard.
You can try on http://barbajs.org for example.
