### ISSUE TITLE
How to show a progress bar during page transition

### ISSUE THREAD

**Issue by ershad989** [luruke/barba.js#63]
Hi,

Barba.js is really awesome thank you so much for making and sharing it ..

I have this question and I'll very much appreciate it if you give an answer, I am not very good at JavaScript though .. just a newbe

I want to show a progress bar during the the page change right after the old container fades out and before  the new container fades in, which shows the the loading progress. something like pace.js

Is that possible?

Thanks ..

**Comment by ershad989** [comment]
Actually one of the examples have a progress bar, this one:

http://www.poigneedemainvirile.com/

If you could make a demo with a progress bar that would be great ..

**Comment by luruke** [comment]
@ershad989 : I don't have a demo at the moment but it should be pretty easy to add a loader inside the transition.

**Comment by ershad989** [comment]
Thank you for the reply,

I should be easy but I dont really know how to insert a PROGRESS BAR between transitions

**Comment by Joel-Mercier** [comment]
Hey @ershad989 you could use [Pace JS](http://github.hubspot.com/pace/docs/welcome/) which automatically detects when a new page is loading and displays a progress bar.
