### ISSUE TITLE
Real slow connections !

### ISSUE THREAD

**Issue by ershad989** [luruke/barba.js#64]
I was testing the page transition and I set the connection speed on Chrome Dev Tools to 2kb/s
fadeOut animation took place and after a while eventually in the console there was this message:

```
barba.min.js:1 XHR failed loading: GET "http://localhost:9001/index-bar-menu-dropdown.html".
Uncaught (in promise) undefined
Uncaught (in promise) undefined
```

after that the page did not load at all, I had to remove the throttling
then the page loaded
when I clicked on Back button of the browser the addres in the addresbar changed but the page did not change to previous one
I had to refresh
So what is this?! is it an error? a bug or the problem is from my code?
sorry it looks like telling a story but I didn't fine a better way to discribe the situation, here is the code that I use:

```javascript
    document.addEventListener("DOMContentLoaded", function() {
        var FadeTransition = Barba.BaseTransition.extend({
            start: function() {
                Promise
                    .all([this.newContainerLoading, this.fadeOut()])
                    .then(this.fadeIn.bind(this));
            }

            fadeOut: function() {
                var deferred = Barba.Utils.deferred();

                TweenMax.to(this.oldContainer, 0.3, {
                    opacity: 0,
                    onComplete: function() {
                        deferred.resolve();
                        $(this.oldContainer).remove();
                        console.log("fade-out");
                    }
                });

                return deferred.promise;
            },

            fadeIn: function() {
                var _this = this;
                var $el = $(this.newContainer);

                TweenMax.set($(this.oldContainer), { display: "none" });
                TweenMax.set($el, { visibility: "visible", opacity: 0, });

                TweenMax.to($el, 0.3, {
                    opacity: 1,
                    onComplete: function() {
                        _this.done();
                        console.log("done");
                    }
                });
            }
        });

        Barba.Pjax.getTransition = function() {
            return FadeTransition;
        };

        Barba.Pjax.Dom.containerClass = "page-contents";
        Barba.Pjax.Dom.wrapperId = "page-contents-wrapper";
        Barba.Prefetch.init();
        Barba.Pjax.start();
    });
```

**Comment by luruke** [comment]
Hi @ershad989 , I haven't had time yet to test it.
I'll let you know.

**Comment by luruke** [comment]
Hi @ershad989 I did different testing but I can't replicate your issue.
Let me know if you have still problems with the latest version.

Also I want to remind you that is possible to change the default xhr timeout which is 5second.
http://barbajs.org/docs/Barba.Utils.html#.xhrTimeout

**Comment by alexcarpenter** [comment]
@luruke I seem to be experiencing the same issues listed above. @ershad989 did you find a solution?

**Comment by coolemur** [comment]
Hi,

I have similar issue. Testing barba transitions with slow 3g connections. 

this.newContainerLoading hangs.

I even tried to increase xhrTimeout from 5000 to 60000 . Same problem remains.
