### ISSUE TITLE
Trigger click event with jquery - no transition happens

### ISSUE THREAD

**Issue by 3oax** [luruke/barba.js#66]
When I trigger a click event on a link with jquery, not transition and pageload happens.
workaround? do i have to trigger another event?
i tried Barba.Dispatcher.trigger('linkClicked', $el.find('.link').get(0)); but with no effect.
$el.find('.link').trigger('click') no effect also.

**Comment by luruke** [comment]
Hi @3oax ,
If I understood correctly you want to fire a transition/page change with JS, right?

You can do that with `Barba.Pjax.goTo` - http://barbajs.org/docs/Barba.Pjax.html#.goTo

Is that what you want to achieve?

**Comment by 3oax** [comment]
yes, exactly. it works, but with an exception:
the link specific transition is not fired.

**Comment by banago** [comment]
@luruke I think `Barba.Pjax.goTo` should be documented in `readme` because it's quite important. Thanks.

**Comment by luruke** [comment]
@banago 👍 

(Feel free to crate a pull request with it! I'm super busy in this period!)
