### ISSUE TITLE
Trouble understanding where to add Views related js

### ISSUE THREAD

**Issue by thinksitdo** [luruke/barba.js#69]
Hi,

Thanks for the library. It;s working pretty well on a website I'm building with Craft. I have a problem with the views. I'm trying to get a class added to my homepage nav through views. My container has a namespace of 'homepage' and I have this code:

```
var Homepage = Barba.BaseView.extend({
  namespace: 'homepage',

  onEnterCompleted: function() {
      $("logo-black").addClass("invert-nav-bar");
      $(nav).addClass("invert-nav-bar");
  }
});
Homepage.init();
```

But, I'm not sure where to put it in my transition script (a separate file that defines the barba transitions loaded after barba.js). Your documentation recommends putting it before Pjax.start(). But this results in the page fully refreshing and not transiting. The rest of my script is:

```
// Barba.js
    Barba.Pjax.start();
    Barba.Prefetch.init();


    var FadeTransition = Barba.BaseTransition.extend({
  start: function() {

    /**
     * This function is automatically called as soon the Transition starts
     * this.newContainerLoading is a Promise for the loading of the new container
     * (Barba.js also comes with an handy Promise polypill!)
     */

    // As soon the loading is finished and the old page is faded out, let's fade the new page
    Promise
      .all([this.newContainerLoading, this.fadeOut()])
      .then(this.fadeIn.bind(this));
  },

  fadeOut: function() {
    /**
     * this.oldContainer is the HTMLElement of the old Container
     */

    return $(this.oldContainer).animate({ opacity: 0 }).promise();
  },

  fadeIn: function() {
    /**
     * this.newContainer is the HTMLElement of the new Container
     * At this stage newContainer is on the DOM (inside our #barba-container and with visibility: hidden)
     * Please note, newContainer is available just after newContainerLoading is resolved!
     */

    var _this = this;
    var $el = $(this.newContainer);

    $(this.oldContainer).hide();

    $el.css({
      visibility : 'visible',
      opacity : 0
    });

    $el.animate({ opacity: 1 }, 400, function() {
      /**
       * Do not forget to call .done() as soon your transition is finished!
       * .done() will automatically remove from the DOM the old Container
       */

      _this.done();
    });
  }
});

/**
 * Next step, you have to tell Barba to use the new Transition
 */

Barba.Pjax.getTransition = function() {
  /**
   * Here you can use your own logic!
   * For example you can use different Transition based on the current page or link...
   */

  return FadeTransition;
};
```

**Comment by luruke** [comment]
Hello @thinksitdo .
Are you sure you don't have JS errors?
```javascript
      $(nav).addClass("invert-nav-bar");
```

Where `nav` is declared?

**Comment by thinksitdo** [comment]
Copy and pasting without thinking. You're right it was supposed to be looking for #nav. It now works fine.

I have one more issue. How do you get a <script> inside the `.barba-container` to run when it has loaded. Previously it would be triggered by a page load. Now it fails to load.
```
<script type="text/javascript">
                          var playerInstance = jwplayer("featured{{feature.id}}");
                          playerInstance.setup({
                            file: "{{feature.getUrl}}",
                            width: "100%",
                          height: "40px",
                          skin: {
                            name: "five"
                            }
                          });
                          </script>
```

**Comment by luruke** [comment]
@thinksitdo You have to use Barba.js events for that.
Or you can use a Barba View.

You can check the documentation on barbajs.org for more info.

**Comment by shanewmurphy** [comment]
Hi Folks,
Hope we can help!! 
Here's my logic:
I'm using anime.js to create a transition animation like so:

var slideReveal = anime.timeline();
slideReveal
  .add({
    targets: '#slideReveal .blindA',
    scaleX: [1, 0],
    easing: "easeInQuad",
    duration: 1000
  });

I'm using (I think) Views to trigger the transition like so when nav another page.

var Home = Barba.BaseView.extend({
  namespace: 'home',
  onEnter: function () {
  },
  onEnterCompleted: function () {
  },
  onLeave: function () {
    document.body.getElementById.add('#slideReveal .blindA');
  },
  onLeaveCompleted: function () {}
});

Home.init();

Result it ain't working! The anime.js animation I created works when the dom (or page refresh) is downloaded but I don't want it to work then. I want it animation when navigation/trigger to other site pages.
