### ISSUE TITLE
Localstorage cache

### ISSUE THREAD

**Issue by luruke** [luruke/barba.js#7]
Implement a more persisent cache system with `localstorange` and with expiration timeout.

**Comment by jarrydfillmore** [comment]
+1 here too!

**Comment by svbackend** [comment]
+1

**Comment by hendrysadrak** [comment]
+1

**Comment by luruke** [comment]
I've been thinking about it and at this stage I don't see any real advantages using it.
Adding this feature could lead to different bugs and unexpected behaviour and I prefer not implement it now.

Of course is someone want to play with it, feel free to submit a pull request :)
