### ISSUE TITLE
Links with svgs = Hard refresh

### ISSUE THREAD

**Issue by mrdoinel** [luruke/barba.js#70]
I was wondering why clicking some links was doing an hard refresh instead of loading the page via barba.js. Here is the link : 

```
<a href="/homepage">
<svg class="icon--logo " role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/images/sprites.svg#logo"></use></svg> <span>Logo name</span>
</a>
```

The linkClicked event is not triggered.

If I replace this code by a regular a:href element with some text I dont have any issues anymore.

**Comment by mrdoinel** [comment]
Wow it seems this point has been fixed in latest release!! Sorry for the noise!! Great job on this library.

**Comment by luruke** [comment]
Actually I just checked and this is still a bug.
The problem is that, clicking on the `<use>` tag, the `xlink:href` is detect as the final link.
https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L193

But then the link is ignored because
https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L266

I'll think about a solution!

**Comment by luruke** [comment]
I should maybe discard the link on all the `use` tag... hope it make sense

**Comment by mrdoinel** [comment]
Yes, I just double check by upgrading to version 1.0.0 and this is still an issue.
Maybe the script should find the closest parent that is a `<a>`.

**Comment by andershopkins** [comment]
A non-JS workaround could be to set  `pointer-events: none` on the `<svg`> element.

**Comment by docherty** [comment]
Has anyone got this to work using @andershopkins technique or something else? I'm using v1.0.0 and I've tried using `pointer-events: none` on the relevant parts of the navigation svg but I can't capture the click.

I'm thinking the solution might be to use non `<a>` elements and just recreate the "clicking the link" event manually but that seems a shame when I suspect Barba does what I want and I'm just missing something obvious (to you!). Any ideas?

**Comment by blimpmason** [comment]
Just realized issue #174 is due to this bug. What's really strange is that on my test project it only happens intermittently:

http://twelvenyc.grossdevelopment.net/

**Comment by blimpmason** [comment]
This article actually explains why it could happen intermittently — it depends on whether the click event target is the wrapping anchor tag, svg, or use element:

https://css-tricks.com/slightly-careful-sub-elements-clickable-things/
