### ISSUE TITLE
True external link blocked?

### ISSUE THREAD

**Issue by psntr** [luruke/barba.js#71]
First of all thank you for written up this nice plugin.

I manage to find a way to make it work with my wordpress template. Nevertheless, I bump onto a issue when a link is external, I have a blog entry, that has a link to let's say google.com, but when I click on the link, the browser returns this message:

Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://www.google.com/' cannot be created in a document with origin 'http://trill.ch' and URL 'http://trill.ch/tk/projects/sixth-project-title/'.

any ideas?

Thank you in advance for reading my post.

**Comment by psntr** [comment]
Ok well, it seems like the preventCheck is not preventing automatically my links, so at the end of my scripts, if add it manually after the Pjax.start(); it works `Barba.Pjax.start();
		
	if (!window.history.pushState){
	Barba.Pjax.preventCheck = function (evt, element) {
            return false;
    };}	
	//Check if it's the same domain
	if (window.location.protocol !== links.protocol || window.location.hostname !== links.hostname){
	Barba.Pjax.preventCheck = function (evt, element) {
            return false;
    };}	`

**Comment by luruke** [comment]
Hi @psntr ,

Why are you replacing `Barba.Pjax.preventCheck`?

**Comment by psntr** [comment]
Oh… correct me if I'm wrong, is it because in my code I had:

`Barba.Pjax.originalPreventCheck = Barba.Pjax.preventCheck;
    Barba.Pjax.preventCheck = function (evt, element) {

        if ($('#barba-container').hasClass("logged-in")) {
            return false;
        }
        return true;

    };
`

And by doing, so, as you said, I replaced the Barba.Pjax.preventCheck default behaviour?

I just wonder then, how to disable barba on wordpress once logged-in, you mentionned something on another post but I don't get what you meant by passing this `window.ADMIN_BAR_VISIBLE ` from wordpress?

`if (window.ADMIN_BAR_VISIBLE) {
      Barba.Pjax.preventCheck = function() {
        return false;
      };
}`

**Comment by luruke** [comment]
```
function epic_enqueue_scripts() {
  wp_register_script('main', BASEURL . '/assets/scripts/main.min.js', array(), '1.0.0', true);
  wp_localize_script('main', 'SITE', array(
    'ADMIN_BAR_VISIBLE' => is_admin_bar_showing()
  ));
  wp_enqueue_script('main');
}

add_action( 'wp_enqueue_scripts', 'epic_enqueue_scripts' );
```

so, `window.SITE.ADMIN_BAR_VISIBLE` will be true/false based if the admin bar is visible or not.

**Comment by psntr** [comment]
I will try your code, meanwhile, I did this: 

`    if ($("#barba-container").hasClass("logged-in")) {
      Barba.Pjax.preventCheck = function() {
        return false;
      };
	}`

Seems to work, but as I'm quite weak at this, not sure if it's the right way? My apologies if my questions may seem stupid.

**Comment by luruke** [comment]
Yes, your solution works as well.
