### ISSUE TITLE
Uncaught (in promise) Error: xhr: HTTP code is not 200

### ISSUE THREAD

**Issue by magicspon** [luruke/barba.js#72]
Hello,

Firstly, this library is ruddy belting, top draw stuff, so many thanks... 

Anyhow, everything is working as expected but i'm getting the same error again and again and it seems to be quite random.

```
app.js:2995 Uncaught (in promise) Error: xhr: HTTP code is not 200
    at XMLHttpRequest.req.onreadystatechange 
req.onreadystatechange @ app.js:2995
app.js:2995 Uncaught (in promise) Error: xhr: HTTP code is not 200(…)req.onreadystatechange @ app.js:2995
```

It doesn't break my site, or cause any issues that a non dev user would see, but I'd quite like to get to the bottom of what's causing it.

Any tips on debugging this? 

Thanks

**Comment by luruke** [comment]
Hey @magicspon !
Do you have the prefetch enabled?

Basically what happens is that when you hover over a link it starts prefetching it, and in some cases this request can result in a 404 (or another xhr response code different from 200), that's why there is that log.

This may happens quite often especially if you are in development phase, where most of the links are temporary.

**Comment by magicspon** [comment]
@luruke 

Yes, I have prefetch enabled

`Barba.Prefetch.init();`

I've put `no-barba` on all of the anchors tags that don't go anywhere (eg href="#"), as well as the svg use tag.

eg
```
<svg>
  <use class="no-barba" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon"></use>
</svg>
```

All the other links link to pages that exist.  The site is still in development, but it's all hooked up with my cms so it's just waiting for the client to sign off, then it can go live, as is.

This is the code. https://gist.github.com/magicspon/e8353f0fc5a433ad01ee35aa06edc0b5
`views` is called on document ready

Thanks for the rapid reply

**Comment by theamnesic** [comment]
Hi guys,

I've got this error too, randomly when I click on a link, the page loads very slowly (around 5 seconds) and I've got this messages in the console :

![capture d ecran 2016-10-12 a 03 41 58](https://cloud.githubusercontent.com/assets/242203/19294607/755e47c0-902e-11e6-86c3-d3fe9c913363.png)

I have prefetch enabled too and no transition.

Can I help for any tests ?

Thanks!

— G

**Comment by luruke** [comment]
Hello @theamnesic , Can you inspect the HTTP request (network tab if you are using Chrome Devtools).

Apparently the page returns a code different then 200.

**Comment by kinkwilde** [comment]
I don't know if this helps, but... It seems to return a (canceled) status.

**Comment by mtwalsh** [comment]
It seems to happen when the page is slow to be returned, so switching on network throttling (GPRS) along with prefetching produces the same error consistently.

**Comment by luruke** [comment]
Thank you @mtwalsh @kinkwilde for your feedback.
I'll try to debug it as soon I have some free time.

Cheers

**Comment by theamnesic** [comment]
Hi @luruke , 

A screenshot of the headers : 

![capture d ecran 2016-12-02 a 18 47 19](https://cloud.githubusercontent.com/assets/242203/20844408/e6f7c384-b8bf-11e6-99f5-9e0d768feee4.png)

**Comment by hartey11** [comment]
Hi, I'm getting a similar issue.

When I go direct to zooba.wpengine.com/real-food it loads fine. But if you navigate to it from another page the promise errors and the page does a full refresh.

How do I debug this?

**Comment by luruke** [comment]
@hartey11 Looks fine here, do you have more infos about your issue?

**Comment by grenouille220** [comment]
I got a similar issue last week and I spent two hours to figure out that the server was returning a 301 for one of the page of my navbar (301 = permanent redirect). Working with cloud CMS forgetting  a slash or adding an unnecessary slash and boom, 301. Good to mention for _newbies_ like me as well that ajax won't work as expected while requesting an html page with a http response different than 200.

200 is 200. Basically two ways to inspect http headers with barba.js:
* using the browser developer console (Resources) as told earlier in this discussion
* using the terminal with tools like _wget_ or _curl_ to output http headers informations

Just my two cents. Cheers

**Comment by luruke** [comment]
Thank you @grenouille220 for your input.

**Comment by semajtwin** [comment]
Hi, @luruke just thought I'd let you know that I have been getting the same issues on a particular PC on localhost. At first I thought it's something to do with barba.js, however it worked on a simple example using a HTML pages.

I have just tried it out on a live WordPress site: http://tchc.com.mt/ and it worked without any issues. It just happens the localhost I'm using is a bit slow, I tried it out on another PC and it worked as well.

So it does seem to be an issue when the request takes a while. Not sure if this helps out in any way.

**Comment by cartogram** [comment]
I may have had some luck with this issue by passing a larger value to the XHR Timeout. The default is 5000.

```
    Barba.Utils.xhrTimeout = 10000
```

**Comment by xhostar** [comment]
cartogram... first, thanks for your idea of modifying xhrTimeout  parameter, but...

Firstly, i tried with 10000 like you say, however, my transition did not work fine 100%... (my script takes 15 seconds to respond, forced by using usleep(15 * 1000000);)

Finally, after several attempts, I tried setting 0 and... voila!, all worked!!

I have no idea if if's the right solution, but it works for me... however, plugin's developers should say something about it...

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout
