### ISSUE TITLE
onEnter within a BaseView doesn't always fire

### ISSUE THREAD

**Issue by JohnBlazek** [luruke/barba.js#73]
First off, have to say I'm really enjoying this library, I've been waiting for a library like this for so long, so thanks!

So the one thing I'm finding is that onEnter isn't consistently fired within my project. My assumption is that when newPageReady is fired, that it triggers onEnter within a BaseView. The first time I transition into a page, I'm noticing onEnter doesn't fire, however subsequent requests do trigger onEnter. Is this a known issue or am I mangling something in my project.

The workaround I think I have for this is that within my View, I have a "pageReady" function that I'm calling from the newPageReady event. So not sure if there is a better way to do this, or if I'm doing something wrong, just thought I'd point this out.

**Comment by luruke** [comment]
Hi @JohnBlazek 
It's quite strange what you are describing.

Are you sure that the namespace of your View match the one on the DOM?

As you can see in the code, a view is just a simple helper to manage events associated to a container.
https://github.com/luruke/barba.js/blob/master/src/View/BaseView.js#L42

Do you also have a demo/link you can share?

**Comment by JohnBlazek** [comment]
Hi @luruke, 

So yes, the namespace matches the one in the DOM. Unfortunately I don't have a demo to share (client reasons bah...) 

I'll expand further, whats funny is onEnterCompleted is triggered every time I change pages, but onEnter isn't every time. It usually is the first (or 2nd) time i make a page request that it is ignored. After that it is fine.

I'll also delve more into my codebase to make sure it isn't something funky I'm doing, for now, the workaround I have works, it just presented itself as an odd problem.

**Comment by luruke** [comment]
@JohnBlazek It's indeed very strange.
I've used barba.js on different project and I've never experienced something like this.

Would be helpful if you could replicate this bug in a small case scenario and share the code.
