### ISSUE TITLE
Barba + wordpress <head> styles not reloading

### ISSUE THREAD

**Issue by twoclickdesign** [luruke/barba.js#74]
Hello & thank for that plugin.

I'm using barba with wordpress and that almost working great. I just have smalls issues : 

**1.** 
From my home page when i go to  a new page : ok is work perfectly
   but if i go back to my home page, some height for few <div> are dynamically set via a js file : 
  but their values are not set again : 

`
$(window).ready( function() {
      var windowWidth = $(window).width();
      var windowHeight = $(window).height();
   $(".projet-container").css("height" , windowHeight * 0.9);
});
`
i also try to copy that code inside a : $(window).on('load', function() { ...
but that not working to

How can i tell to barba to reload my js ?

**2.** 
My structure look like  basically : 
< head > All my WP style and others...</ head >
< div class="content" >
< div id="barba-wrapper" >
	< div class="barba-container" >
		< section id="projects" >

.... content of my all page

		</ section >
	</ div >
</ div >
</ div >
< footer >< /footer >

**My problem is :** if i refresh my page after click on a link i just have the barba container working ? Same if someone arrive on a sub page 
 all of my head section is not loading. 
is that a way to change that. I think i can manage that if i put my barba container with head & footer inside but that loosing the ajax's goal if the whole page is reloading.

SORRY FOR MY POOR ENGLISH...

thank.

**Comment by luruke** [comment]
Hello @twoclickdesign .

Barba.js uses a PJAX technique, that means that it transforms your website in a kind of Single page application, so your JS is "loaded once".

To run some specific code when switch page you can use barba [events](http://barbajs.org/events.html) or [views](http://barbajs.org/views.html).

I also suggest you to read [this article](https://www.smashingmagazine.com/2016/07/improving-user-flow-through-page-transitions/) for more information on how barba.js works under the hood.

**Comment by twoclickdesign** [comment]
Thank. I manage my code to make it work. But it is shit code...

I try the views but without success. I guess i miss something. he return me error
