### ISSUE TITLE
Add new option appendContent: top/bottom

### ISSUE THREAD

**Issue by Splintex** [luruke/barba.js#76]
It would be great to make custom position of loaded content. It's bottom position of parent now because of this: `wrapper.appendChild(element);` It made me a problem when I was trying to
change only the top part of the page.

**Comment by luruke** [comment]
Hello @Splintex.

I never had this kind of problem, for example if I want to create a transition that requires to overlap the new and old content, it would be enough to set barba-wrapper as relative and then, the new container as position absolute.

Am I missing something?
Can you explain what you want to achieve?

Cheers.

**Comment by Splintex** [comment]
In case of my markup `<div id="barba-wrapper"><div class="barba-container"></div><span class="static-block"></span></div>` it would be great to put new `.barba-container` before `.static-block` but also I can change my markup. Yes, maybe it's bad idea to make this new option, what do you think?

**Comment by luruke** [comment]
I see now.

I would say it's easier if you keep just `barba-container` in the wrapper and move the static block in another main wrapper.
Adding an option will not solve all the edge-cases.
