### ISSUE TITLE
jQuery error with FancyBox 2.1.5.

### ISSUE THREAD

**Issue by derbenner** [luruke/barba.js#77]
In my testpage i Use jQuery 1.7, Fancybox 2.1.5 and Barba in latest Version.

when i click on a specific fancybox link (class=lightbox) it opens the Lightbox within opacity ~0.764734 and stucks, after a few seconds an alert apear and i can stop the jquery plugin, any idea?

**Comment by luruke** [comment]
Mhh, do you have an example you can share?
(Never used FancyBox)
