### ISSUE TITLE
Run Page transition after the View animation is complete

### ISSUE THREAD

**Issue by murillocamargo** [luruke/barba.js#79]
Hi, first of all thanks for this amazing library. I'm using it as a default for all my projects.

I'm having a problem trying to fire the site base transition after the view transition is completed.

For example, I'm using the FadeIn > FadeOut animation from the Barba.js documentation.

Here is the piece of code I'm trying to execute:

```
var About = Barba.BaseView.extend({

                namespace: 'about',

                onEnter: function () {
                    // **RUN FADEIN**
                },

                onLeave: function () {
                    $('html').velocity('scroll', {
                        offset: '0px',
                        duration: 1000,
                        delay: 5000
                    }).promise().done(function () {
                        // **RUN FADEOUT**
                    });
                }
            });
```

The complete JS is here: https://gist.github.com/murillocamargo/8f8bf416728a196783e68c2d195415fa

Thanks.

**Comment by luruke** [comment]
Hi @murillocamargo !
You should that logic inside your Barba transition and not in the View.

So, if I understand correctly, you want to scroll up just if you leaving the about page?
It's a logic you can add in the transition, you can check your old page using [Barba.HistoryManager](http://barbajs.org/docs/Barba.HistoryManager.html)

Hope it makes sense.
Cheers
