### ISSUE TITLE
Barba & RequireJS dont work ?

### ISSUE THREAD

**Issue by Flolax** [luruke/barba.js#80]
Hey,

I try to use barba with requireJS but an error occurs when loading the plugin "Uncaught ReferenceError: Barba is not defined"

http://pastebin.com/Rwdjz5VS <-- My code

Maybe I takes me wrong, any idea how to operate with requireJS barba?
Thanks! 

cc @luruke

**Comment by luruke** [comment]
I'm targeting `umd` in webpack config, so technically it should work with requirejs even if I never used it.

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("Barba", [], factory);
	else if(typeof exports === 'object')
		exports["Barba"] = factory();
	else
		root["Barba"] = factory();
})(this, function() {
```

have you tried with `Barba` (b uppercase)?

**Comment by Flolax** [comment]
Yes I tried but it does not work with the B uppercase.
However, I found a solution!


You must define the module thanks to the manual conversion

http://requirejs.org/docs/commonjs.html#manualconversion

```
define(function(require, exports, module) { // add this line for define module
    (function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define("Barba", [], factory);
    else if(typeof exports === 'object')
        exports["Barba"] = factory();
    else
        root["Barba"] = factory();
})(this, function() { ...
});
```

**Comment by 19h47** [comment]
I use Barba with requirejs and at first I had the same problem, but for me the capital B fixed the problem. Weird. 🤔

**Comment by Flolax** [comment]
@19h47 Le plus important c'est que ça marche :)

**Comment by 19h47** [comment]
@Flolax Je ne peux qu'être d'accord. 😁

**Comment by loup-brun** [comment]
I'm still experiencing `Barba not undefined` when trying to load `Barba` with `require.js`  – would have to manually edit the Barba source file to include @Flolax's fix.

Therefore this is still an issue.
