### ISSUE TITLE
Updating other meta tags besides title.

### ISSUE THREAD

**Issue by Burans** [luruke/barba.js#82]
Hi! Firstly - thanks for the great plugin!
Is it possible to update other tags inside `<head>` the same way `<title>` is updated by default?
I need to update facebook og meta tags.

Thank you!

**Comment by luruke** [comment]
Hi Burans!
It doesn't makes much sense update open graph tags, since when the facebook crawler (or other crawler) will hit the directly url they will fetch the right values.

In any case you can use the event `newPageReady`.
For more info have a look to the doc: http://barbajs.org/events.html

**Comment by Burans** [comment]
Hi @luruke!
Makes sense! Sorry for the silly question!

**Comment by grenouille220** [comment]
About this one, yes it's perfect for facebook... only ! Any other javascript pieces of codes like bookmarks, browser addon / extensions, etc... will just parse the current html document to retrieve the data. And 99% of the time they're parsing only the html header. They won't extract micro data or json-ld or whatever could be available inside the html body. Please reconsider it for the V2 please.

**Comment by riiccardo** [comment]
@luruke 
thanks for your great plugin i love it 😍 
can u show us code example in here ?? i'm Amateur :(

i see ur **StackOverFlow** comment but still confiused ...
and that **Gist** you shared now expired ..

**Comment by pierrehenri220** [comment]
@riiccardo I actually modified my username, the gist hasn't expired yet !
@iamrobert Thank you very much for the demo link
@luruke  Thanks for the mention on StackOverflow,  I appreciate :-)

So here it is, the updated the gist with the native js version from @min30327 at the same time.
- https://gist.github.com/pierrehenri220/58690c83d8c8d5c9308a35a240b34d69

Cheers to all

**Comment by dngraphisme** [comment]
Hi everyone, do you have a similar code for Barba V2 ? 

Thank you in advance to all
