### ISSUE TITLE
Keep old content visible while transitioning

### ISSUE THREAD

**Issue by rockethouse** [luruke/barba.js#85]
Hi, I'm trying to do a transition where the new content slides over the top of the old content, so I need both pages visible whilst the transition is in progress.... by default the new page is given visibility: hidden until the transition is finished. Is there any way around this?

**Comment by luruke** [comment]
Hi @rockethouse,
yes of course you can mix the new / old page together during your transition.
You can manually set `newContainer` as `visibility: visible` (after `newContainerLoading` is resolved).

Hope it makes sense.

**Comment by rockethouse** [comment]
Hi @luruke,

Okay great and how would I do that exactly? by actually modifying the .css() for the newContainer?

**Comment by luruke** [comment]
newContainer is an `HTMLElement`, you can set it with `newContainer.style.visibility = 'visible';` or if you want to really use jQuery: `$(newContainer).css('visibility', 'visible');`
