### ISSUE TITLE
How to disable cache and is it possible to disable it for one page only?

### ISSUE THREAD

**Issue by jeffceriello** [luruke/barba.js#86]
Ciao Luigi,

I don't really understand where to add 

`Barba.Pjax.cacheEnabled`

and set it to false.

Also, is it possible to disable cache only on one page?

Grazie!
Jeff

**Comment by luruke** [comment]
Hi @jeffceriello .
You can disable the cache adding:
```
Barba.Pjax.cacheEnabled = false;
```
before your `Barba.Pjax.start()`.

If you want to remove something from you cache, you can simple remove your page/item from the array `Barba.BaseCache.data`

**Comment by PhillyWebGuy** [comment]
Barba.BaseCache doesn't seem to exist (?)

![screen shot 2017-03-03 at 10 15 22 am](https://cloud.githubusercontent.com/assets/449963/23557173/22e9a1da-fffd-11e6-890c-884b19d62f45.png)
