### ISSUE TITLE
Add back button event 

### ISSUE THREAD

**Issue by magicspon** [luruke/barba.js#87]
Hola,

I'm not sure if this entirely required, but it might be useful to have an event fire when a user goes back in the browser.

Something like:

```
bindEvents: function() {
    document.addEventListener('click',
      this.onLinkClick.bind(this)
    );

    window.addEventListener('popstate',
      this.onStateChange.bind(this, true)
    );
  },
```

and 

```
// eg. es6 default property
onStateChange: function(back = false) {
    /*
      ... 
    */
    if(back) {
      Dispatcher.trigger('backButton',
        /* some arguments */
      );
    }
    /*
      ... 
    */
},
```

I added this to my version, but then realized I could achieve what I was after using the existing `initStateChange` event.

Anyhow, thanks for the superb script.

ta

**Comment by luruke** [comment]
Hi @magicspon ,
I never had need of it, but one solution could be to check `Barba.HistoryManager.history`.

This array contains the history of your navigation with Barba, you can easily check if the latest value is the same of the length-3

Hope it makes sense

**Comment by magicspon** [comment]
@luruke agreed...

**Comment by lonepalmus** [comment]
The HistoryManager doesn't guarantee that the backbutton was clicked? could have just as well gotten there via the navigation.

or how do you check in initStateChange that the backbutton was clicked, @magicspon ?

**Comment by magicspon** [comment]
@lonepalmus 

I set a default argument in the onStateChange method to false.  Then added another pop state event listener that set the argument to true.

Alternatively you could do something like
```
let clicked = false;
Barba.Dispatcher.on('linkClicked', (HTMLElement, MouseEvent) => {
    clicked = true
})

Barba.Dispatcher.on('initStateChange', function(currentStatus) {
	if(!clicked) {
		// backbutton was clicked
	}
});
```

**Comment by lonepalmus** [comment]
Great, thanks! just had the problem of the browser 'jumping' to the previous page scroll before I had the old faded out.. Now I can work around it :)
