### ISSUE TITLE
Google Analytics Issue

### ISSUE THREAD

**Issue by SergioVento90** [luruke/barba.js#88]
Hi,
It's not clear how can I update Google Analytics.
I've my script added to every page:
<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'xx-xxxxxxxx-x', 'auto');
      ga('send', 'pageview');

</script>
How I have to do to fix it? 
Thank you :)

**Comment by luruke** [comment]
Hello @SergioVento90 

Something like this should do the job:

```
Barba.Dispatcher.on('initStateChange', function() {
  if (typeof ga === 'function') {
    ga('send', 'pageview', location.pathname);
  }
});
```

**Comment by SergioVento90** [comment]
Oh really a fast answer :D 
I include this string on Barbajs?

**Comment by luruke** [comment]
You have to include that code anywhere on your website after loaded Barba.js

Cheers

**Comment by SergioVento90** [comment]
Perfect! Thank you

**Comment by hartey11** [comment]
Does this mean that 2 page views are counted when you first go on the site as initStateChange is fired on first load?

**Comment by bigskillet** [comment]
@luruke, will the code example you provided above

```
Barba.Dispatcher.on('initStateChange', function() {
  if (typeof ga === 'function') {
    ga('send', 'pageview', location.pathname);
  }
});
```
work with the new Google Analytics embed tag?

```
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-XXXXXXXX-1');
```

**Comment by northform** [comment]
bigskillet: It doesn't appear to be working for me anymore either with the new GA embed.

**Comment by BernhardBaumrock** [comment]
I came up with this one, seems to work:
```js
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  Barba.Dispatcher.on('initStateChange', function() {
    // modify to your needs
    var path = (window.location.href).replace(window.location.origin, '').toLowerCase();
    gtag('js', new Date());
    gtag('config', 'UA-XXXXXXX-1', {
      'anonymize_ip': true, // for GDPR
      'page_title' : document.title,
      'page_path': path
    });
  });
  </script>
```

**Comment by JayHoltslander** [comment]
I feel like this issue should be linked to on [the FAQ page](http://barbajs.org/faq.html) under
"_How can I update Google Analytics (or any other tracking sytem)?_"
