### ISSUE TITLE
Metas updates between pages

### ISSUE THREAD

**Issue by chleszgt** [luruke/barba.js#89]
Hi,

I saw a lot of answer in issues but still not sure of how to update metas between pages. I'm using YOAST to do this with Wordpress.
 
With this :
```
var originalFn = Barba.Pjax.Dom.parseResponse;

Barba.Pjax.Dom.parseResponse = function(response) {
 // do your stuff with the response
 console.log(response);
 return originalFn.apply(Barba.Pjax.Dom, arguments);
};
```
I see that metas desc change in response but it's not effective in dom.

Hope problem is clear and u could help me to solve this.

Thx,

**Comment by luruke** [comment]
Hello!
Why do you want to update those meta to the user when switching pages?
The crawler/bot is going to load that page directly and get the correct meta tags.

There was a similar issue here: https://github.com/luruke/barba.js/issues/82

**Comment by chleszgt** [comment]
👍
I believed metas doesn't update at all but it make sense as you say, dom with correct metas tags is ok when hit directly.
I did not see this issue, thx for prompt answer and for barba, very good project !
