### ISSUE TITLE
Woocommerce and barba

### ISSUE THREAD

**Issue by psntr** [luruke/barba.js#91]
Hi,

Again thank you for the developing this amazing plugin, I've been enjoying it for many projects and still do.

Today I bump on a weird issue, that seems to happen with PJAX and the WooCommerce plugin.

The problem: 
The links (button, color swatch…) behavior are working when you access the shop page directly, like `www.mysite.com/shop/ `
but once you access it from another page, let's say this one:
 `www.mysite.com/project/ `
to the shop, links are not working and all the links with `href="#"` would be added on the URL. 

I don't quite understand the issue here, because I copy and paste the output in HTML of both page, they seems to have the exact same content. And no javascript error in my console.

**Comment by psntr** [comment]
My temporary solution is not to use barba on the shop page which is a pity but at least the shop works. I simply added `$('li#shop a').addClass("no-barba");`

**Comment by luruke** [comment]
@psntr - Your issue is due that the Javascript code of woocommerce is not running.
Not sure if woocommerce has an API to "reload/launch" their binding/events.

**Comment by psntr** [comment]
@luruke Indeed, thank you! I guess if I want to still use barba on the shop page I should dynamically load the Woocommerce javascript. 

Source: http://stackoverflow.com/questions/805384/how-to-apply-inline-and-or-external-css-loaded-dynamically-with-jquery

**Comment by luruke** [comment]
I don't know woocommerce, but could be an idea.

Cheers

**Comment by theamnesic** [comment]
Hi @psntr, 

Same problem here...
Do you find a clean solution to load WC scripts ?

Thanks!

— G

**Comment by psntr** [comment]
Hello @theamnesic,

Sadly I didn't try to load the WC scripts… I just disabled barba on the shop page. I hope you will find a way to properly launch the WC codes. 

Good luck.

**Comment by theamnesic** [comment]
@psntr, 

Unfortunately, I think it's not possible to reload the WC script properly ...

Currently I use `$('.store a').addClass("no-barba")` and disable Ajax for "Add to Cart" buttons and "Remove product" from cart.

I'll advise you if I find a better solution!

**Comment by ElliGator** [comment]
Has there been any progress on this issue? It seems that I cannot get Barba to work with Woocommerce's cart ajax. Styles aren't loaded and break the scripts.

**Comment by georgal** [comment]
> @psntr,
> 
> Unfortunately, I think it's not possible to reload the WC script properly ...
> 
> Currently I use `$('.store a').addClass("no-barba")` and disable Ajax for "Add to Cart" buttons and "Remove product" from cart.
> 
> I'll advise you if I find a better solution!

This is the most solid workaround in case you want to skip the ajax issues fast and reliably! 
good job
