### ISSUE TITLE
Transition not firing for prefetched pages in Safari/Edge

### ISSUE THREAD

**Issue by tipsy** [luruke/barba.js#92]
I'm trying to prefetch all links in my application, but it seems to kill the transition in Safari (and Edge, not that it matters a lot). It works fine in chrome/opera/firefox on win/osx/android. My code:

```
document.querySelectorAll("a").forEach(anchor => {
    var xhr = Barba.Utils.xhr(anchor.href);
    Barba.Pjax.Cache.set(anchor.href, xhr);
});
```

Is this a known issue, or am I doing something wrong?

**Comment by luruke** [comment]
Hello @tipsy, thanks for the issue.
I'll try to debug it later in the day 👍

**Comment by rockethouse** [comment]
I think i'm experiencing a similar issue... on all other browsers transitions work fine, but in Safari sometimes (not always) a new page will skip the transition and just appear.

**Comment by rockethouse** [comment]
Edit: I'm noticing some odd behaviour in Safari on two machines (so its not just my machine) and I'm not even sure it's related to Barba, but Im finding some css properties are not being applied properly on load of a new page... ie one class has top:100% which then translates to top:0% - If i manually remove and add the class that sets the top to 100%, it will only take effect (move to 100%) after I manually add it back. Does that make sense?

**Comment by tipsy** [comment]
@luruke I've noticed another strange thing about this. When prefetching the back-link, transition works:

Works on Safari:
```
if (Barba.HistoryManager.prevStatus() !== null) {
    prefetch(Barba.HistoryManager.prevStatus().url);
}
```
