### ISSUE TITLE
Demo's for download?

### ISSUE THREAD

**Issue by zokka79** [luruke/barba.js#94]
Hey,

This isn't an issue, but could you make the demos downloadable as a zip? I would really want to use your awesome barba.js in my next design. I would just need some good examples with codes, so i could start exploring this more. id really like to make something like this awesome site...

http://www.buildinamsterdam.com/

Br, jukkasoininen.com

**Comment by luruke** [comment]
Hello @zokka79 
The code of examples are available on the branch gh-pages:
https://github.com/luruke/barba.js/tree/gh-pages/demo

Cheers

**Comment by zokka79** [comment]
Thank you so much!

L?hetetty iPhonesta

Luigi De Rosa <notifications@github.com<mailto:notifications@github.com>> kirjoitti 5.12.2016 kello 16.02:


Hello @zokka79<https://github.com/zokka79>
The code of examples are available on the branch gh-pages:
https://github.com/luruke/barba.js/tree/gh-pages/demo

Cheers

-
