### ISSUE TITLE
Struggling with events for updating navigation

### ISSUE THREAD

**Issue by zreese** [luruke/barba.js#95]
Maybe along the same lines as #74, but I'm having trouble updating content outside of the barba container using events. I get an `Uncaught TypeError: Cannot read property 'classList' of null(…)` when adding the active class.  Any help would be greatly appreciated. 

```
    Barba.Dispatcher.on('newPageReady', function(currentStatus) {
		const link = currentStatus.url.split(window.location.origin)[1].substring(1);

        const navigation = document.querySelector('.navbar-nav');
        const navigationLinks = navigation.querySelectorAll('.menu-item');
        const navigationLinkIsActive = navigation.querySelector(`[href="${link}"]`);

        Array.prototype.forEach.call(navigationLinks, (navigationLink) => navigationLink.classList.remove('active'));

        // this next part is returning an error for some reason?
		// Cannot read property 'classList' of null(…)
			navigationLinkIsActive.classList.add('active');
    });
```

**Comment by jonnyscholes** [comment]
@zreese  Do you have a staging/live/test site anywhere with this happening on it we could look at? More context always helps :)

I can't see a Barba.js related issues with your code - my suspicion is that `[href="${link}"]` isnt matching anything. Is `link` what you would expect it to be and *exactly* what you would find in the relevant `href` (including slashes etc)?

**Comment by zreese** [comment]
I have a development server but I would be 100% fired if I shared the URL publicly... can I email it to you somehow?

The output for `link` appears to be correct. At the very least, it's what *I* expect it to be, but I'm using wordpress, so I wonder if it has something to do with how wordpress handles the navigation.

**Comment by luruke** [comment]
the problem is that your `navigationLinkIsActive ` is undefined.

If you are not using partial content, you can get the 4th parameter of `newPageReady` event, read the new html and then update the menu active class.

See here for more info: http://barbajs.org/events.html

**Comment by zreese** [comment]
@luruke Thanks for the help. Would you be able to elaborate a bit or maybe provide some code? When I log `newPageRawHTML` I only see the URL for the page I'm transitioning away from, so I'm not sure what to do.

**Comment by luruke** [comment]
@zreese Make sure your running the latest version, then:
```
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, rawHTML) {
 console.log(rawHTML);
});
```

**Comment by zreese** [comment]
Sorry if I'm being overly dense, but rawHTML outputs the entirety of the page... how would that help in updating the active menu item? If I'm going to return the page on a transition every time it seems like it'd be more efficient to just move everything inside the barba container.

**Comment by luruke** [comment]
@zreese, having the full HTML you can easily detect in the "new menu" which is the active class.

So:
- Detect the new active class in the new HTML
- Remove all the active class in the current menu
- Add the active class in the current menu

**Comment by zreese** [comment]
I appreciate the help. At this point that's a little too kludgy to be a shippable solution so we're just going to take barba out of the project. Thanks, though.
