### ISSUE TITLE
Barba.js detected as Virus

### ISSUE THREAD

**Issue by sethstha** [luruke/barba.js#96]
While i was exploring about barba. I made a decision to give it a shot. When i downloaded barba from github. Google chrome detected it as a virus. Then i used raw file and saved it. But the windows defented also detected it as virus.

Here are the screenshots
![image](https://cloud.githubusercontent.com/assets/2367137/21044069/2f2c5c5c-be22-11e6-9056-75bdb6fc856b.png)

![image](https://cloud.githubusercontent.com/assets/2367137/21044090/4e00ea76-be22-11e6-8721-6df193585a13.png)

Thank you

**Comment by dmarkowicz** [comment]
Looks like false positive or problem with your local files. Current package is clean and not detected by any antyvirus software. Please see scan results:
https://www.virustotal.com/en/file/b7ef625764a43548fb1431487cd86dd1f7e157b0d959427d6a3ce64364a77fc4/analysis/1481369082/
https://www.virustotal.com/en/file/7638bfbceff6b808b0c2e7fc345586d3d5d2c1607da16c0554850733fda95fe4/analysis/1481369785/
https://www.virustotal.com/en/file/1f44cf29900fe3eb8a981a67b5450caca807e155c140d0d9ba6ba7e9fbda9f8c/analysis/1481369921/

**Comment by sethstha** [comment]
This is only detected by Windows Defender and not being detected by any other antivirus. I will scan my computer if it is infected. I will be updated about it.

Thank you

**Comment by sethstha** [comment]
Windows Defender latest virus definition is detecting it as virus. While on my personal laptop with an older version of definition is not detecting it as virus. Here is another screenshot

![image](https://cloud.githubusercontent.com/assets/2367137/21087443/ef4b37d8-c04d-11e6-931c-96ec3b041ce2.png)

I am not going to take a shot while Windows Defender is detecting it as Trojan Win32/Sprisky.D!cl

Please have a look at it. 
Thanks

**Comment by luruke** [comment]
@sethstha It's definitely a false positive.
You might ask more information to Windows Defender support, unfortunately there is nothing we can do about it.

Thank you,
Cheers
